DDS-1295 [Breadcrumb] Retouching
dsv-rp/DDS pull request #104
Opened 2024-12-03 05:48 UTC by poetrainy

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1295](https://daikinsvoil.atlassian.net/browse/DDS-1295)

## Design

- [FIgma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/bVhR5wTRjND1WxUStnRYkP/DDS%3A-Design-Kit?node-id=44779-2003&node-type=section&m=dev)

## Checklist

- [x] I have added a changeset file that describes the changes.
      _Hint_: run `npx changeset`.
- [x] I have performed a self-review of my code.
- [x] I have added/updated appropriate regression tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.
      _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the bug fix does not affect the keyboard accessibility of the component.
- [x] I have confirmed that the fix does not introduce any new visual regressions.

If you don't feel that the PR is ready for review, please create the PR in draft status.

2024-12-05 08:08 UTC, yodas7 commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +        ></span>`;
We use `<a>` without `href` for placeholder links.
Can't we use `<daikin-link>` for current link?

2024-12-06 03:09 UTC, poetrainy commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +        ></span>`;
@yodas7 
This implementation was chosen because daikin-link does not have a style similar to current.
It was also difficult to overwrite the class.

2024-12-06 07:20 UTC, yodas7 commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +        ></span>`;
@poetrainy 
Then just use `<a>` instead of span.

2024-12-06 07:21 UTC, yodas7 requested changes
Wrote comment.

2024-12-10 07:52 UTC, yodas7 commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +  showDivider = false;
nit. I'd like to make the position of the divider clear.

```suggestion
  @property({ type: Boolean, reflect: true, attribute: "append-divider" })
  appendDivider = false;
```

2024-12-10 07:52 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.ts
> +      item.showDivider = index < items.length - 1;
Try not to use different expressions (`!==` and `<`) to mean the same thing.

```suggestion
      const isLast = index === items.length - 1;
      item.variant = isLast ? "current" : "normal";
      item.showVisited = this.showVisited;
      item.appendDivider = !isLast;
```

2024-12-10 07:52 UTC, yodas7 commented on .changeset/long-cats-visit.md
> +Breadcrumb Item: Updated appearance. (DDS-1642)
The attributes are kebab case. Camel case is used for the properties.

```suggestion
**BREAKING CHANGE** Breadcrumb: The `trailing-slash` and `overflow` attributes have been removed. (DDS-1642)
**BREAKING CHANGE** Breadcrumb Item: The `trailing-slash` attribute has been removed. (DDS-1642)
**BREAKING CHANGE** Breadcrumb Item: The `ellipsis` value of the `variant` attribute has been removed. In addition, the `current` value has been added. (DDS-1642)
Breadcrumb: The `show-visited` attribute has been added. (DDS-1642)
Breadcrumb: Updated appearance. (DDS-1642)
Breadcrumb Item: The `show-visited` attribute has been added. (DDS-1642)
Breadcrumb Item: Updated appearance. (DDS-1642)
```

2024-12-10 09:39 UTC, yodas7 approved these changes

2024-12-12 07:01 UTC, ukkary approved these changes

2024-12-13 08:01 UTC, merged