DDS-1513 Integrate Design Tokens (1/3: Base Integration)
dsv-rp/DDS pull request #105
Opened 2024-12-10 05:42 UTC by yodas7

Split from #76.

2024-12-11 01:27 UTC, hiro-daikin requested changes

2024-12-11 01:27 UTC, hiro-daikin commented on package.json
> +    "@daikin-oss/dds-tokens": ">=0.3.0 <1.0.0"
This is fine - we just need to mention this in our documentation

2024-12-11 01:27 UTC, hiro-daikin commented on src/index.ts
> -export * from "./colors";
Dosatsu currently uses the color palette. 
Where and how would users get the color palette values from?

2024-12-11 01:33 UTC, yodas7 commented on src/index.ts
> -export * from "./colors";
@hiro-daikin 
If users need color codes, they should import them from `@daikin-oss/dds-tokens`.
On the other hand, using color codes directly will result in a lack of theme support, so if possible, I would recommend using them in a way like `var(--dds-color-blue-40)`.

In any case, I think that these are the responsibilities of `@daikin-oss/dds-tokens` and `@daikin-oss/plugin` now that the design tokens have been established.

2024-12-11 01:36 UTC, yodas7 commented on package.json
> +    "@daikin-oss/dds-tokens": ">=0.3.0 <1.0.0"
I've updated README to install `@daikin-oss/dds-tokens` as well.
https://github.com/dsv-rp/DDS/pull/105/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

2024-12-12 06:51 UTC, hiro-daikin commented on src/index.ts
> -export * from "./colors";
I agree that it should probably be the responsibility of other packages.
This is a breaking change, however, and should be included in the changeset

2024-12-12 06:52 UTC, hiro-daikin commented on package.json
> +    "@daikin-oss/dds-tokens": ">=0.3.0 <1.0.0"
@yodas7 Hopefully this is also included in our zeroheight documentation

2024-12-12 06:52 UTC, hiro-daikin approved these changes

2024-12-13 05:52 UTC, ukkary approved these changes

2024-12-13 05:53 UTC, merged