feat: Implemented a new carousel component
dsv-rp/DDS pull request #109
Opened 2024-12-12 03:13 UTC by poetrainy

This PR adds Carousel (`daikin-carousel`, `daikin-carousel-item`) component.

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1296](https://daikinsvoil.atlassian.net/browse/DDS-1296)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/w7HdaKXLx1AsAJe1c9j9Yq/DDS%3A-Design-Kit?node-id=43238-623&node-type=canvas&m=dev)

## API Design

- [JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3087040534/Carousel+Component+API)

## How Has This Been Tested?

### Visual Regression Tests

- \[Ghost; Fill\] variants matrix.

### Interaction Tests

- Pressing the `next` button switches to the next slide
- When the last slide is displayed, the `next` button is inactive
- Pressing the `prev` button switches to the previous slide
- When the first slide is displayed, the `prev` button is inactive
- Pressing the indicator switches to that slide
- Clicking on the slide fires the corresponding event

## Checklist

- [x] I have added a changeset file that describes the changes.  
       _Hint_: run `npx changeset`.
- [x] I have performed a self-review of my code.
- [x] I have added appropriate visual regression tests.
- [x] I have added appropriate interaction tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.  
       _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the component can be operated using only the keyboard.
- [x] I have confirmed that the focus state of the component is visually discernible.

2024-12-19 03:05 UTC, yodas7 requested changes
- The display is strange when `animation` set to `manual`
- Maybe we should use [scroll snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_snap/Basic_concepts).

2024-12-19 03:05 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +            )}
Try doing `calc` inside tailwind css.

```html
<div
  style=${`--total:${this._itemCount};--current:${this.currentIndex};`}
  class="w-[calc(100%*var(--total))] translate-x-[calc(-100%*var(--current)/var(--total))] ..."
>...</div>
```

2024-12-19 03:05 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +                aria-selected=${`${this.currentIndex === index}` as const}
I think we can do this

```suggestion
                aria-selected=${this.currentIndex === index}
```

2024-12-19 03:05 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +      this._items.forEach((item, i) => (item.active = i === this.currentIndex));
nit.

```suggestion
      for (const [index, item] of this._items.entries()) {
        item.active = index === this.currentIndex;
      }
```

2024-12-19 03:22 UTC, poetrainy commented on src/components/carousel/daikin-carousel.ts
> +  duration = 600;
@yodas7 
I would like to know why it has to be a custom property.
I made it an attribute because I thought it was an item that would often be customized depending on the usage scenario.

2024-12-19 04:32 UTC, poetrainy commented on src/components/carousel/daikin-carousel.ts
> +            )}
@yodas7 
For example, when the user specifies a fade animation with animation=“manual”, I thought it would be inconvenient if the width was derived using `calc`.

2024-12-19 05:31 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  duration = 600;
@poetrainy 
Since the `duration` prop is only used by `--translate-transition-duration: ${duration}ms`, instead of preparing the property, we can just use `var(--ddc-transition-duration, 600ms)` or something like that.
Users can set `--ddc-transition-duration` property to override duration.

2024-12-19 05:51 UTC, poetrainy commented on src/components/carousel-item/daikin-carousel-item.ts
> + * @fires carousel-click - It fires when clicked on with daikin-carousel-item. Normally, daikin-carousel-item does not receive focus directly. Also, when there is a click operation on the item part o
@yodas7 
I deleted the click event for the carousel, but I don't know how to pass the keyboard event that occurs in the item container of daikin-carousel to daikin-carousel-item.

2024-12-19 06:01 UTC, poetrainy commented on src/components/carousel/daikin-carousel.ts
> +  duration = 600;
@yodas7 
I thought that setting properties would be more familiar to users than setting CSS variables. It's easy to imagine that there would be an item for manipulating the duration of the animation.
Should it be defined using CSS variables instead?

2024-12-19 07:09 UTC, poetrainy commented on src/components/carousel-item/daikin-carousel-item.ts
> +      class="flex-none size-wit overflow-hidden"
It was deleted and replaced with an existing event.

2024-12-19 07:09 UTC, poetrainy commented on src/components/carousel-item/daikin-carousel-item.ts
> + * @fires carousel-click - It fires when clicked on with daikin-carousel-item. Normally, daikin-carousel-item does not receive focus directly. Also, when there is a click operation on the item part o
It was deleted and replaced with an existing event.

2024-12-19 07:11 UTC, poetrainy commented
@yodas7 
> The display is strange when animation set to manual
I have decided not to specify the width explicitly, as we think that users who want to set the animation manually may not necessarily want it to be displayed in a slide-like format.

2024-12-23 04:40 UTC, poetrainy commented
The following corrections have been made.

- Carousel items now display outlines when the focus is on the content.
- Carousel items now automatically have aria-label assigned to them, rather than arbitrary values.

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +          @mouseup=${this._handleMouseup}
Not sure if we should listen to mouse as well.
How are the competitors doing?

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  }
Handle slotchange

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel/stories/framework-wc.ts
> +  "flex justify-center items-center w-full h-[400px] text-ddt-color-common-text-primary bg-ddt-color-common-disabled";
Move this to common.ts

2024-12-23 07:28 UTC, yodas7 commented on src/utils/is-similar-to-click.ts
Maybe this file is no more needed.

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel-item/stories/framework-wc.ts
> +  "flex justify-center items-center w-full h-[400px] text-ddt-color-common-text-primary bg-ddt-color-common-disabled";
Move this to common.ts

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  "aria-[selected=true]:focus-visible:after:outline-ddt-color-common-border-focus",
They can be simplified to `aria-selected:...`

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +    this._swipeEndX = e.changedTouches[0].pageX;
I think it would be good if the slide moved while swiping (like scrolling).

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +    if (Math.abs(result) < 10) {
Not sure if we should use `10`.

2024-12-23 07:28 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +      },
nit.

```suggestion
      icon: {
        chevronLeft: ["i-daikin-chevron-left"],
        chevronRight: ["i-daikin-chevron-right"],
      },
```

or

```suggestion
      intent: {
        previous: ["i-daikin-chevron-left"],
        next: ["i-daikin-chevron-right"],
      },
```

2024-12-24 00:24 UTC, poetrainy commented on src/components/carousel/daikin-carousel.ts
> +          @mouseup=${this._handleMouseup}
@yodas7 
For this implementation, I referred to Bootstrap and shadcn/ui.
Only shadcn/ui allows swiping, and mouse operation was also possible.
https://ui.shadcn.com/docs/components/carousel

2024-12-24 05:49 UTC, poetrainy commented on src/components/carousel/daikin-carousel.ts
> +          @mouseup=${this._handleMouseup}
@yodas7 
I'm sorry, but I've removed this because there were problems with the mouse swipe operation when it was possible to focus on the carousel item.

2024-12-24 08:39 UTC, poetrainy commented
When displaying the first or last item, should it stop after a certain amount of swiping if you try to swipe in the direction where there are no items? (Reference: [shadcn/ui](https://ui.shadcn.com/docs/components/carousel))

2024-12-24 08:40 UTC, poetrainy commented
@yodas7 
When displaying the first or last item, should it stop after a certain amount of swiping if you try to swipe in the direction where there are no items? (Reference: [shadcn/ui](https://ui.shadcn.com/docs/components/carousel))

2024-12-24 09:00 UTC, yodas7 commented
@poetrainy 
I think so. shadcn looks very high quality.
However, if it becomes too complicated because of this function, it may be worth considering excluding it from the first release.

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +    this._emitSelect(moveOffset === 1 ? "next" : "prev", beforeCurrentIndex);
nit. When performing this kind of validation, it is safer to calculate the values that are scheduled to be changed in advance and determine whether they are appropriate or not.

```suggestion
    const newIndex = this.currentIndex + moveOffset;
    if (newIndex < 0 || newIndex >= this._itemCount) {
      return;
    }

    const oldIndex = this.currentIndex;
    this.currentIndex = newIndex;
    this._emitSelect(moveOffset === 1 ? "next" : "prev", oldIndex);
```

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  }
I think we don't need this as `slotchange` event will be emitted first time. Could you try it?

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +    if (Math.abs(this._swipeX) < 10) {
This should at least be a constant.

2024-12-24 09:25 UTC, yodas7 commented on .changeset/itchy-seahorses-arrive.md
> +Added Carousel Component. (DDS-1296)
nit.

```suggestion
---
"@daikin-oss/design-system-web-components": minor
---

Carousel: Initial Implementation. (DDS-1296)
```

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +      isSwipe: {
nit.

```suggestion
      swiping: {
```

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  private _isSwipe = false;
nit.

```suggestion
  private _swiping = false;
```

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  private _swipeX = 0;
nit.

```suggestion
  private _swipeOffsetX = 0;
```

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  duration = 600;
@poetrainy 
Deciding how to design something is a difficult problem that requires consideration of various aspects such as usability and performance.
I think that things that are only used in CSS should be completed in CSS. This also contributes to improving performance by reducing the number of renderings.

2024-12-24 09:25 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  }
I'm not sure if it's safe to reference `[0]` always.
Also, should we start swiping when two or more fingers are touching?

2024-12-25 00:54 UTC, poetrainy commented
@yodas7 
Swipe is not included in the requirements from the designer, so I think it's fine to delete it.

2024-12-25 01:22 UTC, poetrainy commented on src/components/carousel/daikin-carousel.ts
> +  }
@yodas7 
Since swiping involves using one or more fingers to operate the screen, I've made it so that it refers to `[0]`.
It seems that using two or more fingers means a different action (e.g. pinch zoom), but I think it also works as a swipe. I can't verify this on the actual device, though.

2024-12-25 01:25 UTC, poetrainy commented on src/components/carousel/daikin-carousel.ts
> +  duration = 600;
Okay, I will.

2024-12-25 07:58 UTC, yodas7 commented
Let's remove swipe feature. It might be too complex for now.

2024-12-26 07:49 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +    ) {
Now we don't have to look `moveOffset`.

```suggestion
    if (newIndex < 0 || newIndex >= this._itemCount) {
```

2025-01-10 08:53 UTC, yodas7 commented on src/components/carousel/daikin-carousel.ts
> +  allowSwipe: boolean = false;
It doesn't seem to be used anymore.

2025-01-14 05:24 UTC, yodas7 approved these changes
LGTM

2025-01-15 02:21 UTC, hiro-daikin approved these changes

2025-01-17 01:18 UTC, merged