DDS-1209 [Card] Add Card Component
dsv-rp/DDS pull request #111
Opened 2024-12-16 03:36 UTC by rinjInTokyo

This PR adds Card (`daikin-card`) component.

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1209](https://daikinsvoil.atlassian.net/browse/DDS-1209)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/DDS%3A-Design-Kit?node-id=3406-2962&node-type=canvas&m=dev)

## API Design

- [JIRA Wiki (card)](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3103522843/Card+Component+API)
- [JIRA Wiki (card header)](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3399778419/Card+Header+Component+API)
- [JIRA Wiki (card footer)](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3103555618/Card+Footer+Component+API)

### Visual Regression Tests

- Card
    -  \[outline; ghost;\] with border and \[body; footer; both\] structure.
- Card Header
    -  \[icon; description; both;\] structure
- Card Footer
    -  \[button; link;\] the action element in footer

### Interaction Tests

- Because it's a wrap component so not interaction now

## Checklist

- [x] I have added a changeset file that describes the changes.  
       _Hint_: run `npx changeset`.
- [x] I have performed a self-review of my code.
- [x] I have added appropriate visual regression tests.
- [x] I have added appropriate interaction tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.  
       _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the component can be operated using only the keyboard.
- [x] I have confirmed that the focus state of the component is visually discernible.

2024-12-17 06:56 UTC, yodas7 reviewed
✅ HTML tags & ARIA roles (Radix UI, MUI)
✅ Component Sizable

2024-12-17 06:56 UTC, yodas7 commented on src/components/card-header/daikin-card-header.ts
> +  "text-ddt-color-common-text-primary",
```suggestion
  "flex-none",
  "text-ddt-color-common-text-primary",
```

2024-12-17 06:56 UTC, yodas7 commented on src/components/card-header/daikin-card-header.ts
> +]);
```suggestion
])();
```

2024-12-17 06:56 UTC, yodas7 commented on src/components/card-header/daikin-card-header.ts
> +  "text-ddt-color-common-text-secondary",
```suggestion
  "flex-none",
  "text-ddt-color-common-text-secondary",
```

2024-12-17 06:56 UTC, yodas7 commented on src/components/card-header/daikin-card-header.ts
> +]);
```suggestion
])();
```

2024-12-17 06:56 UTC, yodas7 commented on src/components/card/daikin-card.ts
> +    "flex-col",
nit.

```suggestion
    "flex",
    "flex-col",
    "gap-4",
    "p-4",
    "rounded-lg",
    "bg-ddt-color-common-background-default",
```

2024-12-17 07:20 UTC, rinjInTokyo commented on src/components/card-header/stories/framework-react.tsx
> +    <div style={{ width: 248 }}>
@yodas7 
> an unit is needed (px?)

Miss that

> not sure why 248.

The header's width spans the entire available space, so I try to set it to match the width specified in the figma design to look better and improve the accuracy of visual testing.

2024-12-18 01:19 UTC, rinjInTokyo commented on src/components/card-header/daikin-card-header.ts
> +      <slot name="left-icon" class="text-ddt-color-common-text-primary"></slot>
It seems `size-6 icon-size-full` will always hold a 24px space even there is no icon. So I refer to button component to use `icon-size-6`

2024-12-18 06:13 UTC, yodas7 commented on src/components/card-header/daikin-card-header.ts
> + *   <span>Label Title</span>
nit.

```suggestion
 *   <span>Card Title</span>
```

2024-12-18 06:31 UTC, yodas7 commented on src/components/card-footer/daikin-card-footer.ts
> +    return html` <slot></slot> `;
```suggestion
    return html`<slot></slot>`;
```

2024-12-18 06:31 UTC, yodas7 commented on src/components/card-header/daikin-card-header.visual.test.ts
> +      label: "Label Title",
nit.

```suggestion
      label: "Card Title",
```

2024-12-18 06:31 UTC, yodas7 commented on src/components/card/stories/framework-react.tsx
> +        <span>Label Title</span>
nit.

```suggestion
        <span>Card Title</span>
```

2024-12-18 06:31 UTC, yodas7 commented on src/components/card/stories/framework-wc.ts
> +        <span>Label Title</span>
```suggestion
        <span>Card Title</span>
```

2024-12-18 06:31 UTC, yodas7 commented on .changeset/calm-apes-allow.md
> +Add Card Component. (DDS-1209)
We now treat new component as minor update, though it does not include breaking changes.

```suggestion
---
"@daikin-oss/design-system-web-components": minor
---

Card: Initial Implementation. (DDS-1209)
```

2024-12-19 03:07 UTC, yodas7 requested changes

2024-12-19 03:07 UTC, yodas7 commented on src/components/card-footer/index.ts
> +export * from ".//daikin-card-footer";
```suggestion
export * from "./daikin-card-footer";
```

2024-12-19 05:25 UTC, yodas7 approved these changes
LGTM

2024-12-20 19:06 UTC, hiro-daikin approved these changes

2024-12-24 08:12 UTC, merged