feat: Implement Text Input Component and Input Group Component
dsv-rp/DDS pull request #13
Opened 2024-07-03 03:30 UTC by poetrainy

This PR adds Text Input (`daikin-text-input`) component and Input Group (`daikin-input-group`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-910](https://daikinsvoil.atlassian.net/browse/DDS-910)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/wHAhw4yC54Hjq6Whb8FL5T/DDS%3A-Design-Kit?node-id=22399-43&t=An87ScyMGOvltVbf-0)

## API Design

Not yet added

## How Has This Been Tested?

- VRT (Visual Regression Test) for error and required and [Normal; Hover; Pressed; Disabled] line matrix.
- When disabled, input cannot be selected.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-07-03 05:07 UTC, yodas7 requested changes

2024-07-03 05:07 UTC, yodas7 commented on src/components/input-group/stories/daikin-input-group-react.stories.tsx
> +                'Message to display in case of error. If disabled is true, ignore this.',
```suggestion
                'Error text to place at the bottom of the field. If specified, sets the `error` property of the element in the slot to `true`. Ignored if the `disabled` is `true`.',
```

2024-07-03 05:07 UTC, yodas7 commented on src/components/input-group/stories/daikin-input-group-react.stories.tsx
> +            description: 'When input is required, give an explicit mark',
```suggestion
            description: 'Whether the field is required. An additional star mark will be added if `true`.',
```

2024-07-03 05:07 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +        }
I think we should reflect `required` too.

2024-07-03 05:07 UTC, yodas7 commented on src/components/input-group/stories/daikin-input-group-react.stories.tsx
> +            description: 'Whether the field is disabled',
```suggestion
            description: 'Whether the field is disabled. Reflected in the `disabled` property of the input in the slot.',
```

2024-07-03 05:07 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +                      >${this.label}${this.required ? ' *' : ''}</label
Just an idea - " *" can be represented by using `after` pseudo element, as it's only meant for visual effect.

2024-07-03 06:50 UTC, poetrainy commented on src/components/text-input/daikin-text-input.ts
> +            autocomplete="${(this.autocomplete ?? nothing) as any}"
I modified it to `ifDefined`.

2024-07-03 06:50 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> +                      >${this.label}${this.required ? ' *' : ''}</label
I have modified it accordingly.

2024-07-03 06:57 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +                : null}
I meant to put one `<label />` under the `<fieldset />` to bind everything together.

2024-07-03 07:04 UTC, yodas7 requested changes

2024-07-03 07:04 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +        }
Calling `_handleSlotChange` from `updated` is actually not a good idea, as this will be a problem if ウェ try to add a dedicated process for `slotchange` in the future.
Create another method (for example, `_reflectSlotProperties`) for this logic and call it from `_handleSlotChange` and `updated` method.

2024-07-03 07:10 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> +                : null}
I was mistaken. I have corrected it as such.

2024-07-03 07:13 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> +        }
Thank you for teaching me. I made a modification to define the new `_reflectSlotProperties`.

2024-07-03 07:20 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +                this.dispatchEvent(new Event('keydown', e))}"
I mean we should use `new KeyboardEvent(...)` and `new InputEvent(...)` instead of `new Event(...)`.
Also `e: Event` in `@input` should be `e: InputEvent`.

2024-07-03 07:33 UTC, yodas7 commented
@poetrainy 
Two conversations are remain unresolved.

2024-07-03 08:00 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +        }
Specifying `required` for native elements is necessary for accessibility, but since this is also related to other components, we'll postpone for now.

2024-07-03 08:21 UTC, yodas7 requested changes
Very good. Suggested a bit of a challenge.

2024-07-03 08:21 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    input-group-bottom-text-error
```suggestion
    color-[--color-feedback-negative]
```

with

```
:host {
  --color-feedback-negative: ${unsafeCSS(colorFeedbackNegative)};
}
```

might be better

2024-07-03 08:21 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +        }
Cloud you try using TailwindCSS for these styles by using CSS custom props?

2024-07-04 00:39 UTC, poetrainy commented on src/components/text-input/daikin-text-input.ts
> +        }
Thank you for the suggestion. I have modified it that way.

2024-07-05 06:29 UTC, yodas7 requested changes

2024-07-05 06:29 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      --button-color-background-secondary-hover: ${unsafeCSS("#CECECE")};
Confusing name; the design token used in TextInput must be from TextInput. If there is a token from another component with the same value, it is a coincidence.
If the token for TextInput is not yet provided, then it should be treated as a missing token.

Also, there is no need to use unsafeCSS for fixed values.

```suggestion
      --input-text-color-...: #......;
      --input-text-color-...: #......;
      --input-text-color-...: #CECECE;
```

2024-07-05 06:29 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +  @property({ type: Boolean })
Might be good to reflect

2024-07-05 06:29 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +  static formAssociated = true;
readonly?

2024-07-05 06:29 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      this.error ? textInputError : "border-daikinNeutral-600",
`disabled` should be checked here, per component docs.

2024-07-05 06:29 UTC, yodas7 commented on src/components/text-input/stories/react.ts
> +        keydown: 'keydown',
```suggestion
        onChange: 'change',
        onInput: 'input',
        onKeyDown: 'keydown',
```

2024-07-05 07:43 UTC, poetrainy commented on __test__/InputGroup.test.js
> +    describe.each(['disabled', 'enabled'])('%s', (state) => {
There is no difference in style with readonly.
Am I correct in my understanding that I should make sure that the readonly attribute is given?

2024-07-05 07:46 UTC, yodas7 commented on __test__/InputGroup.test.js
> +    describe.each(['disabled', 'enabled'])('%s', (state) => {
Yes, we may want to make sure that the correct style is attached even if readonly is given.

2024-07-05 08:00 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> +      <label class="${inputGroupContainer}">
It worked out that way. Thank you.
Should this also apply to the `host` portion of the component?

2024-07-05 08:06 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +      <label class="${inputGroupContainer}">
Since the `:host` can be manipulated by the user, we want to specify the size of the element here. In other words, we want to leave room for the user to change the size of the component.
Therefore, we are not considering applying `display: contents;` to the `:host`.

If the size of the component currently does not follow the size of the `:host`, please modify it.

2024-07-08 01:54 UTC, yodas7 commented
Some conversations remain unresolved, but testing readonly is easier in the new project configuration, so I'll merge develop now.

2024-07-08 01:54 UTC, yodas7 approved these changes

2024-07-08 04:36 UTC, yodas7 commented
@poetrainy 
Merged develop. Please make sure the code is OK.

2024-07-08 05:02 UTC, poetrainy commented
@yodas7 
Thank you for the merge. I have confirmed that there is no problem.

2024-07-08 05:51 UTC, yodas7 commented
LGTM, Ask others to review.

2024-07-08 22:14 UTC, hiro-daikin approved these changes

2024-07-09 05:51 UTC, yodas7 reviewed
I noticed that the layout shift occurs with or without error text.
Should we fix this?

2024-07-10 08:05 UTC, merged