fix: add attachInternals to let checkbox can be used in form
dsv-rp/DDS pull request #15
Opened 2024-07-04 02:58 UTC by rinjInTokyo

fix: add attachInternals to let checkbox can be used in form

2024-07-05 02:50 UTC, yodas7 requested changes

2024-07-05 02:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +    }
```suggestion
    this.internals.setFormValue(this.checked ? this.value : null);
```

2024-07-05 02:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +    this.dispatchEvent(newEvent);
```suggestion
    this.dispatchEvent(new Event("change", event));
```

2024-07-05 02:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +    const input = this.shadowRoot?.querySelector("input") as HTMLInputElement;
```suggestion
    const input = this.shadowRoot?.querySelector("input") as HTMLInputElement | null | undefined;
    if (!input) {
      return;
    }
```

2024-07-05 02:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +      @change=${this._handleChange}
```suggestion
      @change=${this._handleChange.bind(this)}
```

2024-07-05 02:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
>        @click=${this._handleClick}
```suggestion
      @click=${this._handleClick.bind(this)}
```

2024-07-05 02:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  static formAssociated = true;
readonly?

2024-07-05 04:53 UTC, rinjInTokyo commented on src/components/checkbox/daikin-checkbox.ts
> +    const input = this.shadowRoot?.querySelector("input") as HTMLInputElement;
`this.shadowRoot?.querySelector("input")` already return the HTMLInputElement | null | undefined type, so when i use `as HTMLInputElement | null | undefined` it will warn that "Redundant casts and non-null assertions should be avoided"
so i just delete as type and add
```
(!input) {
      return;
    }
```

2024-07-05 07:37 UTC, yodas7 requested changes

2024-07-05 07:37 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +    }
Can we use `@query` for this?
https://lit.dev/docs/components/shadow-dom/#query

2024-07-05 07:37 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  @property({ type: Object })
I don't think `internals` has to be public nor reactive.

2024-07-05 07:38 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  @property({ type: Object })
So my suggestion is to remove the decorator and make it `private _internals;`.

2024-07-05 09:00 UTC, yodas7 requested changes

2024-07-05 09:00 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  @property({ type: Object })
Seems unchanged to me.

2024-07-08 00:35 UTC, yodas7 approved these changes
LGTM. I'll do the merge of develop.

2024-07-08 00:41 UTC, KoharaKazuya commented on src/components/checkbox/daikin-checkbox.ts
> +      @change=${this._handleChange.bind(this)}
@rinjInTokyo 
I think we needs no bind. Please see <https://lit.dev/docs/components/events/#understanding-this-in-event-listeners>.

2024-07-08 01:01 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +      @change=${this._handleChange.bind(this)}
Didn't know that. I'll fix this.

2024-07-08 01:40 UTC, yodas7 commented
@rinjInTokyo @KoharaKazuya 
Merged develop. Please make sure the code is OK.

2024-07-08 02:26 UTC, KoharaKazuya commented on src/components/checkbox/daikin-checkbox.ts
> +  static readonly formAssociated = true;
@yodas7 
What means this property? Does this have functional mean in the Lit? I'm not sure. Please tell me.

2024-07-08 04:35 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  static readonly formAssociated = true;
@KoharaKazuya 
It appears to be necessary to have custom elements treated as having form data. The specification is probably in the link below.
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example

2024-07-08 05:26 UTC, KoharaKazuya commented on src/components/checkbox/daikin-checkbox.ts
> +  static readonly formAssociated = true;
@yodas7 
Thanks! I didn't know it is a web components spec.

2024-07-08 05:27 UTC, KoharaKazuya approved these changes

2024-07-08 05:54 UTC, yodas7 reviewed
I think it's almost OK. Some comments about stylistic issues added.

2024-07-08 05:54 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  }
```suggestion
  private _internals = this.attachInternals();
```

2024-07-08 05:54 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  }
Let's move this below `render()` method.

2024-07-08 07:04 UTC, yodas7 approved these changes
LGTM. Thanks.

2024-07-08 07:12 UTC, yodas7 commented
@rinjInTokyo 
As my review is finished, please ask others to review (hiro-san and shun-san).

2024-07-09 06:40 UTC, yodas7 requested changes
Commented things I missed earlier.

2024-07-09 06:40 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  _input: HTMLInputElement | null | undefined;
```suggestion
  private _input: HTMLInputElement | null | undefined;
```

2024-07-09 06:40 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +  override updated(changedProperties: Map<string, unknown>) {
```suggestion
  override updated(changedProperties: PropertyValues<this>) {
```

2024-07-09 08:08 UTC, yodas7 approved these changes
LGTM, Thanks.

2024-07-10 05:32 UTC, ukkary approved these changes

2024-07-10 08:11 UTC, merged