DDS-916 Add radio component
dsv-rp/DDS pull request #16
Opened 2024-07-05 00:04 UTC by rinjInTokyo

This PR adds Radio Button (`daikin-radio`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-1020](https://daikinsvoil.atlassian.net/jira/software/projects/DDS/boards/24/backlog?selectedIssue=DDS-916)

## API Design

- [JIRA Wiki for Tab Component] Will Add after

## How Has This Been Tested?

- VRT (Visual Regression Test) for \[small; large\] size variants and \[Normal; Hover; Pressed; Disabled\] states matrix.
- Click on the radio and it will be checked when enable
- Click on the radio and it won't be checked when disabled

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate interaction tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-07-05 02:47 UTC, yodas7 requested changes

2024-07-05 02:47 UTC, yodas7 commented on __test__/__image_snapshots__/__diff_output__/notification-test-js-notification-toast-information-multi-true-1-snap-diff.png
This should not be committed.

2024-07-05 02:47 UTC, yodas7 commented on tailwind.config.js
> +              left: -1,
body should not have `<svg>` tags, try removing them and set `width` and `height`

2024-07-05 02:47 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +        @change=${this._handleChange}
This might lose `this`.

```suggestion
        @click=${this._handleClick.bind(this)}
        @change=${this._handleChange.bind(this)}
```

2024-07-05 02:47 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +    }
Might be better to make it common whenever possible.

```suggestion
    this.internals.setFormValue(this.checked ? this.value : null);
```

2024-07-05 02:47 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +    "peer-focus-visible:after:text-daikinBlue-700",
You may want to prevent these styles from being applied when readonly or disabled.  

ref:
- https://github.com/dsv-rp/DDS/pull/8/commits/d45b97b74e62eef8a075e7c4ee427a396d62a40d#diff-06146dbd7ac082b5a41ea626af9040e51fb70e07c6f136c8a706ae30ba5724fc
- https://github.com/dsv-rp/DDS/pull/8/commits/d45b97b74e62eef8a075e7c4ee427a396d62a40d#diff-33250deecea5594f9c6d76c69e8365a63d2301799039a23e5cfcfd30ab2eebc5

2024-07-05 02:47 UTC, yodas7 commented on __test__/Radio.test.js
> +    it("click the radio and will be selected when default", async () => {
```suggestion
    it("click the radio and will be checked when default", async () => {
```

2024-07-05 02:47 UTC, yodas7 commented on __test__/Radio.test.js
> +    it("click the radio and will not be selected when disabled", async () => {
```suggestion
    it("click the radio and will not be checked when disabled", async () => {
```

2024-07-05 02:47 UTC, yodas7 commented on __test__/Radio.test.js
> +    });
You might want to test if readonly works.

2024-07-05 02:47 UTC, yodas7 commented on __test__/Radio.test.js
> +        describe.each(["enabled", "disabled"])("%s", (state) => {
It might be better to check for readonly styles.

```suggestion
        describe.each(["enabled", "disabled", "readonly"])("%s", (state) => {
```

2024-07-05 02:47 UTC, yodas7 commented on __test__/Radio.test.js
> +          it("enable", async () => {
Not consistent with disabled.

```suggestion
          it("base", async () => {
```

2024-07-05 02:47 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  peer
Can we use `appearance-none` instead?

2024-07-05 08:01 UTC, yodas7 requested changes

2024-07-05 08:01 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +    return html`<label class="inline-flex gap-[8px] items-center"
Might be better to fill parent container so that the user can extend label width

```suggestion
    return html`<label class="inline-flex w-full h-full gap-[8px] items-center"
```

2024-07-05 08:35 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  internals;
```suggestion
  // define internals to let radio can be used in form
  private _internals;
```

2024-07-05 08:35 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  static formAssociated = true;
```suggestion
  static readonly formAssociated = true;
```

2024-07-05 08:59 UTC, yodas7 approved these changes
Thanks for your effort. I'll be in charge of merging `develop` next week.

2024-07-08 01:40 UTC, yodas7 commented
@rinjInTokyo
Merged develop. Please make sure the code is OK.

2024-07-08 07:11 UTC, yodas7 requested changes
Only correction to comment. Otherwise good.

2024-07-08 07:11 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +   * Specify the label text for check box
```suggestion
   * Specify the label text for the radio
```

2024-07-08 07:11 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +   * The value.
```suggestion
   * The form value.
```

2024-07-08 07:11 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +    // Specify the component size
```suggestion
```

2024-07-08 08:02 UTC, yodas7 approved these changes
Thanks.

2024-07-08 21:51 UTC, hiro-daikin requested changes

2024-07-08 21:51 UTC, hiro-daikin commented on src/components/radio/daikin-radio.ts
> +    "disabled:after:text-daikinNeutral-200",
We should also add `daikinSerif`

2024-07-09 02:13 UTC, rinjInTokyo commented on src/components/radio/daikin-radio.ts
> +    "disabled:after:text-daikinNeutral-200",
@hiro-daikin 
thanks, I also miss it in checkbox component and fix it on other branch
[add font style to checkbox component](https://github.com/dsv-rp/DDS/pull/15/commits/ae8b92ade08eb8071b5b53a333a681806b39f0cc)

2024-07-09 20:23 UTC, hiro-daikin approved these changes

2024-07-10 05:23 UTC, ukkary commented on src/components/radio/daikin-radio.ts
> +    "enabled:after:text-[#8C8C8C]",
No design token?

2024-07-10 08:15 UTC, rinjInTokyo commented on src/components/radio/daikin-radio.ts
> +    "enabled:after:text-[#8C8C8C]",
@ukkary 
there is not design token about #8C8C8C color

2024-07-10 08:18 UTC, merged