DDS-911 Add Textarea Component
dsv-rp/DDS pull request #17
Opened 2024-07-05 07:40 UTC by poetrainy

This PR adds Text Input (`daikin-textarea`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-911](https://daikinsvoil.atlassian.net/browse/DDS-911)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/wHAhw4yC54Hjq6Whb8FL5T/DDS%3A-Design-Kit?node-id=22362-15&t=xemRTNNlKGqEqaBz-0)

## API Design

Not yet added

## How Has This Been Tested?

- VRT (Visual Regression Test) for error and required and [Normal; Hover; Pressed; Disabled] line matrix.
- When disabled, input cannot be selected.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-07-05 07:43 UTC, yodas7 commented
I think this PR is blocked by #13. Should we change this to Draft?

2024-07-05 07:51 UTC, yodas7 commented
I'd like to review this after #13 is completed.

2024-07-08 05:20 UTC, yodas7 commented
@poetrainy 
Merged the base branch. Let me know if you feel something is wrong.

2024-07-08 07:10 UTC, poetrainy commented
@yodas7 
Thank you. I have confirmed that there is no problem here either.

2024-07-08 07:20 UTC, yodas7 requested changes

2024-07-08 07:20 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +
This should be in the `slotchange` handler, not in the constructor.

2024-07-08 07:20 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  _textareas!: DaikinTextarea[];
If there is no need to distinguish between the two, then merge them into one.

```suggestion
  @queryAssignedElements({ selector: "daikin-text-input,daikin-textarea" })
  _controls!: ControlElement[];
```

where

```ts
type ControlElement = DaikinTextInput | DaikinTextarea;
```

2024-07-08 07:20 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +              >${this._textareaCounter}/100</span
I think `maxlength` should be used here instead of 100.

2024-07-08 07:20 UTC, yodas7 commented on src/components/textarea/stories/framework-wc.ts
> +    onKeyDown,
My fault; remove this

```suggestion
```

2024-07-08 07:20 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +        @input=${this._handleInput}
Don't we add `@keydown` like we do with TextInput?

2024-07-08 07:20 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +        @input=${this._handleInput}
`value` also may be missing.

2024-07-08 08:19 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> +  _textareas!: DaikinTextarea[];
@yodas7 
I completely forgot, but the following line could be used in the logic for displaying the counter (which I moved to `_handleSlotChange`).

I fixed the line that used `getElementByTagName`, leaving the following description. Is this incorrect?

````
@queryAssignedElements({ selector: "daikin-textarea" }
````

2024-07-08 08:21 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  _textareas!: DaikinTextarea[];
I think that's correct.
In that case, it is a good idea to have both `_controls` and `_textareas`.

2024-07-08 08:26 UTC, poetrainy commented on src/components/textarea/daikin-textarea.ts
> +        @input=${this._handleInput}
@yodas7 
Added `@keydown`.

I don't seem to have `value` in textarea, am I correct? Is this topic different from that?

2024-07-09 01:25 UTC, yodas7 requested changes
Sorry, I lost VRTs in the merge process. Please add it.

2024-07-09 01:25 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +        maxlength=${this.maxlength}
If maxlength is specified for the teaxtarea, the text will be truncated, so the counter should never exceed maxlength. Therefore, it is questionable that maxlength should be the same value for the counter and this one.

2024-07-09 01:25 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +        @input=${this._handleInput}
I missed the `value` field in the component.
Just add `.value=${value}`.

2024-07-09 01:25 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +  @property({ type: Boolean })
reflect?

2024-07-09 01:25 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +  @property({ type: Boolean })
reflect?

2024-07-09 01:25 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +  @property({ type: Number })
reflect?

2024-07-09 01:25 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +  @property({ type: String })
reflect?

2024-07-09 01:33 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +    this._textareaCounter = this.value.length;
`.length` might not be suitable for counting length.
See https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/length#%E8%A7%A3%E8%AA%AC

2024-07-09 01:34 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +    this._internals.setFormValue(this.value);
We should update `_textareaCounter` as well.
Let's extract L140 and L141 to a separate private method.

2024-07-09 01:38 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    }
```suggestion
    for (const item of this._textareas) {
      item.counter = true;
    }
```

2024-07-09 05:48 UTC, yodas7 requested changes

2024-07-09 05:48 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +  private _updateTextareaCounter(value: string): void {
```suggestion
  private _updateValueAndCounter(value: string): void {
```

2024-07-09 05:48 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +    this._internals.setFormValue(this.value);
We don't need `this._internals.setFormValue(this.value);` anymore

2024-07-09 05:48 UTC, yodas7 commented on src/components/input-group/stories/framework-react.tsx
> +      {content === "Textarea" && <ReactDaikinTextarea />}
Let's set value as we do in `TextInput` to test if `value` attribute works.

```suggestion
      {content === "Textarea" && <ReactDaikinTextarea value="Value" />}
```

2024-07-09 06:34 UTC, yodas7 requested changes

2024-07-09 06:34 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +  private _textareaCounter: number = 0;
This should be an [internal reactive state](https://lit.dev/docs/components/properties/#internal-reactive-state) ad it's used in the render method.

2024-07-11 09:28 UTC, yodas7 approved these changes
LGTM, Thanks.

2024-07-12 19:14 UTC, hiro-daikin approved these changes

2024-07-16 08:13 UTC, merged