DDS-1046 DDS-1137 Add Icon Component
dsv-rp/DDS pull request #18
Opened 2024-07-10 05:50 UTC by poetrainy

This PR adds Icon (`daikin-icon`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent):
  - [DDS-1046](https://daikinsvoil.atlassian.net/browse/DDS-1046)
  - In progress: [DDS-1137](https://daikinsvoil.atlassian.net/browse/DDS-1137)
    - As soon as this is completed, this branch will be undrafted.
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/wHAhw4yC54Hjq6Whb8FL5T/DDS%3A-Design-Kit?node-id=0-1526&t=UvT0DNR0CFs6u9P5-0)

## API Design

Not yet added

## How Has This Been Tested?

- VRT (Visual Regression Test) for [S; M; L; XL] size and [black; white; colored] color matrix.
- VRT for Notification component (refactored to replace Icon)
  - Test passed without problems and no snapshot updates were made

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-07-10 05:50 UTC, poetrainy commented
Still in progress regarding DDS-1137. As soon as this is completed, this branch will be undrafted.

2024-07-10 07:06 UTC, poetrainy commented
The functionality of the icon component is complete.
However, DDS-1137 is still in progress as there are things to check.
As soon as this is completed, this branch will be out of draft.

2024-07-11 03:19 UTC, poetrainy commented
DDS-1137 implementation was completed, so this pull request was undrafted.

2024-07-11 03:20 UTC, poetrainy commented
DDS-1137 implementation was completed, so this pull request was undrafted.

2024-07-11 08:58 UTC, yodas7 requested changes

2024-07-11 08:58 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +              size="${BUTTON_ICON_SIZE_MAP[this.size]}"
```suggestion
              icon=${this.leftIcon}
              size=${BUTTON_ICON_SIZE_MAP[this.size]}
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +      ${this.leftIcon.length
```suggestion
      ${this.leftIcon
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +      ${this.rightIcon.length
```suggestion
      ${this.rightIcon
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +              size="${BUTTON_ICON_SIZE_MAP[this.size]}"
```suggestion
              icon=${this.rightIcon}
              size=${BUTTON_ICON_SIZE_MAP[this.size]}
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/button/stories/common.ts
> +      "Specify the left icon to be inserted in the icon. See `Icon` for available icons.",
```suggestion
      "Specify the left icon to be inserted in the icon. See `daikin-icon` component for available icons.",
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/button/stories/common.ts
> +      "Specify the left right to be inserted in the icon. See `Icon` for available icons.",
```suggestion
      "Specify the left right to be inserted in the icon. See `daikin-icon` component for available icons.",
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +      original: [],
```suggestion
      current: [], // uses `currentColor`
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +  },
```suggestion
```

2024-07-11 08:58 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +      display: block;
```suggestion
      --size-xl: ${unsafeCSS(space24)};

      display: block;
```

2024-07-11 09:00 UTC, yodas7 commented
Since the icons are managed in files, it might be better to devise a way to allow the files to have color and alias information.
Alternatively, a JSON file of the icon index could be prepared.

2024-07-11 09:00 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +  icon = "";
Might be better if it's typed.

2024-07-12 02:31 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +  icon = "";
I mean `IconType`

2024-07-12 02:32 UTC, yodas7 requested changes
I mean `IconType`, not just `string` for `icon` prop.

2024-07-12 04:00 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +  icon = "";
@yodas7 
In this case, what would be the initial value? Or is it a form that allows `undefined`?

2024-07-12 06:09 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +  icon = "";
@poetrainy 
I think it would be `IconType | null`, given that native attributes such as `role` has `string | null` type.

2024-07-16 02:02 UTC, yodas7 requested changes

2024-07-16 02:59 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +  warning: "#000000",
It was summarized in Figma
https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/DDS%3A-Design-Kit?node-id=9701-14962&t=Naq3PE8wJHDyyPvQ-0

2024-07-16 05:45 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +  warning: "#000000",
Got it.
There seems to be no default color (a color not related to the theme) for these icons.
`null` may be preferable.

2024-07-16 05:48 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +  warning: "#000000",
Maybe we should manage them as JSON.

```json
{
  "icons": {
    "alarm": {
      "class": "i-daikin-notification-status-alarm"
      "color": null,
    },
    ...
  }
}
```

2024-07-17 06:31 UTC, yodas7 requested changes

2024-07-17 06:31 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +    const defaultColor = this.icon ? icons[this.icon].color : null;
We may want to warn user if user is trying to use uncolored icon as colored icon

```suggestion
    const defaultColor = this.icon ? icons[this.icon].color : null;

    if (import.meta.env.DEV) {
      if (!(this.icon in icons)) {
        console.warn(`There is no icon named ${this.icon}.`);
      } else if (this.color === "colored" && !defaultColor) {
        console.warn(`The icon ${this.icon} does not have a default color.`);
      }
    }
```

2024-07-17 06:31 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +      colored: ["text-[--default-color]"],
Might be good to use "default", "intrinsic", or something else?

2024-07-18 01:46 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +      colored: ["text-[--default-color]"],
I'm sorry, but I can't quite understand the intention of this comment. Should I change it to “intrinsic”?

2024-07-22 07:08 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +      colored: ["text-[--default-color]"],
I just thought the way of writing `color=“colored”` was a little weird.
Any word that conveys the meaning of color will do.

2024-07-22 09:02 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +      colored: ["text-[--default-color]"],
@yodas7 
The CSS variable name is `--default-color`, so I changed the name to `default`.

2024-07-23 03:14 UTC, yodas7 requested changes

2024-07-23 03:14 UTC, yodas7 commented on src/components/icon/daikin-icon.ts
> +      if (!(this.icon in icons)) {
```suggestion
      if (!this.icon) {
        console.warn("icon property is not specified");
      } else if (!(this.icon in icons)) {
```

2024-07-23 03:14 UTC, yodas7 commented on src/components/button/stories/common.ts
> +      "Specify the left icon to be inserted in the icon. See `daikin-icon` component for available icons.",
```suggestion
      "Specify the left icon to be inserted. See `daikin-icon` component for available icons.",
```

2024-07-23 03:14 UTC, yodas7 commented on src/components/button/stories/common.ts
> +      "Specify the left right to be inserted in the icon. See `daikin-icon` component for available icons.",
```suggestion
      "Specify the right icon to be inserted. See `daikin-icon` component for available icons.",
```

2024-07-23 06:21 UTC, yodas7 approved these changes
LGTM. Thanks.

2024-07-23 06:25 UTC, poetrainy commented
Thank you very much. It was also a learning experience for me.

2024-07-24 00:12 UTC, hiro-daikin commented on src/components/icon/daikin-icon.ts
> +    }
If the user asks for an icon that doesn't exist, will this still work?

2024-07-24 00:12 UTC, hiro-daikin commented on src/components/icon/daikin-icon.ts
> +      current: [], // uses `currentColor`
We will also need a daikin blue icon.

2024-07-24 01:53 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +      current: [], // uses `currentColor`
@hiro-daikin 
How often is daikin blue used as an icon color?
The `currentColor` currently implemented allows you to assign the text color of the parent element to the icon color. If you specify it appropriately here, it is possible to use daikin blue even with the current implementation.

2024-07-24 01:56 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +    }
@hiro-daikin 
In that case, the console.warn on line 88 will be displayed.
Please check the new commit as we have modified some of the code for this implementation.

2024-07-24 21:28 UTC, hiro-daikin commented on src/components/icon/daikin-icon.ts
> +      current: [], // uses `currentColor`
@poetrainy It should be used quite often. 
However, if we can specify using `currentColor`, I think that would be okay too. 

I would assume these cases would also be documented? 
Since this is one major use case, it might be good to also add a visual regression test.

2024-07-24 21:40 UTC, hiro-daikin commented on src/components/icon/daikin-icon.ts
> +    }
I see that logic.
What I would like to know is what gets rendered. 

For example, shoelace keeps the width, but just shows nothing. 
You can play around the `codepen` examples here: https://shoelace.style/components/icon

2024-07-25 02:46 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +    }
@hiro-daikin 
Thank you for the example.
As with shoelace, the area where the icon should be inserted is reserved, but nothing is displayed.

2024-07-25 02:47 UTC, poetrainy commented on src/components/icon/daikin-icon.ts
> +      current: [], // uses `currentColor`
@hiro-daikin 
I've added an announcement about changing colors using `current` in documents and a visual regression test.

2024-07-26 00:27 UTC, hiro-daikin approved these changes

2024-07-26 08:07 UTC, merged