DDS-904 add button component
dsv-rp/DDS pull request #2
Opened 2024-06-21 06:35 UTC by rinjInTokyo

This PR adds Button (`daikin-button`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-904](https://daikinsvoil.atlassian.net/jira/software/projects/DDS/boards/24/backlog?selectedIssue=DDS-904)
- Figma design: [Figma]

## API Design

[JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3019341872/Button+Component+API)

## How Has This Been Tested?

- VRT (Visual Regression Test) for \[Primary; Primary Danger; Secondary; Tertially\] variants and \[Normal; Hover; Pressed; Disabled\] states matrix.
- confirm that there is no attribute `disabled` when default
- confirm that there is attribute `disabled` when disabled

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-06-24 05:40 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +        }
```suggestion
        const SIZE_CLASS_MAP = {
          default: buttonSizeDefault,
          condensed: buttonSizeCondensed;
        };
        
        CN += SIZE_CLASS_MAP[this.size] ?? SIZE_CLASS_MAP.default
```

2024-06-24 06:18 UTC, KoharaKazuya requested changes

2024-06-24 06:18 UTC, KoharaKazuya commented on __test__/Button.test.js
> +                // we have to focus on the internal button element
@rinjInTokyo 
I was able to have focus on daikin-button in storybook. Do you have any special problem of jest?

2024-06-24 06:18 UTC, KoharaKazuya commented on jest-puppeteer.config.js
@rinjInTokyo 
Could you please add a comment about the reason for this configuration?

2024-06-24 06:18 UTC, KoharaKazuya commented on src/components/button/react-jsx.d.ts
@rinjInTokyo 
I don't know what this is for. Cloud you please tell me?

2024-06-24 06:18 UTC, KoharaKazuya commented on src/components/button/stories/daikin-button-react.stories.tsx
> +            type={type ?? "button"}
@rinjInTokyo 
Maybe you shouldn't add a default value. I think the empty value tests are needed.

2024-06-24 06:58 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +        }
```ts
const CN = [
  button,
  VARIANT_CLASS_MAP[this.variant] ?? VARIANT_CLASS_MAP.primary,
  SIZE_CLASS_MAP[this.size] ?? SIZE_CLASS_MAP.default
].join(" ");
```

2024-06-24 07:04 UTC, yodas7 commented on __test__/__image_snapshots__/button-test-js-button-primary-danger-default-focus-1-snap.png
The focus ring exists for accessibility.
After modifying as per Figma, feedback to the design team may be needed.

2024-06-24 07:30 UTC, rinjInTokyo commented on __test__/Button.test.js
> +                // we have to focus on the internal button element
@KoharaKazuya 
It seems that daikin-button is not a input element (like a wrap?) so it can not be focused,  i have to  get the button element from the shadow root and focus it.
<img width="1627" alt="image" src="https://github.com/dsv-rp/DDS/assets/106000401/2c99693c-1d48-4b5b-871a-30b8bf53962e">

<img width="1632" alt="image" src="https://github.com/dsv-rp/DDS/assets/106000401/b9603f13-eba5-44ce-a75c-ae6b1e8a58a9">

2024-06-24 08:11 UTC, rinjInTokyo commented on __test__/setupTests.js
> +    blur: 0
when test be ran in Github it will always error so we try to change the properties to fix it but it's not work.
this change is just show that we has tried that way and hope this line will help somebody

2024-06-24 08:16 UTC, rinjInTokyo commented on src/components/button/react-jsx.d.ts
@KoharaKazuya 
Submitted this file accidentally and i will delete it

2024-06-24 08:26 UTC, rinjInTokyo commented on jest-puppeteer.config.js
@KoharaKazuya 
we use chrome environment to test so this config is to improve rendering performance

2024-06-24 08:30 UTC, KoharaKazuya commented on __test__/__image_snapshots__/button-test-js-button-primary-danger-default-focus-1-snap.png
Yes, I think so too. What should we do? Currently, the implementation is not as shown in Figma.

2024-06-25 00:52 UTC, KoharaKazuya commented on jest-puppeteer.config.js
@rinjInTokyo 
Thanks. We would like to pass this on to future developers. Could you please add a comment in the code?

2024-06-25 00:56 UTC, KoharaKazuya commented on __test__/setupTests.js
> +    blur: 0
@rinjInTokyo 
If we must tell developer this should not be changed, please comment it in the code.

2024-06-25 01:25 UTC, KoharaKazuya commented on __test__/Button.test.js
> +                // we have to focus on the internal button element
@rinjInTokyo 
I got it. I think we should make `daikin-button` focus-able. Can you try to override focus method?

```typescript
class DaikinButton {
  override focus() {
    innerButtonElement.focus();
  }
}
```

2024-06-25 01:52 UTC, rinjInTokyo commented on __test__/__image_snapshots__/button-test-js-button-primary-danger-default-focus-1-snap.png
designer hope we can turn off the ring

2024-06-25 02:43 UTC, hiro-daikin requested changes

2024-06-25 02:43 UTC, hiro-daikin commented on src/components/button/daikin-button.ts
> +          ].join(" ");
I've since encountered the `class variance authority` library. 
It might help us organize this better: https://stevekinney.net/courses/storybook/adding-a-size-variant

2024-06-25 02:43 UTC, hiro-daikin commented on src/components/button/daikin-button.ts
> +    text-[14px]
These pixel definitions, I wonder if it's normal to have these hardcoded like this, instead of deriving it from tokens. 

It might be worthwhile to see what the industry standard is in terms of what is tokenized vs what is not

2024-06-25 02:43 UTC, hiro-daikin commented on __test__/setupTests.js
> +        height: 600,
I think Mike was working on what the expected viewport size is. Just an FYI. We can change this later.

2024-06-25 02:43 UTC, hiro-daikin commented on __test__/Button.test.js
> +    describe("interaction test", () => {
For interaction tests, I was thinking we would need to write additional code to make sure that the functionality works as intended.

For example, for disabled state, we can add a `onClick` handler, and if the button is disabled, the action should not get triggered

2024-06-25 03:09 UTC, rinjInTokyo commented on __test__/Button.test.js
> +    describe("interaction test", () => {
@hiro-daikin cc @ukkary 
yes, I have tried to inject spy to daikin-button to detect has click event been triggered once or not, but i met some problem because the project structure. devs will consider about that. 
and if it will cost too much time to solve this problem maybe we can add test case after?

2024-06-25 03:21 UTC, ukkary commented on src/components/button/daikin-button.ts
> +const VARIANT_CLASS_MAP = {
@KoharaKazuya Considering whole structure, don't we need to freeze Object to not override each object value?

example
```
const VARIANT_CLASS_MAP = object.freeze({
    primary: 'button-primary',
    secondary: buttonSecondary,
    tertiary: buttonTertiary,
    primaryDanger: buttonPrimaryDanger,
  } as const);
```

2024-06-25 03:30 UTC, yodas7 commented on __test__/Button.test.js
> +    describe("interaction test", () => {
That test case is intentionally excluded at this time.
We initially attempted to test this case using Storybook's interaction tests, but due to a lack of reproducibility in Storybook's test environment, the click event was fired even when disabled (even though it did not actually happen in the browser). (even though it does not actually happen in the browser).
Testing with Puppeteer may solve the problem, but in that case, we need to prepare a process to provide feedback on the page in response to the click event.
Currently, only Storybook is available from Puppeteer, and we had to decide where to place the pages for interaction testing, but since we did not know how to properly place them, we gave up for now.

2024-06-25 03:32 UTC, yodas7 commented on __test__/Button.test.js
> +    describe("interaction test", () => {
FYI after the migration to Vitest:
Since Vite is available for Vitest browser testing, it may be suitable for this type of interaction testing.

2024-06-25 04:54 UTC, KoharaKazuya commented on src/components/button/daikin-button.ts
> +const VARIANT_CLASS_MAP = {
@ukkary 
It seems to be good! However, we need to freeze almost all objects. I don't think it's necessary to freeze because the problems that can be prevented are small considering how hard it is.

2024-06-25 04:58 UTC, yodas7 requested changes

2024-06-25 04:58 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +    min-w-[88px]
Are these correct?
You need to check what the recommended maximum and minimum widths for your design mean.
These may not be something that should be specified as a component, but something that users of the component should be aware of.

2024-06-25 04:58 UTC, yodas7 commented on src/components/button/daikin-button.ts
>      static styles = css`
To give the component flexibility, we want the size of the element to be defined by the shadow host.
That is, the inner element (in this case the `<button>` element) will have the same size as its parent container (the shadow host, in this case the `<daikin-button>` element), with default width and height specified in `<daikin-button>`.

To do so, add

```css
:host {
  width: fit-content;
  min-height: 42px;
}

:host([variant="condensed"]) {
  min-height: 32px;
}
```

to host styles.

Then remove all `w-*`, `min-h-*`, `min-w-*`, `max-w-*` from button classes.

2024-06-25 07:39 UTC, yodas7 commented on src/components/button/daikin-button.ts
> +    text-[14px]
We are currently examining efficient ways to import design tokens. (We are considering creating a Vite plugin that allows to import tokens of a given hierarchy as CSS code with CSS custom property definitions.)
This will take time, so I suggest that we proceed with hard-coding this at this stage, and then change it after implementation of this & consideration of how much we want to design tokens.

2024-06-25 08:15 UTC, KoharaKazuya commented on __test__/setupTests.js
> +    blur: 0
Thank you for your comment.

2024-06-25 08:26 UTC, KoharaKazuya commented on __test__/__image_snapshots__/button-test-js-button-primary-danger-default-focus-1-snap.png
'danger' button has blue ring yet.

2024-06-25 09:22 UTC, KoharaKazuya commented on jest-puppeteer.config.js
> +// Ddd this code to improve chrome browser rendering performance when test
@rinjInTokyo 
typo?

```suggestion
// Add this code to improve chrome browser rendering performance when test
```

2024-06-25 23:54 UTC, rinjInTokyo commented on jest-puppeteer.config.js
> +// Ddd this code to improve chrome browser rendering performance when test
Sorry, it's a typo

2024-06-26 01:09 UTC, KoharaKazuya commented on src/components/button/daikin-button.ts
> +          // primary: "bg-blue-500 text-white border-transparent hover:bg-blue-600",
@rinjInTokyo 
What purpose for these lines? I overlooked these in the previous review. :/

2024-06-26 01:44 UTC, rinjInTokyo commented on src/components/button/daikin-button.ts
> +          // primary: "bg-blue-500 text-white border-transparent hover:bg-blue-600",
@KoharaKazuya 
I use class-variance-authority to create classname base on hiro's suggestion and this comment is to show that not only classname array but also classname string containing spaces

2024-06-26 02:15 UTC, KoharaKazuya commented on src/components/button/daikin-button.ts
> +          // primary: "bg-blue-500 text-white border-transparent hover:bg-blue-600",
@rinjInTokyo 
Only for discussion? I think the code not for the future developers should be removed or the comment should be added for the developers.

2024-06-26 02:20 UTC, rinjInTokyo commented on src/components/button/daikin-button.ts
> +          // primary: "bg-blue-500 text-white border-transparent hover:bg-blue-600",
@KoharaKazuya 
I will remove it

2024-06-26 03:48 UTC, hiro-daikin commented on src/components/button/daikin-button.ts
> +    text-[14px]
I've come across this [plugin](https://www.figma.com/community/plugin/1261234393153346915/variables2css) which converts variables in Figma into CSS. Might be worth taking a look. 

But my question is - we only have design tokens for color, fonts, and maybe a few others. Do we need token studio to output sizing as well? 

Spectrum seems to have sizing tokens: https://spectrum.adobe.com/page/design-tokens/

2024-06-26 04:04 UTC, hiro-daikin commented on __test__/Button.test.js
> +    describe("interaction test", () => {
@yodas7 @rinjInTokyo 
I'm okay with adding another ticket for this. 

There's also storybook play function: https://storybook.js.org/docs/writing-stories/play-function#writing-stories-with-the-play-function

The advantage is we can co-locate tests, and very little setup is required - for future consideration.

2024-06-26 04:11 UTC, hiro-daikin commented on src/components/button/daikin-button.ts
> +import { cva } from "class-variance-authority";
We can also extract types using [Variant Types](https://cva.style/docs/getting-started/typescript)

This may help speed up development and reduce bugs

2024-06-26 06:43 UTC, hiro-daikin approved these changes

2024-06-26 06:59 UTC, yodas7 approved these changes

2024-06-26 08:11 UTC, KoharaKazuya requested changes

2024-06-26 08:11 UTC, KoharaKazuya commented on __test__/__image_snapshots__/button-test-js-button-tertiary-default-focus-1-snap.png
@rinjInTokyo 
There is no difference in appearance from `__test__/__image_snapshots__/button-test-js-button-tertiary-default-base-1-snap.png`. We should consider a11y.

2024-06-26 08:38 UTC, rinjInTokyo commented on __test__/__image_snapshots__/button-test-js-button-tertiary-default-focus-1-snap.png
@KoharaKazuya 
According to meeting's conclusion I add the outline when focus in tertiary button

2024-06-27 01:17 UTC, yodas7 approved these changes
LGTM

2024-06-27 01:18 UTC, merged