DDS-1022 Add Accordion Component
dsv-rp/DDS pull request #20
Opened 2024-07-11 07:51 UTC by poetrainy

This PR adds Accordion (`daikin-accordion`, `daikin-accordion-group`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent):
  - [DDS-1022](https://daikinsvoil.atlassian.net/browse/DDS-1022)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/wHAhw4yC54Hjq6Whb8FL5T/DDS%3A-Design-Kit?node-id=24068-567&t=Rc1MdyRJ84YL1anu-0)

## API Design

Not yet added

## How Has This Been Tested?

- VRT (Visual Regression Test) for [open; close] and [enabled; disabled] matrix.
- Click on the summary to view the contents. Also, when the contents are displayed, they will be hidden.
- When disabled, input cannot be selected.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-07-11 08:25 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      disabled: {
status might be better.

```suggestion
      status: {
```

2024-07-11 08:31 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +    },
```suggestion
```

2024-07-11 08:31 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      disabled: {
```suggestion
      status: {
```

2024-07-11 08:32 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      max-width: 400px;
Is it okay to set max-width by the library?

2024-07-11 08:33 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      --accordion-summary-chevron-rotate: 0;
It looks unused to me.

```suggestion
```

2024-07-11 08:33 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +  private _visibleContents(e: PointerEvent) {
```suggestion
  private _handleSummaryClick(e: PointerEvent) {
```

2024-07-11 08:34 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +    const content = (e.target as HTMLElement).nextElementSibling as HTMLElement;
Maybe we can use [ref](https://lit.dev/docs/templates/directives/#ref) to reference DOM element.

2024-07-11 08:36 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      };
We may want to leave a comment as to why we need to delay setting open.

2024-07-11 08:42 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +    if (this.dataOpen) {
It might be good to note what we are doing (opening or closing) in this if clause.

```
// Accordion is opened; close it.
```

2024-07-11 08:45 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +        <div class=${accordionContentClassName}>
One of the advantages of using TailwindCSS is separation of concerns.
The closer the element and style are described, the easier it is to see what the element will look like.

```suggestion
        <div class="pt-2 pb-[24px] px-[20px] text-sm">
```

2024-07-11 08:49 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +  dataOpen = false;
It may be better to replace `dataOpen` with `open` and existing `open` with `detailsOpen`, since `dataOpen` is more correct as an open/close state and details' `open` is in a delayed form.

2024-07-11 08:51 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +];
```suggestion
const getContentOpenKeyframe = (content: HTMLElement) => ({
  height: `${content.offsetHeight}px`,
});
```

2024-07-11 08:51 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +const contentDefault = {
```suggestion
const contentCloseKeyframe = {
```

2024-07-11 08:51 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +const animationOptionBase = {
```suggestion
const animationOption = {
```

2024-07-12 00:35 UTC, poetrainy commented on src/components/accordion/daikin-accordion.ts
> +      max-width: 400px;
The following description was found in Figma.

```
Accodionのデフォルトサイズは400px  x 48px、 ただし横サイズはディスプレイサイズに合わせて調節可能
並びときにAccodion上下の横線に合わせ並びこと。
```

2024-07-12 00:37 UTC, poetrainy commented on src/components/accordion/daikin-accordion.ts
> +  dataOpen = false;
The values of the properties that `daikin-accordion-items` has change, is it still ok?

2024-07-12 02:41 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      max-width: 400px;
Sounds good then.

2024-07-12 02:50 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +  dataOpen = false;
I think it's ok. Could you try it?

2024-07-12 02:51 UTC, yodas7 requested changes
Please try switching open and dataOpen.

2024-07-12 04:22 UTC, poetrainy commented on src/components/accordion/daikin-accordion.ts
> +  dataOpen = false;
I understand. I have corrected it as such.

2024-07-16 01:58 UTC, yodas7 requested changes
Some suggestions about TailwindCSS

2024-07-16 01:58 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +        <div class="pt-2 pb-[24px] px-[20px] text-sm">
```suggestion
        <div class="pt-2 pb-6 px-5 text-sm">
```

2024-07-16 01:58 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    "[&>summary:after]:[&[data-open]]:rotate-180",
Styling children is not a good idea.
We should move this to summary itself.

We may want to:

- Add `&[aria-disabled='false']` to our plugin (e.g. as `aria-enabled`)
- Add "group" class to the `details` element
- Use `group-aria-enabled:hover:bg-[#DCDCDC]` in summary
- Use `group-[[data-open]]:after:rotate-180`

See [this page](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state) for `group` usage

2024-07-16 01:58 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +    ::slotted(daikin-accordion-item:not(:last-child)) {
```suggestion
    }

    ::slotted(daikin-accordion-item:not(:last-child)) {
```

2024-07-16 01:58 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    "px-[20px]",
```suggestion
    "px-5",
```

2024-07-16 04:33 UTC, poetrainy commented on src/components/accordion-item/daikin-accordion-item.ts
> +    "[&>summary:after]:[&[data-open]]:rotate-180",
@yodas7 
Thank you very much, I will try to get it to work.
Using `group` to apply the aria-disabled style did not work, so I unified it with cva like the rest of the site. Would this be different from your intention?

2024-07-16 05:40 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    "[&>summary:after]:[&[data-open]]:rotate-180",
That's okay, thanks.

2024-07-16 05:41 UTC, yodas7 reviewed
CI failing; please check.

2024-07-17 02:11 UTC, poetrainy commented
@yodas7 
The error has been corrected. I apologize for the inconvenience, but would you please check again?

2024-07-17 05:18 UTC, yodas7 commented
There's no need to be so formal. I'll check.

2024-07-17 06:21 UTC, yodas7 requested changes
It might be good to add interaction test for keyboards (for both enabled and disabled)

2024-07-23 03:03 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +        tabindex=${!this.disabled ? 0 : -1}
I mean placing `@click` below `tabindex`.

```suggestion
        tabindex=${this.disabled ? -1 : 0}
        @click=${this._handleSummaryClick}
```

2024-07-23 06:52 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      max-width: 400px;
@poetrainy 
I'm still a little worried about it, so could you ask the designer to check it?
I think 400px is a little small for a content area.

2024-07-23 06:52 UTC, yodas7 commented
@poetrainy 
https://github.com/dsv-rp/DDS/pull/20#discussion_r1687518918

2024-07-25 02:59 UTC, yodas7 requested changes

2024-07-25 02:59 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    }
```suggestion
    const sync = () => {
      this._detailsOpen = this.open;
    };

    if (this.open) {
      sync();
    } else {
      setTimeout(sync, 250);
    }
```

2024-07-25 02:59 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    }
Maybe we should move animation from `_handleSummaryClick` to here so that animation works when setting `open` programatically.

2024-07-25 03:27 UTC, poetrainy commented on src/components/accordion-item/daikin-accordion-item.ts
> +    }
@yodas7 
I tried this method, but it didn't work because the updated() animation fires even when `open = true` is already set in firstUpdated.

2024-07-25 06:31 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    }
@poetrainy 
Maybe we should check `this.open !== this._detailsOpen` before starting animation.

2024-07-25 07:12 UTC, poetrainy commented on src/components/accordion-item/daikin-accordion-item.ts
> +    }
@yodas7 
I was able to clear it that way. Thank you.

2024-07-25 07:22 UTC, yodas7 requested changes

2024-07-25 07:22 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    this._contentAnimate();
We should check if changed properties include "open" or not to improve performance.

2024-07-26 01:29 UTC, hiro-daikin approved these changes

2024-07-26 08:15 UTC, merged