Fix react interaction test not working at all
dsv-rp/DDS pull request #23
Opened 2024-07-12 08:40 UTC by yodas7

There was a typo in `test:interaction-react` command.

2024-07-12 09:26 UTC, KoharaKazuya approved these changes

2024-07-16 02:38 UTC, ukkary requested changes

2024-07-16 02:40 UTC, ukkary commented on src/storybook/type-utils.ts
> +type Uppercase =
Could shorten more.
```
type EventListenerKeys<K> = K extends `on${Capitalize<string>}` ? K : never;
```

2024-07-16 05:31 UTC, yodas7 commented on src/storybook/type-utils.ts
> +type Uppercase =
That's a very smart idea! I've made the change.

2024-07-16 06:08 UTC, ukkary approved these changes

2024-07-16 06:26 UTC, merged