DDS-908 Add breadcrumb component
dsv-rp/DDS pull request #24
Opened 2024-07-16 03:21 UTC by rinjInTokyo

This PR adds breadcrumb and breadcrumb-item (`daikin-breadcrumb`, `daikin-breadcrumb-item`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-908](https://daikinsvoil.atlassian.net/browse/DDS-908)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/wHAhw4yC54Hjq6Whb8FL5T/DDS%3A-Design-Kit?node-id=23120-920&m=dev)

## API Design

[JIRA Wiki]Will add after

## How Has This Been Tested?

- breadcrumb
  - VRT (Visual Regression Test) for \[withTrailingSlash; withoutTrailingSlash\] trailingSlash style and \[withOmission; withoutOmission\] omission style.
  - If omission is true and the breadcrumb will be omitted when wrap container becomes smaller
- breadcrumb-item
  - VRT (Visual Regression Test) for \[max; min\] variants and \[Normal; Hover; Pressed; Disabled\]  state

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-07-24 22:13 UTC, hiro-daikin approved these changes
Looks good for now. 

One thing we may want to consider is adding an ellipsis at the end of each item. For example, `Home -> Item 1 -> Really long str....`

2024-07-25 02:47 UTC, yodas7 requested changes
I'm a little worried about whether the current mechanism for omitting content is sufficient (such as recalculating content size when slot content changes, or how to display the menu for omitted items).
However, I don't have a good solution, so I think it's fine to leave it as it is until the menu is implemented.

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +        : html`<span>. . .</span>`;
Depending on our needs, we need to change the code depending on what we want the "text on the display", the "text to be selected (copied)", and the "text to be read by the screen reader" to be.
At least for screen readers, "…" or "..." should be better than ". . .", so `aria-label` should be specified.

```suggestion
        : html`<span aria-label="…">. . .</span>`;
```

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +      >
nit.

```suggestion
      <slot name="link">
        <a
          href=${ifDefined(this.href)}
          class=${linkClassName}
          target=${this.target}
        >${linkText}</a>
        ${slash}
      </slot>
```

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +  target: "_blank" | "_self" | "_parent" | "_top" | "framename" = "_self";
`target` actually accepts any string, as "framename" is not just "framename" but is a frame's name.

```suggestion
  target: string | null = null;
```

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.ts
> +    }
```suggestion
    const shouldOmit = this.overflow === "ellipsis" && this.offsetWidth < this._expandedContentWidth;
    if (this.omitted === shouldOmit) {
      return;
    }
    this.omitted = shoudOmit;
    
    const daikinBreadCrumbItems = this._slottedDaikinBreadCrumbItems;
    for (const [index, item] of daikinBreadCrumbItems.entries()) {
      const mode = shouldOmit ? (index === 0 || index >= daikinBreadCrumbItems.length - 2 ? "visible" : index === 1 ? "ellipsis" : "hidden") : "visible";
      item.hidden = mode === "hidden";
      item.variant = mode === "ellipsis" ? "ellipsis" : "normal";
    }
```

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.ts
> +  }
```suggestion
  private _updateBreadcrumbs() {
    const daikinBreadCrumbItems = this._slottedDaikinBreadCrumbItems;
    for (const [index, item] of daikinBreadCrumbItems.entries()) {
      if (index === daikinBreadCrumbItems.length - 1) {
        // last item
        item.trailingSlash = this.trailingSlash;
        item.disabled = true;
        continue;
      }
      
      item.trailingSlash = true;
    }
  }
```

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.ts
> +  _omit() {
```suggestion
  private _omit() {
```

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.ts
> +  private _divWrap: HTMLElement | null | undefined;
We should use ref.

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.ts
> +  }
we should use queryAssignedElements

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.visual.test.ts
> +      console.log(baseURL);
```suggestion
```

2024-07-25 02:47 UTC, yodas7 commented on src/components/breadcrumb/stories/framework-react.tsx
> +        DaikinBreadcrumbItem1
```suggestion
        Breadcrumb Item 1
```

2024-07-25 09:24 UTC, yodas7 commented on cspell-dictionary.txt
> +framename
bump

2024-07-26 00:26 UTC, rinjInTokyo commented on cspell-dictionary.txt
> +framename
@yodas7 
removed it

2024-08-02 06:47 UTC, yodas7 requested changes
I also wanted to test the use of `link` slots.

2024-08-06 03:12 UTC, yodas7 commented
@rinjInTokyo 
Forgot to mention Changesets; please add a changeset.
e.g. `Add Breadcrumbs Component.`

2024-08-06 03:25 UTC, yodas7 requested changes

2024-08-06 03:25 UTC, yodas7 commented on tailwind.config.cjs
> +      ]);
Good catch. To make it more versatile, we can use the following method:

```suggestion
      matchVariant("slotted", (value) => [`&::slotted(${value})`, `&>${value}`]);
```

with `slotted-[*:focus-visible]:text-daikinBlue-700`.

2024-08-06 07:13 UTC, yodas7 approved these changes
LGTM

2024-08-21 05:46 UTC, merged