DDS-1026 Add Dropdown Component
dsv-rp/DDS pull request #25
Opened 2024-07-16 07:37 UTC by poetrainy

This PR adds Dropdown (`daikin-dropdown`, `daikin-dropdown-item`) component.

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1026](https://daikinsvoil.atlassian.net/browse/DDS-1026)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/wHAhw4yC54Hjq6Whb8FL5T/DDS%3A-Design-Kit?node-id=3437-3108&t=hlFRlGCI214ER8BR-0)

## API Design

Not yet added

## How Has This Been Tested?

### Visual Regression Tests

- \[Small; Medium\] sizes and \[Top; Left; None\] Label position and \[Exist; None\] left icon and \[Open; Close\] statues and \[Normal; Hover\] states matrix.

### Interaction Tests

- There is a button where the initial value of the drop-down menu is entered, and when clicked, the drop-down is opened.
- When an item in the opened drop-down is selected, the drop-down closes and the button text changes to the selected value.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate visual regression tests.
- [x] I have added appropriate interaction tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.  
       _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the component can be operated using only the keyboard.
- [x] I have confirmed that the focus state of the component is visually discernible.

2024-07-17 02:30 UTC, poetrainy commented
This branch is scheduled to open as soon as the design checks are complete.

2024-07-19 01:14 UTC, poetrainy commented
I have confirmed with Mr. Keitaro that no implementation is required for the variant, so I will open the branch without changing the code.

2024-07-22 02:26 UTC, yodas7 requested changes

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> + * Primary UI component for user interaction
Descriptive comments would be helpful.

- Use as a direct child element of daikin-dropdown

etc.

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +    const event = new CustomEvent("dropdownItemClick", {
I think just "select" is fine?

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown-item/stories/framework-react.tsx
> +    <ReactDaikinDropdownItem {...props}>Value</ReactDaikinDropdownItem>
Value makes it look like an internal value.

```suggestion
    <ReactDaikinDropdownItem {...props}>Dropdown Item</ReactDaikinDropdownItem>
```

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown-item/stories/framework-wc.ts
> +    <daikin-dropdown-item value=${value}>Value</daikin-dropdown-item>
```suggestion
    <daikin-dropdown-item value=${value}>Dropdown Item</daikin-dropdown-item>
```

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +        text: this.textContent,
I don't think `text` is needed.

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +              this._handleClickChange(e)}
beautiful. awesome.

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  override ariaLabel = "";
maybe we don't have to declare this?

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.visual.test.ts
> +      describeEach(["exist", "none"] as const, (leftIcon) => {
```suggestion
      describeEach(["left", "none"] as const, (icon) => {
```

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.visual.test.ts
> +  describeEach(["exist", "none"] as const, (label) => {
```suggestion
  describeEach(["labeled", "unlabeled"] as const, (label) => {
```

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.visual.test.ts
> +});
We may want interactive variants (hover, focus, etc.) for small/medium, labeled/unlabeled, open/close dropdowns.

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/stories/framework-react.tsx
> +        <ReactDaikinDropdownItem value="value3">Value3</ReactDaikinDropdownItem>
```suggestion
        <ReactDaikinDropdownItem value="value1">Item 1</ReactDaikinDropdownItem>
        <ReactDaikinDropdownItem value="value2">Item 2</ReactDaikinDropdownItem>
        <ReactDaikinDropdownItem value="value3">Item 3</ReactDaikinDropdownItem>
```

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/stories/framework-wc.ts
> +        <daikin-dropdown-item value="value3">Value3</daikin-dropdown-item>
```suggestion
        <daikin-dropdown-item value="value1">Item 1</daikin-dropdown-item>
        <daikin-dropdown-item value="value2">Item 2</daikin-dropdown-item>
        <daikin-dropdown-item value="value3">Item 3</daikin-dropdown-item>
```

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  contentsRef: Ref<HTMLElement> = createRef();
```suggestion
  private _buttonRef = createRef<HTMLElement>();

  private _contentsRef = createRef<HTMLElement>();
```

2024-07-22 02:26 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
I think we need a `value` prop.
Also it would be better if this component could act as a form.

2024-07-23 05:10 UTC, yodas7 commented on src/components/dropdown/stories/daikin-dropdown.stories.ts
> +};
We should have stories with:

- no options (if it's allowed)
- only 1 option
- many (20 or more) options

2024-07-23 05:10 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
Don't we need disabled options?

2024-07-23 05:11 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
Don't we need disabled and readonly dropdown lists?

2024-07-23 05:29 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +    "w-[218px]",
I'm sorry, but it looks like this one won't work.

2024-07-23 05:31 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +          "leading-[22px]",
This too.

2024-07-23 05:32 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +          "min-h-[42px]",
This too.

2024-07-23 05:39 UTC, poetrainy commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +      class="w-[216px] minH-[42px] bg-white py-[10px] px-[12px] font-daikinSerif text-[15px] leading-[22px] text-left hover:bg-[#ebebeb]"
The same applies here. Some of the codes were not applicable.

2024-07-23 05:44 UTC, poetrainy commented on src/components/dropdown-item/daikin-dropdown-item.ts
I'll check with the designer.

2024-07-23 05:44 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
I'll check with the designer.

2024-07-23 06:10 UTC, poetrainy commented on src/components/dropdown/stories/daikin-dropdown.stories.ts
> +};
I will check with the designer whether scrolling is necessary when there are a large number of items (approximately 20 items are expected).

2024-07-23 06:13 UTC, poetrainy commented
@yodas7 
I have made the corrections except for the items that need to be checked by the designer, so I will request a review again.

2024-07-23 06:16 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    "w-[218px]",
Got it. I noticed .5 only works under 4.0 (i.e. 0.5, 1.5, 2.5 and 3.5).
You can leave the code as is, but please check with the designer just in case.

2024-07-23 06:27 UTC, yodas7 requested changes

2024-07-23 06:27 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +
Handle the case where `focusedItemIndex < 0`.

2024-07-23 06:43 UTC, yodas7 requested changes

2024-07-23 06:43 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  leftIcon?: IconType;
```suggestion
  leftIcon: IconType | null = null;
```

2024-07-23 06:43 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  @property({ type: String, reflect: true, attribute: "label-position" })
Basically, I want to decide whether or not to reflect based on the following policy:

- If it is Boolean, then reflect
- If it is a String, reflect if there is a possibility of using an attribute selector.

```suggestion
  @property({ type: String, attribute: "label-position" })
```

2024-07-23 06:43 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  @property({ type: String, reflect: true, attribute: "left-icon" })
```suggestion
  @property({ type: String, attribute: "left-icon" })
```

2024-07-23 06:43 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> + * * A dropdown list component.
```suggestion
 * A dropdown list component.
```

2024-07-23 06:43 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +      .catch((e: unknown) => console.error(e));
We should use [autoUpdate](https://floating-ui.com/docs/autoupdate)

2024-07-31 04:36 UTC, poetrainy commented
Disabled fix completed.
Work on the maximum height limit has not yet begun.

2024-08-02 06:44 UTC, yodas7 commented
Please check two unresolved comments.
Also, I think we should use `listbox` role.

2024-08-08 02:32 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  protected override updated(changedProperties: PropertyValues): void {
```suggestion
  protected override updated(changedProperties: PropertyValues<this>): void {
```

2024-08-08 02:33 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +      }
```suggestion
      let itemIndex = this._items.findIndex(
        ({ value }) => this.value === value
      );
      
      if (itemIndex < 0) {
        itemIndex = 0;
        this.value = this._items[itemIndex].value;
      }

      this._buttonLabel = this._items[itemIndex].textContent ?? "";
      this._items[itemIndex].selected = true;
```

2024-08-08 02:50 UTC, yodas7 requested changes
Added two comments.

2024-08-08 03:53 UTC, poetrainy commented
@yodas7 Thank you. I've made the corrections.

2024-08-08 06:48 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +      }
@poetrainy 
`@queryAssignedElements` is expensive, so please store it as a variable.

2024-08-08 06:48 UTC, yodas7 requested changes
@poetrainy
`@queryAssignedElements` is expensive, so please store it (`this._items`) as a variable.

2024-08-08 06:49 UTC, yodas7 commented
Also, please add a Changeset.

2024-08-19 05:16 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  _buttonLabel = "";
nit.
```suggestion
  private _buttonLabel = "";
```

2024-08-19 05:16 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  _items!: DaikinDropdownItem[];
```suggestion
  private _items!: DaikinDropdownItem[];
```

2024-08-19 05:17 UTC, yodas7 approved these changes
LGTM

2024-08-21 05:37 UTC, yodas7 commented
Waiting for the design spec of the maximum height of the dropdown list.
Once it is finalized, we will request a code review.

2024-09-09 03:02 UTC, yodas7 commented
I'll close and re-open this PR to run Netlify deploy preview.

2024-09-09 03:04 UTC, yodas7 commented
Maybe it didn't need to be reopened.
The preview is below:
https://deploy-preview-25--dds-storybook.netlify.app/

2024-09-09 05:34 UTC, yodas7 requested changes

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> + *
Add `@fires`, `@slot` and `Hierarchy:`.

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +      },
nit. Maybe we don't need this, as we can use `event.target` to identify the element.

```suggestion
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +    this.shadowRoot?.querySelector("button")?.focus(options);
nit. Maybe we should use [`@query`](https://lit.dev/docs/components/shadow-dom/#query).

```suggestion
    this._button?.focus(options);
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  private _reflectButtonLabel() {
```suggestion
  private _reflectOptionsAndLabel() {
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
1. `selected` is not updated if `itemIndex < 0`.
2. `_buttonLabelType` is not updated if `itemIndex < 0`.
3. I think it is preferable to have a button label type that indicates whether or not the currently selected item is available - From this perspective, it would be more natural to refer to the `this.placeholder` directly in the `render`, rather than using `this._buttonLabel`.

```suggestion
    const selectedItem = items.find(
      ({ value }) => this.value === value
    );

    for (const item of items) {
      item.selected = item === selectedItem;
    }

    this._hasSelectedItem = !!selectedItem;
    this._selectedItemLabel = selectedItem?.textContent ?? "";
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +        </button>
```suggestion
        <button
          type="button"
          class=${cvaButton({
            error: this.error,
            placeholder: !!this._hasSelectedItem,
          })}
          aria-expanded=${this.open && !this.disabled}
          ?disabled=${this.disabled}
          @click=${this._handleClick}
          ${ref(this._buttonRef)}
        >
          ${this._hasSelectedItem ? this.placeholder : this._selectedItemLabel}
        </button>
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +            state: this.open && !this.disabled ? "visible" : "hidden",
nit.

```suggestion
            open: this.open && !this.disabled,
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  }
We should not react to "select" event dispatched from unmanaged elements.
Also, we don't have to add `detail` as the user can retrieve the current value via `event.target.value`.

```suggestion
  private _handleSelect(event: SelectEvent) {
    const item = event.target;
    if (!this._items.include(item)) {
      return;
    }

    this._hasSelectedItem = true;
    this._selectedItemLabel = event.target.textContent ?? "";

    this.open = false;
    this.value = e.detail.value;

    this.dispatchEvent(new Event("change"));
  }
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> + * @fires change - When an item in the drop-down list is selected, it returns the value of the selected item.
```suggestion
 * @fires change - A custom event emitted when a user selects a dropdown item.
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> + * A dropdown list component.
```suggestion
 * A dropdown list component.
 *
 * Hierarchy:
 * - `daikin-dropdown` > `daikin-dropdown-item`
```

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown/stories/daikin-dropdown.stories.ts
> +  play: definePlay(async ({ args, canvasElement, step }) => {
- Test that the event is fired and that the target.value of the event is correct
- Test that the disabled dropdown and dropdown items do not respond

2024-09-09 05:34 UTC, yodas7 commented on src/components/dropdown-item/stories/daikin-dropdown-item.stories.ts
> +  },
- Test that the event is fired.
- Test that the disabled dropdown items do not fire events

2024-09-09 05:42 UTC, yodas7 commented
Also, the dropdown menu should close when the user clicks outside of the menu.

2024-09-11 04:48 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +      },
@poetrainy ping

2024-09-11 04:49 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    this.value = event.detail.value;
```suggestion
    this.value = target.value;
```

2024-09-11 05:00 UTC, yodas7 requested changes

2024-09-11 08:35 UTC, yodas7 requested changes
I meant to copy only the part of `@eslint/compat`.
Please revert the ESLint rules - this would have too much of an impact.

2024-09-12 05:09 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +        aria-required=${this.required}
I don't think we can use aria-required to the button

2024-09-12 05:43 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +        aria-required=${this.required}
@yodas7 
Button has changed the role to combobox. At this time, I thought it would be okay to use `aria-required`, but was I mistaken?
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/

2024-09-13 06:31 UTC, yodas7 approved these changes
LGTM

2024-10-17 02:54 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +
```suggestion
    const operation = (
      {
        ArrowDown: "moveDown",
        ArrowUp: "moveUp",
        Escape: "close",
      } as const
    )[event.key];

    if (!operation) {
      return;
    }

    if (operation === "close") {
      if (this.open) {
        // Close
        this.open = false;
      } else {
        // Clear selection
        this.value = undefined;
      }
      return;
    }

    const moveOffset = operation === "moveUp" ? -1 : 1;
```

2024-10-17 02:54 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    checkIsDisabledElementAndFocus(focusedItemIndex, moveOffset);
Please rewrite this with loop instead of recursion.
Beware of infinite loop.

2024-10-17 04:54 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +    checkIsDisabledElementAndFocus(focusedItemIndex, moveOffset);
@yodas7 
Two corrections have been made.

2024-10-17 23:02 UTC, hiro-daikin requested changes

2024-10-21 07:48 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +        this.value = undefined;
I'm not sure if we should use `undefined` for `this.value`.
In HTML standards, `value` is always a string because some option is always selected.
Maybe we should use `null` instead of `undefined`.

2024-10-21 07:48 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +        .catch((error: unknown) => console.error(error));
nit. We don't have to do `console.error`.

```suggestion
      this.updateComplete
        .then(() => {
          item.focus();
        }, () => {
         // do nothing
        });
```

2024-10-22 09:00 UTC, yodas7 commented on package.json
> +    "@eslint/compat": "^1.1.1",
We don't need this as `eslint-plugin-wc@^2.2.0` is released.

2024-10-23 00:30 UTC, poetrainy commented on icons/dropdown-check.svg
At present, since the icons are independent for each component, we are using prefixes for management purposes.

2024-10-23 00:44 UTC, poetrainy commented on package.json
> +    "@eslint/compat": "^1.1.1",
Because `fixupConfigRules` is used in eslint.config.js, it could not be deleted.

2024-10-23 05:30 UTC, yodas7 commented on package.json
> +    "@eslint/compat": "^1.1.1",
`@eslint/compat` is only used to fix issues with `eslint-plugin-wc`, but since the issues were fixed in `eslint-plugin-wc` v2.2.0, it is no longer necessary.
You can update `eslint-plugin-wc` to 2.2.0 and remove `@eslint/compat` and `fixupConfigRules `.

2024-10-23 07:55 UTC, yodas7 requested changes

2024-10-23 07:55 UTC, yodas7 commented on eslint.config.js
Revert please.

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown-item/stories/common.ts
> +  __vrtSelected__: {
```suggestion
  selected: {
```

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +  selected = false;
```suggestion
  /**
   * Whether the dropdown item is selected.
   * Set automatically by `daikin-dropdown` component.
   */
  @property({ type: Boolean, reflect: true })
  selected = false;
```

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +  private _button: HTMLButtonElement | null | undefined;
nit.

```suggestion
  private _button!: HTMLButtonElement | null;
```

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown-item/daikin-dropdown-item.ts
> +   * Dropdown item value text
```suggestion
   * Form value of the dropdown item.
```

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +   * Dropdown value
```suggestion
   * Form value of the dropdown.
   * `null` if not selected.
```

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +   * Whether the dropdown is error
```suggestion
   * Whether the dropdown is in an error state.
```

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +   * Whether or not a drop-down menu is displayed
```suggestion
   * Whether the dropdown menu is opened.
```

2024-10-24 08:11 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
It seems that the `daikin-dropdown` component does not support native form feature (i.e. `attachInternals()`).
Could you add it?

2024-10-24 09:01 UTC, yodas7 approved these changes

2024-10-24 09:01 UTC, yodas7 commented
Resolve conflicts please.

2024-10-25 01:09 UTC, hiro-daikin commented on icons/dropdown-check.svg
@poetrainy 
That is fine, but hopefully we can remove this technical debt in the near future

2024-10-25 08:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
If the user enter a printable key, the dropdown will open. Then, search.

```suggestion
    const printableCharacter = event.key.length === 1 ? event.key : null;
    if (printableCharacter) {
      this._searchItem(printableCharacter);
      return;
    }

    const operation = (
      {
        ArrowDown: "down",
        ArrowUp: "up",
        Escape: "close",
      } as const
    )[event.key];
    if (!operation) {
      return;
    }
```

2024-10-25 08:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
```suggestion
  private _searchItem(prefix: string): void {
    // Open the dropdown if not.
    if (!this.open) {
      this.open = true;
      this.updateComplete.then(() => {
        // Search when opened.
        this._searchItem(prefix);
      })
      .catch(() => {
        // do nothing
      });
      return;
    }

    // Focus on the first enabled item with specified prefix.
    const prefixLowerCase = prefix.toLowerCase();
    const item = this._items.find(
      (item) => !item.disabled && item.textContent?.toLowerCase().startsWith(prefixLowerCase)
    );
    item?.focus();
```

2024-10-25 08:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
```suggestion
    switch (operation) {
      case "down":
      case "up":
        this._moveFocus(operation === "up" ? -1 : 1);
        break;

      case "close":
        this._handleKeyDownEscape();
        break;
    }
```

2024-10-25 08:34 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +        });
I think using CSS variables is better than directly applying styles.

```suggestion
        elements.floating.style.setProperty("--floating-width", `${rects.reference.width}px`);
```

2024-10-25 08:35 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
With this, `if (!operaiton)` is no more needed.

2024-10-28 01:03 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +    }
@yodas7 
Can I use the printable keys even if the dropdown menu is not open?
Could you tell me the reference documents you used?

2024-10-28 01:10 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +    }
@yodas7 
With this implementation, it seems that the focus does not move within the item.

2024-10-28 01:16 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
@poetrainy 
[****](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/)

2024-10-28 01:18 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
I see. We should move on to the next item.

2024-10-28 01:38 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +        class="w-[--floating-width] max-h-[200px] overflow-y-auto m-0 p-0 absolute left-[--floating-x,0] top-[--floating-y,0] right-auto bottom-auto opacity-1 transition-[opacity] rounded-[4px] shado
```suggestion
        class="min-w-[--floating-width] max-h-[200px] overflow-y-auto m-0 p-0 absolute left-[--floating-x,0] top-[--floating-y,0] right-auto bottom-auto opacity-1 transition-[opacity] rounded-[4px] shadow-dropdown"
```

2024-10-28 01:38 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +      (item) => item.textContent?.[0].toLowerCase() === prefix.toLowerCase()
```suggestion
      (item) => !item.disabled && item.textContent?.toLowerCase().startsWith(prefix.toLowerCase())
```

2024-10-28 01:38 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    );
```suggestion
    );
    if (!items.length) {
      return;
    }
```

2024-10-28 01:38 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
```suggestion
    // Focus on the first or next item with specified prefix.
    const nextItem = items[(focusedItemIndex + 1) % items.length];
    nextItem.focus();
```

2024-10-28 01:38 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  private _searchItem(prefix: string): void {
```suggestion
  private _searchItem(prefix: string): void {
    // Open the dropdown if not.
    if (!this.open) {
      this.open = true;
      this.updateComplete.then(() => {
        // Search when opened.
        this._searchItem(prefix);
      })
      .catch(() => {
        // do nothing
      });
      return;
    }

```

2024-10-28 01:38 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    if (this.open && printableCharacter) {
```suggestion
    if (printableCharacter) {
```

2024-10-28 05:50 UTC, poetrainy commented on src/components/dropdown/daikin-dropdown.ts
> +    }
@yodas7 
Thank you for teaching me. I didn't know about this specification.

2024-10-28 07:17 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    }
```suggestion
    // If there is no item focused, then focus on the first item
    if (focusedItemIndex === -1) {
      moveOffset = 1;
    }
```

2024-10-29 04:57 UTC, yodas7 reviewed
I'd like to improve focus management.

2024-10-29 04:57 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +  }
```suggestion
  }

  private _lastFocusedItem: DaikinDropdownItem | null = null;  

  /**
   * Opens the dropdown and focuses on the appropriate item.
   */
  private _open(): void {
    if (this.open) {
      return;
    }
    
    this.open = true;
    this.updateComplete.then(() => {
      const items = this._items;
      const item = items.find((item) => item === this._lastFocusedItem) ?? items.find((item) => item.value === this.value) ?? items[0];
      item?.focus();
    })
    .catch(() => {
      // do nothing
    });
  }

  /**
   * Closes the dropdown and focuses on the field.
   */
  private _close(): void {
    if (!this.open) {
      return;
    }
    
    const activeElement = document.activeElement;
    this._lastFocusedItem = (activeElement && items.find((item) => item.contains(activeElement)) ?? null;
    
    this.open = false;
    this.updateComplete.then(() => {
      this.focus();
    })
    .catch(() => {
      // do nothing
    });
  }  
```

2024-10-29 04:57 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    this.open = false;
```suggestion
    this._close();
```

2024-10-29 04:57 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    this.open = !this.open;
```suggestion
    if (this.open) {
      this._close();
    } else {
      this._open();
    }
```

2024-10-29 04:57 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    if (!this.open) {
```suggestion
    if (!this.open) {
      // Not using `this._open()` since we manage focus ourselves here.
```

2024-10-29 04:57 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +      this.open = false;
```suggestion
      this._close();
```

2024-10-29 04:57 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +        });
```suggestion
      this._open();
```

2024-10-29 04:57 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    this.value = target.value;
```suggestion
    this.value = target.value;

    this._close();    
```

2024-10-29 07:36 UTC, yodas7 commented on src/components/dropdown/daikin-dropdown.ts
> +    this._lastFocusedItem = nextItem;
Maybe we should listen to the `focusin` event in the `<slot>`?

2024-10-29 09:36 UTC, yodas7 approved these changes
I believe it's all right now.

2024-11-05 18:27 UTC, hiro-daikin approved these changes

2024-11-07 00:48 UTC, merged