DDS-905 Add tooltips component
dsv-rp/DDS pull request #29
Opened 2024-07-23 01:33 UTC by rinjInTokyo

This PR adds Tooltip (`daikin-tooltip`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-905](https://daikinsvoil.atlassian.net/browse/DDS-905)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/NXXTOI32oZFrGsEDFFCqD0/DDS%3A-Design-Kit?node-id=20023-3168&m=dev)

## API Design
[JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3085500420/Tooltips+Component+API)

## How Has This Been Tested?

- VRT (Visual Regression Test) for [light, dark] variant and ["top", "bottom", "left", "right"] placement and when tooltip in ["center",  "leftTop", "rightBottom"] of page.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-07-23 06:11 UTC, yodas7 requested changes

2024-07-23 06:11 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    });
`autoUpdate` should be called only once.
We should do this in `connectedCallback` and cleanup in `disconnectedCallback` if possible.
if not, we should do this in `firstUpdated` method but we'll still need to clean it up in some way.

2024-07-23 06:11 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +      ?.assignedElements()[0];
We should wrap the default slot with `<div class="contents">` so that the users can use multiple elements for trigger.

2024-07-23 06:11 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    const float = this.shadowRoot?.querySelector("span");
```suggestion
    const float = this._tooltip;
```

2024-07-23 06:11 UTC, yodas7 commented on src/components/tooltip/stories/framework-wc.ts
> +            id elemental cetus massa eu ipsum.
It might be better to make the tooltip content configurable.

2024-07-23 06:55 UTC, yodas7 commented
Also we should use [ref](https://lit.dev/docs/templates/directives/#ref) instead of query for getting elements in templates.

2024-07-24 06:27 UTC, rinjInTokyo commented on src/components/tooltip/daikin-tooltip.ts
> +    });
@yodas7 
I move autoUpdate from updated function to mouse move enter event and clean it in mouse move out event.

2024-07-24 06:32 UTC, rinjInTokyo commented on src/components/tooltip/daikin-tooltip.ts
> +    "max-w-[312px]",
@yodas7 
I revise the top and left to suggestion, about "max-w-78" it seems not work so if need i have to add custom name into tailwind config file

2024-07-24 09:13 UTC, yodas7 commented
pls add `@floating-ui/dom` to `include` in `.storybook/main-common.ts`.

2024-07-24 09:18 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    "max-w-[312px]",
It's ok then.

2024-07-24 09:28 UTC, yodas7 requested changes

2024-07-24 09:28 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    this._cleanUpAutoUpdate = autoUpdate(reference, float, () => {
```suggestion
    this._cleanUpAutoUpdate?.();
    this._cleanUpAutoUpdate = autoUpdate(reference, float, () => {
```

2024-07-24 09:28 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  private _cleanUpAutoUpdate!: () => void;
```suggestion
  private _cleanUpAutoUpdate: (() => void) | null = null;
```

2024-07-24 09:28 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    this._cleanUpAutoUpdate();
```suggestion
    this._cleanUpAutoUpdate?.();
    this._cleanUpAutoUpdate = null;
```

2024-07-24 09:28 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  }
We should use `open` property for managing display state.

2024-07-24 09:28 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  private _triggerElement!: HTMLElement | null;
It might be better to use [ref](https://lit.dev/docs/templates/directives/#ref).

2024-07-24 09:28 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  slotItems?: Array<Node>;
No longer needed.

```suggestion
```

2024-07-25 03:14 UTC, yodas7 requested changes

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  }
I think it is okay to update `this.open` directly in the caller.

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  }
I think we don't need this anymore.

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  _runAutoUpdate() {
```suggestion
  private _startAutoUpdate() {
```

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  _handleClick() {
```suggestion
  private _handleClick() {
```

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  _handleMouseLeave() {
```suggestion
  private _handleMouseLeave() {
```

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  _handleMouseEnter() {
```suggestion
  private _handleMouseEnter() {
```

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  _handleClick() {
We should move this method below `_runAutoUpdate` method.

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +
Maybe we want a disconnectedCallback:

```ts
override disconnectedCallback() {
  this._cleanUpAutoUpdate?.();
  this._cleanUpAutoUpdate = null;
  this.open = false;
}
``

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    this._runAutoUpdate();
I think `_runAutoUpdate` and cleanup should be done in `updated` callback, so that it works also when `open` is set programatically.

2024-07-25 03:14 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +          <span>${this.description}</span>
Let's make it easy to add line breaks, following the standard HTML tooltips (`title` attr).

```suggestion
          <span class="whitespace-pre-line">${this.description}</span>
```

2024-07-25 03:18 UTC, yodas7 requested changes

2024-07-25 03:18 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * @fires mouseenter - Emitted when the mouse cursor move enter trigger element
`@fires` describes the events that cause the component to fire.
In this case, the tooltip component does not fire any events, so `@fires` is not necessary.
(Although I suppose it would be fine to fire events such as "open" and "close".)

```suggestion
 * @slot - A slot for the element to which the tooltip is attached (the trigger element).
 * @slot description - A slot for the tooltip content.
```

2024-07-25 03:18 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * @fires mouseenter - Emitted when the mouse cursor move enter trigger element
BTW I thought `tooltip` is a better slot name than `description`.

2024-07-25 03:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +        ${ref(this._triggerRef)}
Add `part` so that the user can style trigger container.

```suggestion
        ${ref(this._triggerRef)}
        part="trigger"
```

2024-07-25 03:21 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +      <span ${ref(this._tooltipRef)} class="${tooltipClassName}">
This one too.

```suggestion
      <span ${ref(this._tooltipRef)} part="tooltip" class="${tooltipClassName}">
```

2024-07-25 05:39 UTC, yodas7 requested changes

2024-07-25 05:39 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  private uninstallAutoUpdate() {
```suggestion
  private _uninstallAutoUpdate() {
```

2024-07-25 05:39 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * @slot description - A slot for the tooltip content.
```suggestion
 * @slot tooltip - A slot for the tooltip content.
```

2024-07-25 05:39 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +   * Specifies the content of the tooltip. Ignored if the description slot exists.
```suggestion
   * Specifies the content of the tooltip. Ignored if the tooltip slot exists.
```

2024-07-25 05:39 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    this.uninstallAutoUpdate();
```suggestion
    this.open = false;
```

2024-07-25 05:39 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    this._startAutoUpdate();
```suggestion
    this.open = true;
```

2024-07-25 05:39 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +        this._cleanUpAutoUpdate?.();
```suggestion
        this._cleanUpAutoUpdate?.();
        this._cleanUpAutoUpdate = null;
```

2024-07-25 09:17 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +      <span ${ref(this._tooltipRef)} part="tooltip" class="${tooltipClassName}">
nit.

```suggestion
      <span ${ref(this._tooltipRef)} part="tooltip" class=${tooltipClassName}>
```

2024-07-26 00:32 UTC, hiro-daikin commented on package.json
> +    "@floating-ui/dom": "^1.6.8",
I've recently heard about the new `popover` API. 
Not sure if you're familiar, but might be worth taking a look.
If we can do it natively, that might be the better option to keep bundle size lower.

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

2024-07-26 02:54 UTC, rinjInTokyo commented on package.json
> +    "@floating-ui/dom": "^1.6.8",
@hiro-daikin 
Thanks! I just heard about that now.
Calculating the position and make sure the tooltip always be a good place is the reason for using floating-ui.
Using [popover api + CSS Anchor Positioning](https://zenn.dev/cybozu_frontend/articles/css-anchor-positioning) may be a good idea to do it natively in the future.
For now, both of them are new api and may be some risk when using some browser. 
Creating a verify and retouching task my be better

2024-07-29 21:52 UTC, hiro-daikin commented on package.json
> +    "@floating-ui/dom": "^1.6.8",
@rinjInTokyo You bring up a good point. Currently `popover` is supported in all the latest browsers, but `Anchor Positioning` is not available yet in Firefox or Safari. In general, we want to support all major browsers, so we can consider this item later.

I've added the ticket to Jira: https://daikinsvoil.atlassian.net/browse/DDS-1226

2024-07-29 22:08 UTC, hiro-daikin commented on src/components/tooltip/stories/daikin-tooltip.stories.ts
> +    // TODO: hover function is not work well when using storybook test library
It might be good to add a ticket and reference the ticket number here.
Otherwise, we might forget about it

2024-07-29 22:09 UTC, hiro-daikin approved these changes

2024-07-31 07:53 UTC, yodas7 requested changes

2024-07-31 07:53 UTC, yodas7 commented on src/components/tooltip/stories/framework-wc.ts
> +          class="innerArea"
No need to set class here?

2024-07-31 07:53 UTC, yodas7 commented on src/components/tooltip/stories/framework-wc.ts
> +        class="viewArea"
We should use `data-testid` for identifiers used for testing purposes.

```suggestion
        data-testid="view-area"
```

2024-07-31 07:53 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +   * Specifies tooltip type
```suggestion
   * Specifies tooltip theme
```

2024-07-31 07:53 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +   * Specifies whether the tooltip should be open when it first renders
```suggestion
   * Whether the tooltip is open. 
```

2024-07-31 07:53 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * @slot tooltip - A slot for the tooltip content.
We may want `toggle` and `beforetoggle` events - see https://developer.mozilla.org/en-US/docs/Web/API/Popover_API#events.

2024-07-31 07:53 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +        middleware: [offset({ mainAxis: 20 }), flip(), shift()],
It might be possible to make it customizable.

```suggestion
        middleware: [offset({ mainAxis: spacing }), flip(), shift()],
```

where

```ts
const hostStyles = window.getComputedStyles(this);
const spacing = parseInt(hostStyles.getPropertyValue("--dds-tooltip-spacing") || DEFAULT_TOOLTIP_SPACING, 10);
```

2024-07-31 07:53 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * @slot tooltip - A slot for the tooltip content.
Also, since we can control tooltip toggle using `open` prop, we may want to provide an option to disable toggling by hover.

```
trigger: "hover" | "manual" = "hover";
```

2024-08-02 01:04 UTC, yodas7 commented on package.json
> +    "@floating-ui/dom": "^1.6.8",
@rinjInTokyo
Please left a comment which includes `TODO(DDS-1226): ...`.

2024-08-02 01:05 UTC, yodas7 commented on src/components/tooltip/stories/daikin-tooltip.stories.ts
> +    // TODO: hover function is not work well when using storybook test library
@rinjInTokyo 
I've created ticket: https://daikinsvoil.atlassian.net/browse/DDS-1269 .
Left a comment which includes `// TODO(DDS-1269): ...`

2024-08-02 05:40 UTC, yodas7 requested changes

2024-08-02 05:40 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    }
This check has to be done before dispatching an event to avoid sending useless events.

2024-08-02 05:40 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    );
This can be done just before calling `computePosition()`.
Also, "20" and "20px" in `styles` should be extracted as a const.

2024-08-02 05:40 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * @slot tooltip - A slot for the tooltip content.
```suggestion
 * @fires beforetoggle - _Cancellable._ A custom event emitted when the tooltip is about to be opened or closed by user interaction.
 * @fires toggle - A custom event emitted when the tooltip is opened or closed.
 *
 * @slot - A slot for the element to which the tooltip is attached (the trigger element).
 * @slot tooltip - A slot for the tooltip content.
 *
 * @cssprop [--dds-tooltip-spacing=20px] - Spacing between the tooltip and the trigger
```

2024-08-02 05:40 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    }
We may want to try using [`@property`](https://developer.mozilla.org/en-US/docs/Web/CSS/@property).

```suggestion
    }
    
    @property --dds-tooltip-spacing {
      syntax: "<length>";
      inherits: true;
      initial-value: 0;
    }
```

2024-08-02 05:42 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * ```
```suggestion
 * @example
 *
 * ```html
 * <daikin-tooltip>
 *   <span slot="tooltip">This is a message</span>
 *   <span>Hover me</span>
 * </daikin-tooltip>
 * ```
 *
 * ```html
 * <daikin-tooltip description="This is a message">
 *   <span>Hover me</span>
 * </daikin-tooltip>
 * ```
```

2024-08-02 09:02 UTC, yodas7 requested changes

2024-08-02 09:02 UTC, yodas7 commented on cspell-dictionary.txt
Please sort again.

2024-08-02 09:02 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    }
Are there any reason we cannot use `@property`?

2024-08-05 01:29 UTC, rinjInTokyo commented on src/components/tooltip/daikin-tooltip.ts
> +    }
@yodas7 
When i use property in styles it show `Unknown at rule @propertylit-plugin(no-invalid-css)` error and not work.
I don't know why may be it's a new api and lit still not support it?

2024-08-05 06:23 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> + * ```
@rinjInTokyo 
Didn't see the change.

2024-08-06 01:47 UTC, yodas7 commented
Made some minor changes regarding code styles.

2024-08-06 02:52 UTC, yodas7 approved these changes
LGTM. Thanks.

2024-08-06 03:12 UTC, yodas7 commented
@rinjInTokyo 
Forgot to mention Changesets; please add a changeset.
e.g. `Add Breadcrumbs Component.`

2024-08-06 07:05 UTC, yodas7 commented on .changeset/rude-bats-smoke.md
> +"@daikin-oss/design-system-web-components": minor
```suggestion
"@daikin-oss/design-system-web-components": patch
```

2024-08-06 07:07 UTC, yodas7 commented
@rinjInTokyo 
I forgot to mention this, but since we are following semver, adding new features at this point will be treated as a patch version update unless it has a breaking change.
Once v1.0.0 is released, it will be a minor version update.

2024-08-06 07:07 UTC, yodas7 approved these changes
LGTM. Thanks.

2024-08-21 05:55 UTC, merged