DDS-1219 Improve component descriptions
dsv-rp/DDS pull request #33
Opened 2024-07-30 06:44 UTC by rinjInTokyo

Add component description

2024-07-30 06:55 UTC, poetrainy commented
Thank you for helping me with my tasks.
I'm concerned about the inconsistencies in the sample strings used for labels and titles within `@example`. I think there was a problem with my sample code as well. Things like whether to use whitespace or hyphens to separate words, whether to include component names in prefixes, and whether to capitalize the first letter of a sentence.

2024-07-30 07:00 UTC, ukkary commented
Link DDS-1219

2024-07-31 01:39 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> + * ```
Only one text input or textarea is expected for the slot in the Input group.
Rather than putting both in one input group, could you please prepare two input groups?

2024-07-31 01:39 UTC, poetrainy commented on src/components/checkbox/daikin-checkbox.ts
> + *  <daikin-checkbox label="checkbox label 1" name="name", value="value"></daikin-checkbox>
Please remove `,`

2024-07-31 01:39 UTC, poetrainy commented on src/components/radio/daikin-radio.ts
> + *  <daikin-radio name="name", value="value"></daikin-radio>
Please remove `,`

2024-07-31 01:40 UTC, poetrainy commented on src/components/button/daikin-button.ts
> + * You can use `daikin-button` component to trigger an action or event
I think it would be better to be consistent about whether or not to add `.` to the end of the sentences in the descriptions.
I think there are a few other places like this.

2024-07-31 01:40 UTC, poetrainy commented on src/components/checkbox/daikin-checkbox.ts
> + *  <daikin-checkbox label="checkbox label 1" name="name", value="value"></daikin-checkbox>
Please remove `,`

2024-07-31 01:40 UTC, poetrainy commented on src/components/toggle/daikin-toggle.ts
> + *  <daikin-toggle name="name", value="value"></daikin-toggle>
Please remove `,`

2024-07-31 02:23 UTC, poetrainy commented on src/components/button/daikin-button.ts
> + *   Accordion-1-content
Could you please check whether the text on the label is appropriate?

2024-07-31 02:31 UTC, poetrainy commented on src/components/accordion-item/daikin-accordion-item.ts
> + *   Accordion-1-content
This is partly because the components I created were not good, but I would like to unify the notation of the sample strings.
If I were to use buttons as an example, I think there is currently a mixture of these types: `Button label text`, `Button label`, `Label text`, `Button-label-text`
Personally, I think that `Button label` (component name + property name, joined by spaces, first letter capitalized) is the easiest to understand.
If possible, I would also like to unify the strings in Storybook, but I can't decide whether it's appropriate to do so in this branch.

2024-07-31 02:32 UTC, poetrainy commented on src/components/button/daikin-button.ts
> + *   Accordion-1-content
This is partly because the components I created were not good, but I would like to unify the notation of the sample strings.
If I were to use buttons as an example, I think there is currently a mixture of these types: `Button label text`, `Button label`, `Label text`, `Button-label-text`
Personally, I think that `Button label` (component name + property name, joined by spaces, first letter capitalized) is the easiest to understand.
If possible, I would also like to unify the strings in Storybook, but I can't decide whether it's appropriate to do so in this branch.

2024-07-31 02:36 UTC, poetrainy commented on src/components/textarea/daikin-textarea.ts
> + *
I don't think a line break is necessary at the end of the line.

2024-07-31 02:37 UTC, poetrainy commented on src/components/text-input/daikin-text-input.ts
> + *
Same as above.

2024-07-31 02:37 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> + *
Same as above.

2024-07-31 02:37 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> + *
Same as above.

2024-07-31 02:37 UTC, poetrainy commented on src/components/button/daikin-button.ts
> + *
Same as above.

2024-07-31 02:56 UTC, rinjInTokyo commented on src/components/button/daikin-button.ts
> + *   Accordion-1-content
@poetrainy 
the button, checkbox component is not appropriate obviously because the copy paste mistake so i fix it first. 
and about other component i'm also not sure that if it should be done now and which is better. so decide it after

2024-07-31 09:47 UTC, yodas7 commented
I've removed myself from the reviewers as I'm the one writing the code.

2024-08-01 08:09 UTC, poetrainy requested changes

2024-08-01 08:13 UTC, poetrainy approved these changes

2024-08-01 23:54 UTC, ukkary approved these changes

2024-08-02 00:31 UTC, hiro-daikin approved these changes

2024-08-02 02:15 UTC, merged