DDS-1033 Progress Bar Component
dsv-rp/DDS pull request #34
Opened 2024-07-31 00:41 UTC by poetrainy

This PR adds Progress Bar (`daikin-progress-bar`) component.

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1033](https://daikinsvoil.atlassian.net/browse/DDS-1033)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/zIwwDGpn7UmrdjfAPcwHX3/DDS%3A-Design-Kit?node-id=25875-3&t=Sgg5DyApfBPrPseA-0)

## API Design

- [JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3106799617/Progress+Bar+Component+API)

## How Has This Been Tested?

### Visual Regression Tests

- \[Inprogress; Completed; Indeterminate; Error\] variants and \[Exist; None\] helpers matrix.

### Interaction Tests

None

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate visual regression tests.
- [ ] I have confirmed that there are no accessibility warnings that can be addressed.

2024-07-31 01:53 UTC, poetrainy commented
Regarding accessibility testing: There is a warning about the color of the text, but there are similar issues in other places, so we will address them all together in the future.

2024-07-31 08:03 UTC, yodas7 requested changes

2024-07-31 08:03 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +      Math.sign(this.max - this.value) === 1 ? this.value : this.max;
```suggestion
    const progressRatio = Math.min(Math.max(this.value / this.max, 0), 1);
```

2024-07-31 08:03 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +        style=${`--percentage-width:${this.max === 100 ? this._viewValue : (this._viewValue / this.max) * 100}%`}
```suggestion
        style=${`--bar-width:${progressRatio * 100}%`}
```

2024-07-31 08:03 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +    }
I don't think we should change `variant`.
I feel it is the user's responsibility.

2024-08-02 06:40 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.visual.test.ts
> +          }),
nit.

```suggestion
          value: variant === "completed" ? 100 : 40,
```

2024-08-05 00:24 UTC, yodas7 reviewed
Code looks good. Add a changeset file.

e.g. "Add Progress Bar Component."

2024-08-05 05:21 UTC, yodas7 requested changes

2024-08-05 05:21 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +        "bg-[#DCDCDC]",
DaikinNeutral 200

2024-08-06 03:14 UTC, yodas7 approved these changes
LGTM. Thanks.

2024-08-06 03:21 UTC, yodas7 requested changes

2024-08-06 03:21 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +});
completed and error has full width, which may not be intended.

```suggestion
const cvaBar = cva([
  "w-full",
  "h-1",
  "overflow-hidden",
  "relative",
  "after:block",
  "after:h-full",
  "after:absolute",
  "after:left-0",
], {
  variants: {
    variant: {
      inprogress: [
        "after:bg-daikinBlue-500"
        "after:w-[--bar-width]",
      ],
      completed: [
        "after:bg-[--colorFeedbackPositive]",
        "after:w-[--bar-width]",
      ],
      indeterminate: [
        "after:bg-daikinBlue-500",
        "after:w-1/2",
        "after:animate-[progress-bar-indeterminate_1200ms_linear_infinite]",
      ],
      error: [
        "bg-[--colorFeedbackNegative]",
        "after:w-[--bar-width]",
      ],
    },
  },
});
```

2024-08-06 07:14 UTC, yodas7 reviewed
LGTM. Thanks!

2024-08-06 07:15 UTC, yodas7 approved these changes

2024-08-07 21:26 UTC, hiro-daikin requested changes

2024-08-07 21:26 UTC, hiro-daikin commented on .changeset/dry-queens-film.md
Does the `filename` get published as well? (If not this is fine)

2024-08-07 21:26 UTC, hiro-daikin commented on src/components/progress-bar/daikin-progress-bar.ts
> +    const progressRatio = Math.min(Math.max(this.value / this.max, 0), 1);
Should we add some sort of input validation?

```
  override updated(changedProperties) {
    if (changedProperties.has('value') || changedProperties.has('max')) {
      this.validateProperties();
    }
  }

  // Validate the 'value' and 'max' properties to ensure they are valid
  validateProperties() {
    if (typeof this.value !== 'number' || this.value < 0) {
      console.warn(`Invalid 'value' property: ${this.value}. Falling back to 0.`);
      this.value = 0;
    }

    if (typeof this.max !== 'number' || this.max <= 0) {
      console.warn(`Invalid 'max' property: ${this.max}. Falling back to 100.`);
      this.max = 100;
    }

    if (this.value > this.max) {
      console.warn(`'value' property: ${this.value} exceeds 'max' property: ${this.max}. Clamping value to max.`);
      this.value = this.max;
    }
  }
```

2024-08-07 21:26 UTC, hiro-daikin commented on src/components/progress-bar/daikin-progress-bar.ts
> +      ></div>
We may need to use some aria attributes.

Reference: https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/Roles/progressbar_role

2024-08-07 21:26 UTC, hiro-daikin commented on src/components/progress-bar/daikin-progress-bar.ts
> +    "after:left-0",
I'm not sure how much of a performance gain we will get, but I believe we can optimize animations by adding `after:will-change-transform`: https://tailwindcss.com/docs/will-change

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

2024-08-08 00:54 UTC, poetrainy commented on src/components/progress-bar/daikin-progress-bar.ts
> +    "after:left-0",
Thank you. Since the only thing using animation is `indeterminate`, I added the above code to that part.

2024-08-08 00:55 UTC, poetrainy commented on src/components/progress-bar/daikin-progress-bar.ts
> +      ></div>
Thank you. The role has been added.

2024-08-08 00:55 UTC, poetrainy commented on src/components/progress-bar/daikin-progress-bar.ts
> +    const progressRatio = Math.min(Math.max(this.value / this.max, 0), 1);
Thank you. I have added that processing.

2024-08-08 01:22 UTC, yodas7 commented on .changeset/dry-queens-film.md
Changeset files are not published; instead, their contents are transcribed into the CHANGELOG file at the time of release. see #39.
Their filenames are automatically generated by Chnagesets CLI to avoid collisions.

2024-08-08 01:23 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +    const progressRatio = Math.min(Math.max(this.value / this.max, 0), 1);
@poetrainy 
Please wrap `console.warn` with `if (import.meta.env.DEV)` when doing this change.

2024-08-08 01:24 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +    const progressRatio = Math.min(Math.max(this.value / this.max, 0), 1);
Maybe we don't have to change props by component. Just warning might be sufficient.

2024-08-08 01:27 UTC, yodas7 commented on src/components/progress-bar/daikin-progress-bar.ts
> +    "after:left-0",
Actually it is not a good idea to use `will-change` beforehand. We should only consider using it if we are experiencing performance issues, otherwise it may actually make things worse.
https://developer.mozilla.org/ja/docs/Web/CSS/will-change

2024-08-15 20:04 UTC, hiro-daikin commented on src/components/progress-bar/daikin-progress-bar.ts
> +    "after:left-0",
@yodas7 I see. I forgot where I saw it, but there are ways to offload some processes to the GPU. Perhaps these optimizations are less important today. 
Let us leave out `will-change` for now.

2024-08-15 20:08 UTC, hiro-daikin approved these changes
LGTM!

2024-08-20 08:17 UTC, merged