DDS-918 DDS-919 Add Notification component
dsv-rp/DDS pull request #4
Opened 2024-06-24 02:34 UTC by poetrainy

This PR adds Notification (`daikin-notification`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-918](https://daikinsvoil.atlassian.net/browse/DDS-918), [DDS-919](https://daikinsvoil.atlassian.net/browse/DDS-919)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/wHAhw4yC54Hjq6Whb8FL5T/DDS%3A-Design-Kit?node-id=21125-661&t=oEpsdbA8Qldr6QhX-0)

## API Design

[JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3019407461/Notification+Component+API)

## How Has This Been Tested?

- VRT (Visual Regression Test) for \[Toast; Inline\] variants and \[Positive; Negative; Warning; Alarm; Information'\] states and \[Single; Multi\] line matrix.
- Fires `click` event when the action button is clicked
- Close the Notification when the Close button is clicked

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-06-24 05:35 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
> +                  data-testid="daikin-notification"
Can we stop using testid and instead test by the presence or absence of content?
It would include the code for the test in the production.

2024-06-24 05:35 UTC, yodas7 commented on __test__/Notification.test.js
> +            ).toHaveLength(1);
I think this one is easier to understand.

```suggestion
            expect(
                await page.$(
                    'daikin-notification >>> div[data-testid="daikin-notification"]',
                )
            ).toBeTruthy();
```

2024-06-24 05:35 UTC, yodas7 commented on __test__/Notification.test.js
> +require('pptr-testing-library/extend');
I don't think we use this package any longer.

2024-06-24 05:54 UTC, yodas7 commented on __test__/Notification.test.js
> +            );
I believe `toBeFalsy` works here.

2024-06-24 05:55 UTC, poetrainy commented on __test__/Notification.test.js
> +require('pptr-testing-library/extend');
Deleted.

2024-06-24 05:55 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +                  data-testid="daikin-notification"
Deleted.

2024-06-24 05:56 UTC, yodas7 commented on __test__/Notification.test.js
> +require('pptr-testing-library/extend');
Please also remove from package.json

2024-06-24 05:57 UTC, poetrainy commented on __test__/Notification.test.js
> +            ).toHaveLength(1);
I had not thought of that method. Fixed.

2024-06-24 06:04 UTC, poetrainy commented on __test__/Notification.test.js
> +            );
Is it because I received an empty array here? `toBeFalsy` did not work well.

2024-06-24 06:05 UTC, poetrainy commented on __test__/Notification.test.js
> +require('pptr-testing-library/extend');
Sorry, Deleted.

2024-06-24 06:34 UTC, poetrainy commented on __test__/Notification.test.js
> +            );
I have made this modification.

2024-06-24 06:50 UTC, yodas7 commented
I'm not sure if externalizing SVG is a good idea.
I guess this depends on whether we want to be able to customize the icons or not.
For example, the checkbox implementation (#5) that uses a specific icon uses tailwindcss-icons plugin to allow icons to be used in TailwindCSS.

2024-06-24 08:01 UTC, KoharaKazuya requested changes

2024-06-24 08:01 UTC, KoharaKazuya commented on src/types/custom.d.ts
@poetrainy 
Please write in `globals.d.ts`.

2024-06-25 03:05 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +import NOTIFICATION_CLOSE_ICON from './assets/daikin-notification-close.svg';
Although there are no clear rules, the constants are described in upper snake case and the types are described in upper camel case.

2024-06-25 03:07 UTC, poetrainy commented on src/components/notification/notification.css
> +        --ColorFeedbackPositive,
Sorry, should have been lower case.

2024-06-25 03:09 UTC, poetrainy commented on src/types/custom.d.ts
Since this description is no longer necessary now that SVG has been entrusted to TailwindCSS-icons, the entire file has been deleted. If it becomes necessary, it will be described in `globals.d.ts` again.

2024-06-25 03:12 UTC, poetrainy commented on __test__/Notification.test.js
> +            ).toHaveLength(0);
I did not do well with that approach.

2024-06-25 04:43 UTC, yodas7 requested changes

2024-06-25 04:43 UTC, yodas7 commented on __test__/Notification.test.js
> +                    if (open === '!true') {
It appears that the test is only executed when "!open".
If it's intentional, please consider defining the value with `const` instead of using `if`.

2024-06-25 06:15 UTC, poetrainy commented on __test__/__image_snapshots__/notification-test-js-notification-inline-alarm-multi-true-false-action-1-snap.png
Fixed a problem with text being broken into new lines.

2024-06-25 06:24 UTC, poetrainy commented on __test__/Notification.test.js
> +                    if (open === '!true') {
This is an intentional test.
The `open` specification has been changed to a constant value.

2024-06-25 06:32 UTC, poetrainy commented on __test__/setupTests.js
> +    blur: 0
I added this code based on Lin's code, but removed it once because it was unnecessary in my test.

2024-06-26 02:29 UTC, hiro-daikin requested changes

2024-06-26 02:29 UTC, hiro-daikin commented on src/components/notification/daikin-notification.ts
> +                          html`<p class="text-[18px] font-bold flex-none">
I believe we are using `Roboto` as the default font. the `daikinSerif` class should have the necessary css rules

2024-06-26 02:29 UTC, hiro-daikin commented on src/components/notification/daikin-notification.ts
> +        const event = new CustomEvent('close');
Should we create `constants` for these custom events?
Also, might be good to be consistent - here it's called `close`, but the one above is prepended with `daikin-`

2024-06-26 02:29 UTC, hiro-daikin commented on __test__/Notification.test.js
> +            expect(await page.$('daikin-notification >>> div')).toBeTruthy();
It might be better to add a data attribute to the elements and add a test id. 
That way, if we change any of the html elements, these tests wouldn't break. 

i.e. `<button data-testid="notification-button"/>...</button>`

Then you can grab by test id here.

This article may be helpful: https://future-architect.github.io/articles/20231128a/

2024-06-26 03:20 UTC, yodas7 commented on __test__/Notification.test.js
> +            expect(await page.$('daikin-notification >>> div')).toBeTruthy();
Personally, it seems to make sense to check for the presence of displayed text content (`Notification-title` in this case).
Given that this is a UI library, there seems to be a disadvantage in exposing the user to the testid, which is only used for testing (but could be removed in the future by tweaking the build tool).

2024-06-26 05:05 UTC, poetrainy commented on src/components/notification/notification.css
> +    border-color: #f68c54;
Tickets on the matter can be found at https://daikinsvoil.atlassian.net/browse/DDS-1071.

2024-06-26 05:06 UTC, poetrainy commented on package.json
> +        "@lit-labs/react": "^2.1.3",
Removed `@lit-labs/react` and installed `@lit/react`.

2024-06-26 05:13 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +        const event = new CustomEvent('close');
The prefix `daikin-` has been added here as well to be consistent with `daikin-action`.

2024-06-26 05:15 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +            : '';
Fixed to return null instead of `''`.

2024-06-26 06:21 UTC, poetrainy commented on tailwind.config.js
> +                            body: '<path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" fill="#
I would like to do that in the future. However, the content is very heavy to do that with this pull request, so I would like to implement it once with hardcoding and then modify this part when I implement the icon component again.

2024-06-26 06:37 UTC, poetrainy commented on __test__/__image_snapshots__/notification-test-js-notification-inline-alarm-multi-true-false-action-1-snap.png
We were told that the Notification inline component was intended to both stretch with the width of the parent element and fit into the element. Therefore, we have modified the Notification inline to maximize the stretching of the element and allow the user to override the width.

2024-06-26 06:39 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +                          html`<p class="text-[18px] font-bold flex-none">
Fixed to use `daikinSerif`.

2024-06-26 08:02 UTC, KoharaKazuya commented on __test__/__image_snapshots__/notification-test-js-notification-inline-alarm-multi-true-false-action-1-snap.png
I got it. Thanks for your explanation.

2024-06-26 08:30 UTC, KoharaKazuya commented on package.json
> +        "@lit-labs/react": "^2.1.3",
@poetrainy 
Thanks.

I'd like to ask you one more favor. Please move this into `devDependencies`.

2024-06-26 09:06 UTC, KoharaKazuya requested changes

2024-06-26 09:06 UTC, KoharaKazuya commented on src/components/notification/stories/daikin-notification-react.stories.tsx
> +            daikinClose={() => console.log('daikin-close')}
@poetrainy 
Please use [`action`](https://storybook.js.org/docs/essentials/actions#exports). For example, `daikin-button-react.stories.tsx`.

2024-06-27 00:28 UTC, poetrainy commented on __test__/setupTests.js
> +    failureThreshold: 0.03,
@KoharaKazuya 
There is an event that causes the test to fail due to fonts (Roboto), and this is a deep-seated problem that cannot be addressed in this release. Therefore, the threshold value has been changed as a temporary measure. The same action has been taken for the Button component. We have an agreement with Mr. Hiro regarding this provisional solution.

2024-06-27 00:35 UTC, poetrainy commented on src/components/notification/stories/daikin-notification-react.stories.tsx
> +            daikinClose={() => console.log('daikin-close')}
@KoharaKazuya 
Sorry, I was mistaken. You mean to remove the prefix. I implemented it as `action`, `close`.

2024-06-27 00:48 UTC, KoharaKazuya commented on __test__/setupTests.js
> +    failureThreshold: 0.03,
@poetrainy 
Thanks. Is there any memo such as issues, tickets, etc?

2024-06-27 00:54 UTC, KoharaKazuya commented on src/components/notification/stories/daikin-notification-react.stories.tsx
> +            daikinClose={() => console.log('daikin-close')}
@poetrainy 
I mean that we should use the `action` function. Please see:

https://github.com/dsv-rp/DDS/blob/35b4023fb5c848ff3c77c57cf3909bfa9a4c3ab4/src/components/button/stories/daikin-button-react.stories.tsx#L14

2024-06-27 01:13 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +        const event = new CustomEvent('close');
Sorry, I was mistaken. You mean to remove the prefix. I implemented it as action, close.

2024-06-27 01:54 UTC, poetrainy commented on src/components/notification/stories/daikin-notification-react.stories.tsx
> +            daikinClose={() => console.log('daikin-close')}
@KoharaKazuya 
Sorry, I did not understand. I have corrected it as such.

2024-06-27 02:13 UTC, yodas7 commented on __test__/setupTests.js
> +    failureThreshold: 0.03,
Created. https://daikinsvoil.atlassian.net/browse/DDS-1138

2024-06-27 02:13 UTC, yodas7 commented on __test__/setupTests.js
> +    failureThreshold: 0.03,
@KoharaKazuya

2024-06-27 02:23 UTC, KoharaKazuya commented on __test__/setupTests.js
> +    failureThreshold: 0.03,
Great 👍

2024-06-27 05:08 UTC, KoharaKazuya commented on src/components/notification/stories/daikin-notification-wc.stories.ts
> +            @close=${action('close')}
@poetrainy 
I think we should check about default value. Please see also: <https://github.com/dsv-rp/DDS/pull/2#discussion_r1650407372>

2024-06-27 06:11 UTC, poetrainy commented on src/components/notification/stories/daikin-notification-wc.stories.ts
> +            @close=${action('close')}
@KoharaKazuya 
Corrected as such.

2024-06-27 06:15 UTC, KoharaKazuya approved these changes

2024-06-27 06:51 UTC, hiro-daikin commented on __test__/Notification.test.js
> +            expect(await page.$('daikin-notification >>> div')).toBeTruthy();
@yodas7 I see your point - I also agree finding by text content is also suitable

2024-06-27 07:03 UTC, hiro-daikin requested changes

2024-06-27 07:03 UTC, hiro-daikin commented on src/components/notification/daikin-notification.ts
> +        const event = new CustomEvent('close');
@poetrainy I meant that maybe we should have a separate file which stores action names. This would help us be consistent when implementing other components with the same action names. 

And on second though, should we also be consistent with html event names like how it is listed here?: https://www.w3schools.com/jsref/event_onclick.asp

```
//constants file

const ON_ACTION_CLICK = 'onactionclick';
const ON_CLOSE = 'onclose';
```

2024-06-27 07:03 UTC, hiro-daikin commented on src/components/notification/daikin-notification.ts
> +                          html`<p class="text-[18px] font-bold flex-none">
I don't see the change reflected - did you push the latest code?

2024-06-27 07:19 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +                          html`<p class="text-[18px] font-bold flex-none">
Perhaps so. It is on line 66 of the most recent change to the file in question.

2024-06-28 01:49 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +        const event = new CustomEvent('close');
@hiro-daikin 
I misread the meaning and I apologize.
I agree about making it constant; I created a new Constants file and implemented it.
However, I think the `on` prefix is unnecessary for event names. This is because HTML has `on` as an attribute, but event names do not. See MDN's Click event and other events for more information: https://developer.mozilla.org/ja/docs/Web/API/Element/click_event

As for the action buttons, I have removed them because we will re-design the properties, etc. before proposing them.

2024-07-01 02:35 UTC, poetrainy commented on __test__/Notification.test.js
> +            expect(await page.$('daikin-notification >>> div')).toBeTruthy();
@hiro-daikin @yodas7 
I have modified it so that the presence or absence of Notification is determined by the presence of text.

2024-07-01 02:37 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +                          html`<p class="text-[18px] font-bold flex-none">
@hiro-daikin 
Sorry, I am correcting a different part of the file than the one you pointed out. Could you please check line 67 of `daikin-notification.ts`?

2024-07-01 02:42 UTC, yodas7 approved these changes
LGTM

2024-07-03 00:01 UTC, hiro-daikin approved these changes

2024-07-03 01:27 UTC, yodas7 commented on __test__/Notification.test.js
> +            expect(await page.$('daikin-notification >>> div')).toBeTruthy();
Resolving as agreed by all participants.

2024-07-03 06:20 UTC, merged