fix: Allowing the size of Text Input to be controlled
dsv-rp/DDS pull request #45
Opened 2024-08-19 02:57 UTC by poetrainy

The size of the Text Input had a fixed value, so we fixed it so that users can control it.

2024-08-19 04:36 UTC, yodas7 reviewed
Changes look good.
Could you add VRT to prevent regression in the future?

2024-08-19 08:19 UTC, yodas7 requested changes

2024-08-19 08:19 UTC, yodas7 commented on src/components/text-input/daikin-text-input.visual.test.ts
> +      describeEach(["resizeSmall", "resizeLarge", null] as const, (vrtArgs) => {
Sorry for the lack of explanation.
To avoid bloat, let's make vrtArgs independent.

2024-08-19 08:19 UTC, yodas7 commented on src/components/textarea/daikin-textarea.visual.test.ts
> +      describeEach(["resizeSmall", "resizeLarge", null] as const, (vrtArgs) => {
Same here.

2024-08-19 08:21 UTC, yodas7 requested changes

2024-08-19 08:21 UTC, yodas7 commented on src/components/text-input/stories/framework-wc.ts
> +      class=${"[&>daikin-text-input]:w-[--vrt-width]"}
Might be good to set both width and height

2024-08-19 08:21 UTC, yodas7 commented on src/components/textarea/stories/framework-wc.ts
> +      class=${`[&>daikin-textarea]:w-[--vrt-width]`}
Might be good to set both width and height.

2024-08-20 08:23 UTC, yodas7 commented on src/components/text-input/stories/framework-react.tsx
> +    );
This might be much straightforward.

```suggestion
    const additionalClassNames = {
      "": "",
      resizeLarge:
        "w-[800px] h-[320px]",
      resizeSmall:
        "w-[160px] h-[40px]",
    }[props.vrtArgs ?? ""];

    return (
      <ReactDaikinTextInput className={additionalClassNames} {...props} />
    );
```

2024-08-21 01:13 UTC, poetrainy commented on src/components/text-input/stories/framework-react.tsx
> +    );
@yodas7 
I'm sorry. I tried the above code with the React version of Storybook, but it didn't work.

2024-08-21 05:25 UTC, yodas7 commented on src/components/text-input/stories/framework-react.tsx
> +    );
@poetrainy 
I tried it out and it worked.
I pushed the changes, so please check them.

2024-08-21 05:28 UTC, yodas7 requested changes
Add a changeset that describes the change.

e.g. `Fixed the issue where Text Input and Textarea could not be resized. (DDS-1279)`

2024-08-21 06:06 UTC, yodas7 approved these changes
LGTM.

2024-08-22 17:27 UTC, toshi-dsv approved these changes

2024-08-22 19:32 UTC, hiro-daikin commented
Can you please edit the description to fit this template:

[.github/PULL_REQUEST_TEMPLATE/bug_fixes.md](https://github.com/dsv-rp/DDS/pull/54/files)

2024-08-22 19:36 UTC, hiro-daikin requested changes

2024-08-22 19:36 UTC, hiro-daikin commented on src/components/text-input/daikin-text-input.visual.test.ts-snapshots/resizeLarge-base-1.png
Should the text here be in the middle?
Or should it be placed up top?

2024-08-23 01:40 UTC, poetrainy commented on src/components/text-input/daikin-text-input.visual.test.ts-snapshots/resizeLarge-base-1.png
@hiro-daikin 
I think middle is fine. I think it would be better for design reasons if the text input was only one line and that text was centered.

2024-08-25 07:21 UTC, hiro-daikin approved these changes

2024-08-26 08:17 UTC, merged