DDS-906 implement checkbox component
dsv-rp/DDS pull request #5
Opened 2024-06-24 04:17 UTC by rinjInTokyo

This PR adds Checkbox (`daikin-checkbox`) component.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-906](https://daikinsvoil.atlassian.net/jira/software/projects/DDS/boards/24/backlog?selectedIssue=DDS-906)
- Figma design: [Figma]

## API Design

[JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3019440180/Checkbox+Component+API)

## How Has This Been Tested?

- VRT (Visual Regression Test) for \[Small; Large\] size and \[Normal; Hover; Pressed; Focus; Disabled\] states matrix.
- confirm that there is no attribute disabled when default
- confirm that there is attribute disabled when disabled

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [x] I have added appropriate unit tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-06-24 08:17 UTC, KoharaKazuya commented on __test__/__image_snapshots__/check-box-test-js-check-box-small-right-indeterminate-enable-1-snap.png
@rinjInTokyo 
The hyphen is not centered.

2024-06-24 08:17 UTC, KoharaKazuya commented on src/components/checkbox/stories/daikin-checkbox-react.stories.tsx
> +            size={size ? size : "small"}
@rinjInTokyo 
https://github.com/dsv-rp/DDS/pull/2#discussion_r1650407372

2024-06-24 08:17 UTC, KoharaKazuya commented on src/components/checkbox/checkbox.css
@rinjInTokyo 
I think we should delete empty file. Is there any reason for this?

2024-06-24 09:06 UTC, rinjInTokyo commented on __test__/__image_snapshots__/check-box-test-js-check-box-small-right-indeterminate-enable-1-snap.png
I try to delete the wrong snapshot and run test again, it seems been fixed

2024-06-24 09:07 UTC, rinjInTokyo commented on src/components/checkbox/checkbox.css
I never use this file so i will delete it

2024-06-25 01:54 UTC, KoharaKazuya requested changes
@rinjInTokyo 
Please work on issue about focus ring. https://github.com/dsv-rp/DDS/pull/2#discussion_r1650377731

2024-06-26 08:21 UTC, KoharaKazuya approved these changes

2024-06-27 07:41 UTC, hiro-daikin requested changes

2024-06-27 07:41 UTC, hiro-daikin commented on __test__/CheckBox.test.js
> +            expect(isDisabled).toBe(false)
For this interaction test, we are checking whether or not the `disabled` attribute exists or not. 

Rather than checking for the attribute, it might be more suitable to perform it like this:

1. Confirm that the checkbox is not selected
2. Click on the checkbox
3. Confirm that the checkbox is selected

2024-06-27 07:41 UTC, hiro-daikin commented on __test__/CheckBox.test.js
> +            expect(isDisabled).toBe(true)
Similar to the above, we should try to click on the checkbox and confirm that the selection was not made

2024-06-27 07:41 UTC, hiro-daikin commented on src/components/checkbox/daikin-checkbox.ts
> +    checkState: "unchecked" | "indeterminate" | "checked";
Should we store these as constants?

i.e.
```
const LABEL_POSITION_LEFT = 'left';
const LABEL_POSITION_RIGHT = 'right';
const CHECK_STATE_UNCHECKED = 'unchecked';
...etc
```

2024-06-27 08:31 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +    checkState: "unchecked" | "indeterminate" | "checked";
We're afraid we're not planning to extract them out as constants.

Since this is a type definition, we do not intend to cut out them as a value.
If the users gives the wrong value, the typedefs here will let they know at that point.

If we were to extract the type definition itself, we would have to extract the entire `"unchecked" | "indeterminate" | "checked"` because the relevance is important.
In that case, the point is whether this type definition may be used independently elsewhere, but for `labelPosition` and `checkState`, we believe that it is currently not.

[FYI React also defines such types directly.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2600)

However, we think it is acceptable to consider extracting when similar definitions are used elsewhere in the future (especially for `labelPosition`).

2024-06-27 09:08 UTC, rinjInTokyo commented on __test__/CheckBox.test.js
> +            expect(isDisabled).toBe(false)
@KoharaKazuya 
I have add interaction to test if checkbox can be selected when click

2024-06-27 09:34 UTC, KoharaKazuya commented on __test__/CheckBox.test.js
> +            expect(isDisabled).toBe(false)
@rinjInTokyo 
I got it. Maybe did you mention to Hiro-san?

2024-06-28 05:04 UTC, yodas7 requested changes

2024-06-28 05:04 UTC, yodas7 commented on __test__/CheckBox.test.js
> +            })
Consider extracting this to a separate function to reuse:

```js
const isChecked = (elementHandle) => page.evaluate((element) => {
    const innerCheckbox = element.shadowRoot.querySelector("input");
    return innerCheckbox.checked;
}, elementHandle);
```

2024-07-01 01:50 UTC, yodas7 requested changes
Some case changes and grouping of tests are suggested. Other than that, looks good to me.

2024-07-01 01:50 UTC, yodas7 commented on __test__/CheckBox.test.js
> +                });
Might be better to use describe.each

2024-07-01 01:50 UTC, yodas7 commented on __test__/CheckBox.test.js
Might be better to name `Checkbox` (lowercase b)

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +type componentSize = labelProps["size"] & checkboxProps["size"];
Type names should start with Uppercase.

```suggestion
type LabelProps = OmitNull<VariantProps<typeof labelCN>>;
type CheckboxProps = OmitNull<VariantProps<typeof checkboxCN>>;
type ComponentSize = LabelProps["size"] & CheckboxProps["size"];
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +class DaikinCheckBox extends LitElement implements DaikinCheckBoxProps {
```suggestion
class DaikinCheckbox extends LitElement implements DaikinCheckboxProps {
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +export interface DaikinCheckBoxProps {
```suggestion
export interface DaikinCheckboxProps {
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +        'daikin-checkbox': DaikinCheckBox;
```suggestion
        'daikin-checkbox': DaikinCheckbox;
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +export default DaikinCheckBox;
```suggestion
export default DaikinCheckbox;
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/common.ts
> +import type { DaikinCheckBoxProps } from '../daikin-checkbox';
```suggestion
import type { DaikinCheckboxProps } from '../daikin-checkbox';
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/common.ts
> +export interface DaikinCheckBoxStoryArgs extends DaikinCheckBoxProps {
```suggestion
export interface DaikinCheckboxStoryArgs extends DaikinCheckboxProps {
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/common.ts
> +type Story = StoryObj<DaikinCheckBoxStoryArgs>;
```suggestion
type Story = StoryObj<DaikinCheckboxStoryArgs>;
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-react.stories.tsx
> +import type { DaikinCheckBoxStoryArgs } from './common';
```suggestion
import type { DaikinCheckboxStoryArgs } from './common';
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-react.stories.tsx
> +const CheckBox: React.FC<DaikinCheckBoxStoryArgs> = ({ size, disabled, readonly, labelPosition, label, checkState }) => {
```suggestion
const Checkbox: React.FC<DaikinCheckboxStoryArgs> = ({ size, disabled, readonly, labelPosition, label, checkState }) => {
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-react.stories.tsx
> +    title: 'Components/CheckBox',
```suggestion
    title: 'Components/Checkbox',
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-react.stories.tsx
> +    component: CheckBox,
```suggestion
    component: Checkbox,
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-react.stories.tsx
> +} satisfies Meta<DaikinCheckBoxStoryArgs>;
```suggestion
} satisfies Meta<DaikinCheckboxStoryArgs>;
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-wc.stories.ts
> +import type { DaikinCheckBoxStoryArgs } from './common.ts';
```suggestion
import type { DaikinCheckboxStoryArgs } from './common.ts';
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-wc.stories.ts
> +    title: 'Components/CheckBox',
```suggestion
    title: 'Components/Checkbox',
```

2024-07-01 01:50 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-wc.stories.ts
> +} satisfies Meta<DaikinCheckBoxStoryArgs>;
```suggestion
} satisfies Meta<DaikinCheckboxStoryArgs>;
```

2024-07-01 05:37 UTC, yodas7 requested changes

2024-07-01 05:37 UTC, yodas7 commented on __test__/Checkbox.test.js
> +                    it('enable', async () => {
Inconsistent when disabled state

```suggestion
                    it('normal', async () => {
```

2024-07-01 05:37 UTC, yodas7 commented on __test__/Checkbox.test.js
> +                describe.each([false, true])("%s", (disabled) => {
Let's use a descriptive name, as it affects test name.

```suggestion
                describe.each(["enabled", "disabled"])("%s", (state) => {
```

2024-07-01 05:37 UTC, yodas7 commented on __test__/Checkbox.test.js
> +                });
Please implement or delete.

2024-07-01 05:37 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +`)
I think we can move this part to line 75 (`const checkboxCN = cva(baseCheckboxCN, {`) and remove the usage of `ctl`.

2024-07-01 05:37 UTC, yodas7 commented on src/components/checkbox/stories/daikin-checkbox-react.stories.tsx
> +const Checkbox: React.FC<DaikinCheckboxStoryArgs> = ({ size, disabled, readonly, labelPosition, label, checkState }) => {
Might be good to use `@lit/react` for consistency.
See https://github.com/dsv-rp/DDS/pull/7/files#diff-e9f63b6f964b8f794dc8abed4d3636989f6e554345ce9de0196d4b33a13abbbb

2024-07-02 04:52 UTC, yodas7 approved these changes
LGTM, thanks.

PSA: Formatting will be done in #12

2024-07-03 00:18 UTC, hiro-daikin commented on src/components/checkbox/daikin-checkbox.ts
> +    checkState: "unchecked" | "indeterminate" | "checked";
@yodas7 We use some of these values in the code like line 179, 180, 195
It may help reduce bugs in the future. 

I'll leave it to your discretion

2024-07-03 00:18 UTC, hiro-daikin approved these changes

2024-07-03 06:33 UTC, merged