DDS-1320 Modified to use Slots for notification descriptions
dsv-rp/DDS pull request #50
Opened 2024-08-22 05:51 UTC by poetrainy

The description of Notification has been modified so that it can use slots.

2024-08-22 06:56 UTC, yodas7 requested changes
I think it would be better to make the `title` slot compatible as well as the `description`.

2024-08-22 06:56 UTC, yodas7 commented on .changeset/old-clouds-type.md
> +The description of Notification has been modified so that it can use slots.
```suggestion
Added an optional `description` slot to the Notification component.
This can be used to specify the description of the Notification instead of the `description` attribute.
```

2024-08-22 06:56 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
> + *
Add `@csspart` when adding `part=`.

2024-08-22 06:56 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
> +              <span part="description" class="text-[18px] flex-none">
I think this should be `div`?

```suggestion
              <div part="description" class="text-[18px] flex-none">
```

2024-08-22 06:56 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
> +                  <span>${this.description}</span>
```suggestion
                  ${this.description}
```

2024-08-23 05:51 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
>     * Title text
```suggestion
   * Title text.
```

2024-08-23 06:00 UTC, yodas7 requested changes

2024-08-23 06:00 UTC, yodas7 commented on src/components/notification/daikin-notification.visual.test.ts
> +              __vrtDescription__: "Description of the notification",
This means that we will always be using the slot, so we won't be able to test the attributes.
Please undo the test case here and create a dedicated test case for testing the slot.

2024-08-23 09:09 UTC, yodas7 commented on src/components/notification/stories/framework-react.tsx
> +      {props.__vrtDescription__ && (
```suggestion
      {!!props.__vrtTitle__ && <span slot="title">{props.__vrtTitle__}</span>}
      {!!props.__vrtDescription__ && (
```

2024-08-26 01:40 UTC, yodas7 commented on src/components/notification/daikin-notification.visual.test.ts
> +});
I think it's okay to put them together in this case.

```suggestion
describeEach(["attribute", "slot"] as const, (insert) => {
  const baseURL = getPageURL({
    variant: "toast",
    title: "Example Notification by attribute",
    description: "Description of the notification by attribute",
    ...(insert === "slot" && {
      __vrtTitle__: "Example Notification by slot",
      __vrtDescription__: "Description of the notification by slot",
    }),
  });

  test("base", async ({ page }) => {
    await page.goto(baseURL);

    // wait for element to be visible
    const element = await page.waitForSelector("daikin-notification", {
      state: "visible",
    });

    // take screenshot and check for diffs
    await expect(page).toHaveScreenshot(await clipFor(element));
  });
});
```

2024-08-26 05:00 UTC, yodas7 commented on .changeset/old-clouds-type.md
> +They can be used to specify the title and description of the Notification instead of the `title` and `description` attribute.
```suggestion
Notification: Added an optional `title` and `description` slots.
These can be used to specify the title and description of the notification instead of the `title` and `description` attributes.
```

2024-08-26 05:01 UTC, yodas7 commented on src/components/notification/daikin-notification.visual.test.ts
> +              __vrtDescription__: "Description of the notification",
Should we undo the changes?

2024-08-26 05:01 UTC, yodas7 commented
@poetrainy 
One comment remain unresolved.

2024-08-26 05:47 UTC, poetrainy commented on src/components/notification/daikin-notification.visual.test.ts
> +              __vrtDescription__: "Description of the notification",
@yodas7 
As you say, I've modified the test for Slot to be run in a separate suite, so this specification is no longer necessary.
I reverted the changes.

2024-08-26 06:00 UTC, yodas7 approved these changes
LGTM. Thanks!

2024-08-27 22:49 UTC, hiro-daikin commented
The changes look good to me. 
I just wonder if we should keep the `label by attribute`?
CC: @yodas7

2024-08-28 00:23 UTC, yodas7 commented
@hiro-daikin 
I don't have a strong opinion on this.
I think that everything that is displayed as content should be compatible with slots, but on the other hand, I'm not sure whether it should also be possible to specify it by attribute.
If we want simplicity in API design, I think it's fine to support slots only.

2024-08-28 00:26 UTC, yodas7 commented
@hiro-daikin 
There are similar issues with other components such as tooltips and accordions, so it might be a good idea to create a separate ticket to define a policy and unify things (slots and/or attributes).

2024-08-28 17:30 UTC, hiro-daikin commented
@yodas7 
I think:
- Use slots when the user needs more control over the content
- Use attributes for component configuration and simple values

In general, I think we should avoid providing both slots and attributes which control the same content. 
For this PR, what happens when a user uses both @poetrainy?

2024-08-30 01:18 UTC, poetrainy commented
@hiro-daikin @yodas7 
The `title` and `description` attributes have been removed, and the slot has been changed to accept them.

2024-08-30 02:33 UTC, yodas7 requested changes
The content of the notification must be able to be changed on Storybook.

2024-08-30 02:33 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
> +                <slot name="title">${this.title}</slot>
```suggestion
                <slot name="title"></slot>
```

2024-08-30 02:33 UTC, yodas7 commented on src/components/notification/stories/daikin-notification.stories.ts
> +    __vrtDescription__: "Notification-description: Toast",
```suggestion
    slotTitle: "Notification-title",
    slotDescription: "Notification-description: Toast",
```

2024-08-30 02:33 UTC, yodas7 commented on src/components/notification/stories/common.ts
>    },
```suggestion
  slotTitle: {
    type: "string",
    defaultValue: "Title text",
    description: "Content of the `title` slot.",
  },
  slotDescription: {
    type: "string",
    defaultValue: "Description text",
    description: "Content of the `description` slot.",
  },
```

2024-09-02 05:22 UTC, yodas7 commented on .changeset/old-clouds-type.md
> +**BREAKING CHANGE** Notification: The `title` and `description` attributes have been removed, and they are now received in the slot.
```suggestion
**BREAKING CHANGE** Notification: The `title` and `description` attributes have been removed, and their contents are now specified using slots with the same names.
```

2024-09-02 05:27 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
> +            class="flex justify-between items-center gap-5 p-5 text-[18px] flex-[1_0_auto]"
```suggestion
            class="flex justify-between items-center gap-5 p-5 text-lg flex-auto flex-shrink-0"
```

2024-09-03 05:19 UTC, yodas7 approved these changes
LGTM

2024-09-03 21:49 UTC, hiro-daikin commented on src/components/notification/daikin-notification.ts
> +              <header class="font-bold flex-none">
Do we need to add the `daikinSerif` to both header and slot?

2024-09-03 22:08 UTC, hiro-daikin commented on src/components/notification/daikin-notification.ts
> +              <div class="flex-none">
Should this be a `<p>` element?

2024-09-03 22:33 UTC, hiro-daikin commented
@poetrainy @yodas7 

I think we should consider adding `role="status"` for inline notifications, and `role="alert"` for toast messages.

https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/Roles/status_role
https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/Roles/alert_role

Shoelace uses the alert role for their toast alerts: https://shoelace.style/components/alert

2024-09-04 00:33 UTC, yodas7 commented on src/components/notification/daikin-notification.ts
> +              <div class="flex-none">
If we use `<p>` here, the elements that can be used inside will be restricted. For example, the user cannot use `<div>` element anymore.

2024-09-04 01:09 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +              <header class="font-bold flex-none">
I specify `daikinSerif` in `cvaContainer()`.

2024-09-04 01:26 UTC, poetrainy commented on src/components/notification/daikin-notification.ts
> +              <div class="flex-none">
I agree that <header> is inappropriate. However, because the fact that slots are allowed means that documents are no longer necessarily inserted, I would like to cover it with <div>.

2024-09-04 21:27 UTC, hiro-daikin commented on src/components/notification/daikin-notification.ts
> +              <div class="flex-none">
@yodas7 @poetrainy 

I see - It might be good for the user to be able to define the elements.
I think we can leave this as `div` then

2024-09-04 21:29 UTC, hiro-daikin approved these changes

2024-09-05 08:20 UTC, merged