fix: add document to breadcrumb component
dsv-rp/DDS pull request #52
Opened 2024-08-22 06:44 UTC by rinjInTokyo

add document to breadcrumb component

2024-08-22 07:02 UTC, yodas7 requested changes

2024-08-22 07:02 UTC, yodas7 commented on src/components/breadcrumb/daikin-breadcrumb.ts
> + * You can use breadcrumb component and breadcrumb-item component to display the current location within a hierarchy. And allow user going back to states higher up in the hierarchy.
When referring to components in a document, please use the format `daikin-*` to linkify it.

```suggestion
 * `daikin-breadcrumb` is a component for representing a breadcrumb list, and is used together with the `daikin-breadcrumb-item` component.
 *
 * Hierarchy:
 * - `daikin-breadcrumb` > `daikin-breadcrumb-item`
```

2024-08-22 07:22 UTC, yodas7 requested changes
The descriptions of some properties could be improved.

**daikin-breadcrumb**

> Specify overflow
> when visible the breadcrumb will not be omitted even breadcrumb-items total width exceed container width

```
Specifies overflow.
If `ellipsis`, some breadcrumb items will be omitted when the total width exceeds the container width.
```

> Specify whether the last of breadcrumb-item should show slash

```
Whether the last breadcrumb item should have trailing slash.
```

**daikin-breadcrumb-item**

> Specify the link should be hidden when ellipsis mode

```
Whether the link should be hidden when ellipsis mode.
Set automatically by `daikin-breadcrumb`.
```

> Specify the link should show slash at the end or not

```
Whether the link should have trailing slash.
Set automatically by `daikin-breadcrumb`.
```

> Specify link variant

```
Specifies the display content.
If `ellipsis`, the "..." will be displayed instead of the link.
Set automatically by `daikin-breadcrumb`.
```

2024-08-22 08:13 UTC, yodas7 requested changes

2024-08-22 08:13 UTC, yodas7 commented on src/components/breadcrumb-item/daikin-breadcrumb-item.ts
> +   * Whether the link should have trailing slash.
Sorry the slash is not in the link.

```suggestion
   * Whether the slash after the link should shown.
```

2024-08-22 08:33 UTC, yodas7 approved these changes
LGTM.

2024-08-23 01:44 UTC, ukkary approved these changes

2024-08-23 01:44 UTC, merged