DDS-1284 Retouching the button component
dsv-rp/DDS pull request #56
Opened 2024-08-23 07:28 UTC by poetrainy

The button component has been retouched.

2024-08-23 07:30 UTC, yodas7 commented
Does this supersedes #43?

2024-08-26 01:30 UTC, yodas7 requested changes
Commented on the contents of the changeset. The rest looks good.

2024-08-26 01:30 UTC, yodas7 commented on .changeset/long-radios-flash.md
> +add danger and tartiary design for button
```suggestion
**BREAKING CHANGE** Button: The `role` attribute/property is renamed to `button-role` attribute and `buttonRole` property to avoid conflicts with standard HTML attributes.
**BREAKING CHANGE** Button: The `size` attribute now accepts values of `"medium"` and `"small"`, instead of `"default"` and `"condensed"`.
**BREAKING CHANGE** Button: The `variant` attribute now accepts values of `"solid"`, `"outline"` and `"ghost"`, instead of `"primary"`, `"secondary"`, `"tertiary"` and `"primaryDanger"`.
Button: Added `color` attribute that accepts values of `"primary"` and `"danger"`.
Button: Updated appearance. (DDS-1284)
```

2024-08-26 04:57 UTC, yodas7 approved these changes
LGTM, but I think the specifications have not yet been finalized, so it might be better to leave the PR in draft status.

2024-08-29 22:32 UTC, hiro-daikin commented
@poetrainy It might be a good idea to use the template for pull requests. 
You can skip unnecessary parts if it doesn't apply

2024-08-29 22:34 UTC, hiro-daikin approved these changes

2024-08-30 08:10 UTC, merged