DDS-1350 [Radio] Retouching
dsv-rp/DDS pull request #61
Opened 2024-08-27 06:35 UTC by poetrainy

The radio component has been retouched.

2024-08-28 09:08 UTC, yodas7 requested changes
- It would be great if we can remove `readonly` property.
- Create a changeset file ([Example](https://github.com/dsv-rp/DDS/blob/cf16fed582d4660e06356dddb9b313715214176a/.changeset/long-radios-flash.md?plain=1))

2024-08-28 09:08 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +        class=${cvaRadio()}
We don't need CVA here, but there seems to be many classes for the element.
Maybe we should do like:

```
const RADIO_CLASSNAME = cva([ ... ])();
```

2024-08-28 09:08 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
>      },
```suggestion
    disabled: {
      false: [],
      true: ["text-daikinNeutral-200"],
    },
```

2024-08-29 01:13 UTC, poetrainy commented
@yodas7 
Should I also remove readonly from the Radio component?

2024-08-29 05:40 UTC, yodas7 commented
@poetrainy 
It is not in standard HTML, so it is better not to have it.

2024-08-29 06:22 UTC, poetrainy commented on src/components/radio/daikin-radio.ts
> +        right: [],
@yodas7 
The reason I added hidden to the checkbox was because that kind of use case occurred with the Table component. I don't think that kind of requirement exists for Radio yet, but should I add hidden to it as well at this stage?

2024-08-29 06:58 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +        right: [],
To be honest I'm not sure.
Even with the current implementation, the user can remove it by specifying an empty string for the `label`, so I feel that we should provide a more correct method than that.

2024-08-29 07:28 UTC, yodas7 requested changes

2024-08-29 07:28 UTC, yodas7 commented on .changeset/little-cameras-share.md
> +**BREAKING CHANGE** Radio: The `size` property has been removed and replaced with a standard size. (DDS-1350)
```suggestion
**BREAKING CHANGE** Radio: The `readonly` and `size` property has been removed. (DDS-1350)
```

2024-08-29 09:01 UTC, yodas7 requested changes

2024-08-29 09:01 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +    this.dispatchEvent(newEvent);
```suggestion
    this.checked = (event.target as HTMLInputElement).checked;
    this._updateFormValue();
    this.dispatchEvent(new Event("change", event));
```

2024-08-30 01:32 UTC, yodas7 commented on src/components/radio/daikin-radio.visual.test.ts
> +      // ensure that hovering or clicking does not change the image for disabled and readonly
```suggestion
      // ensure that hovering or clicking does not change the image for disabled
```

2024-08-30 01:34 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +   * when `left` the label will be in left of radio, when `right` label will be in right of radio.
```suggestion
   * - `right` (default): The label will be placed to the right of the radio button.
   * - `left`: The label will be placed to the left of the radio button.
   * - `hidden`: The label will not be shown.
```

2024-08-30 02:22 UTC, yodas7 requested changes

2024-08-30 02:22 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  "enabled:[&:not(:checked)]:active:before:bg-daikinNeutral-200",
```suggestion
  "enabled:[&:not(:checked)]:group-hover:before:bg-daikinNeutral-100",
  "enabled:[&:not(:checked)]:group-active:before:bg-daikinNeutral-200",
```

2024-08-30 02:22 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  "enabled:checked:active:border-daikinBlue-600",
```suggestion
  "enabled:checked:group-hover:border-daikinBlue-300",
  "enabled:checked:group-active:border-daikinBlue-600",
```

2024-08-30 02:22 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  ["flex", "gap-2", "items-center", "font-daikinSerif"],
```suggestion
  ["group", "flex", "gap-2", "items-center", "font-daikinSerif"],
```

2024-08-30 06:23 UTC, yodas7 approved these changes
LGTM

2024-09-18 07:54 UTC, yodas7 commented on .changeset/little-cameras-share.md
> +**BREAKING CHANGE** Radio: The `labelPosition` property has been removed `left` and added `hidden`. (DDS-1350)
```suggestion
**BREAKING CHANGE** Radio: The `labelPosition` property no longer supports `"left"`. Instead, it now supports `"hidden"`. (DDS-1350)
**BREAKING CHANGE** Radio: The `labelPosition` attribute (not property) has been renamed to `label-position`.
```

2024-09-18 07:54 UTC, yodas7 commented on .changeset/little-cameras-share.md
> +**BREAKING CHANGE** Radio: The `readonly`, `size` and `error` property has been removed. (DDS-1350)
nit.

```suggestion
**BREAKING CHANGE** Radio: The `readonly`, `size` and `error` properties have been removed. (DDS-1350)
```

2024-09-26 00:34 UTC, hiro-daikin approved these changes

2024-09-26 08:55 UTC, merged