DDS-1325 [Text Field] [Input Group] Retouching
dsv-rp/DDS pull request #62
Opened 2024-08-29 05:58 UTC by poetrainy

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1325](https://daikinsvoil.atlassian.net/browse/DDS-1325)

## Checklist

- [x] I have added a changeset file that describes the changes.
- [x] I have performed a self-review of my code.
- [x] I have added/updated appropriate regression tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.
- [x] I have confirmed that the bug fix does not affect the keyboard accessibility of the component.
- [x] I have confirmed that the fix does not introduce any new visual regressions.

[DDS-1325]: https://daikinsvoil.atlassian.net/browse/DDS-1325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-02 03:07 UTC, yodas7 requested changes

2024-09-02 03:07 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
>      variant: {
nit: use "true" and "false".

2024-09-02 03:07 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +      required: ["after:i-daikin-required", "after:size-4", "after:ml-1"],
nit: use "true" and "false".

2024-09-02 03:07 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      },
nit.

```suggestion
      disabled: {
        false: [],
        true: ["text-[--text-input-outline-color-disabled]"],
      },
```

2024-09-02 03:07 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      },
nit.

```suggestion
      error: {
        false: ["border-daikinNeutral-600"],
        true: ["border-[--text-input-border-color-error]"],
      },
```

2024-09-02 05:34 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +    "enabled:hover:outline-offset-[-2px]",
nit.

```suggestion
    "enabled:hover:-outline-offset-2",
```

2024-09-02 05:34 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +    "enabled:active:outline-offset-[-2px]",
nit.

```suggestion
    "enabled:active:-outline-offset-2",
```

2024-09-02 05:34 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +    "enabled:focus-visible:outline-offset-[-2px]",
nit.

```suggestion
    "enabled:focus-visible:-outline-offset-2",
```

2024-09-02 05:34 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +        right: ["pl-3", "pr-[44px]"],
nit.

```suggestion
        left: ["pl-11", "pr-3"],
        right: ["pl-3", "pr-11"],
```

2024-09-02 05:34 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      : input;
For simplicity, I think it's okay to always have a div.

2024-09-03 05:17 UTC, yodas7 commented on src/components/text-input/stories/framework-wc.ts
> +        .rightIcon=${rightIcon}
Use attributes to ensure Storybook generates correct code.

2024-09-03 05:17 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      </div>`;
nit.

```suggestion
    const createIcon = (position: "left" | "right", icon: IconType | null) =>
      icon ? html`<div
        class=${cvaIconContainer({
          disabled: this.disabled,
          position,
        })}
      >
        <daikin-icon icon=${icon} size="m" color="current"></daikin-icon>
      </div>` : nothing;
```

2024-09-03 05:17 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      : input;
nit.

```suggestion
    return html`<div class="w-full h-full relative">
        ${createIcon("left", this.leftIcon)}
        ${input}
        ${createIcon("right", this.rightIcon)}
      </div>`;
```

2024-09-03 05:17 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +        icon: this.leftIcon ? "left" : this.rightIcon ? "right" : "none",
It looks like it doesn't work when both icons are specified.

2024-09-03 05:17 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +      },
```suggestion
      leftIcon: {
        false: ["pl-3"],
        true: ["pl-11"],
      },
      rightIcon: {
        false: ["pr-3"],
        true: ["pr-11"],
      },
```

2024-09-03 06:52 UTC, poetrainy commented on src/components/text-input/daikin-text-input.ts
> +    "z-[1]",
I confirmed that it was okay to delete the last line, so I made the correction.

2024-09-03 08:16 UTC, yodas7 approved these changes
LGTM. Thanks!

2024-09-11 05:32 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +        aria-required=${this.required}
I think we should use `required` attr.

```suggestion
        ?required=${this.required}
```

2024-09-18 07:22 UTC, yodas7 requested changes
Add a changeset file.

2024-09-18 07:47 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +        aria-required=${this.required}
@poetrainy 
Doesn't seem to be fixed.

Please add a reaction after the change has actually been made. Or, if you think that this change is not suitable, please leave a comment.

2024-09-18 08:29 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> +        </div>
@yodas7 
I have prepared a space for the error message to be read out in advance. For example, even if nothing is displayed here, a gap will be created because it will remain as a space. Therefore, I covered it with margin.

2024-09-19 00:36 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +        </div>
@poetrainy 
Is there a problem with setting the wrapper `<div>` to `display: none`?

2024-09-19 02:18 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +        </div>
Can't we do like following?

```suggestion
        <div
          class=${cvaHelper({
            type: helperType, /* "helper" | "helperDisabled" | "error" | "none" */
          })}
          aria-live=${helperType === "error" ? "polite" : nothing}
        >
          ${helperText}
        </div>
```

2024-09-20 01:03 UTC, yodas7 reviewed
I think it's improved a lot.

2024-09-20 01:03 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +      !this.disabled && !!this.error.length
nit.

```suggestion
      this.error && !this.disabled
```

2024-09-20 01:03 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +        <div
We cannot use `<div>` inside `<label>`

```suggestion
        <span
```

2024-09-20 01:14 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +        </span>
Maybe we should add a [sr-only](https://tailwindcss.com/docs/screen-readers) element.

```suggestion
        </span>
        ${this.required ? html`<span class="sr-only">(required)</span>` : nothing}
```

2024-09-20 02:14 UTC, yodas7 approved these changes
Thanks

2024-09-24 06:26 UTC, yodas7 commented
I've made some changes to use CSS variables for prioritization, but I'm not sure if this will be useful.
I'll review it tomorrow, so please wait a while.

2024-10-03 20:58 UTC, hiro-daikin commented
I don't see a changelog

2024-10-03 21:11 UTC, hiro-daikin requested changes
Please create the change log

2024-10-04 01:07 UTC, poetrainy commented
@hiro-daikin 
Thank you for pointing this out. It has been added.

2024-10-04 16:48 UTC, hiro-daikin commented on src/components/input-group/daikin-input-group.ts
> +import "../icon/daikin-icon";
This imports all icons, including ones that the user may not user, correct?

Consider this approach where they use `slots`: https://shoelace.style/components/button#prefix-and-suffix-icons

The benefit of this approach:
- Only the specified icon gets used/loaded
- If DDS icons are not sufficient, the user can use their own icon

We may eventually have to reconsider our icon strategy as a whole.
I think we've taken the approach of - "You can only use DDS-approved icons".
But in reality, we currently have limited icons and that may not be sufficient for most users. 

cc: @yodas7

2024-10-04 16:50 UTC, hiro-daikin requested changes

2024-10-04 16:50 UTC, hiro-daikin commented on src/components/text-input/daikin-text-input.ts
> +import "../icon/daikin-icon";
Same comment as above

2024-10-10 07:12 UTC, poetrainy commented on src/components/input-group/daikin-input-group.ts
> +import "../icon/daikin-icon";
@hiro-daikin 
The icons have been modified so that they are introduced from the slot.
There are several other components that specify icons by attribute, so we will also support these.

2024-10-11 19:18 UTC, hiro-daikin approved these changes

2024-10-21 06:52 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +        style=${`--input-padding-left:${this._hasLeftIcon ? "44px" : "16px"}; --input-padding-right:${this._hasRightIcon ? "44px" : "16px"};`}
Maybe we should do this with `cvaInput`

2024-10-21 06:52 UTC, yodas7 commented on src/components/text-input/daikin-text-input.ts
> +          @slotchange=${(event: Event) => this._handleSlotChange(event, "left")}
Actually we can simplify this as following since we can obtain slot name (`left-icon` or `right-icon`) with `(event.target as HTMLSlotElement).name`.

```suggestion
          @slotchange=${this._handleSlotChange}
```

2024-10-23 05:36 UTC, yodas7 approved these changes
LGTM

2024-10-30 02:35 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  required = "";
If you set `reflect: true` and use an empty string as the default, it will probably add the attribute and cause confusion.

```suggestion
  @property({ type: String, reflect: true })
  required: string | null = null;
```

2024-10-30 02:35 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +   * Reflected in `required` attribute of the input control in the slot.
```suggestion
   * Text indicating that the field is required.
   * If a non-empty string is set,
   * - the text will be displayed in red to the right of the label, and
   * - the `required` attribute will be set for the input control in the slot.
   * Ignored if `disabled` is `true`.
```

2024-10-30 02:35 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  error = "";
```suggestion
  error: string | null = null;
```

2024-10-30 02:35 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  helper = "";
```suggestion
  helper: string | null = null;
```

2024-10-30 02:35 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  label = "";
```suggestion
  label: string | null = null;
```

2024-10-30 02:48 UTC, yodas7 approved these changes

2024-10-30 02:57 UTC, merged