DDS-1327 [Textarea] Retouching
dsv-rp/DDS pull request #64
Opened 2024-09-02 07:08 UTC by poetrainy

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1327](https://daikinsvoil.atlassian.net/browse/DDS-1327)

## Checklist

- [x] I have added a changeset file that describes the changes.
- [x] I have performed a self-review of my code.
- [x] I have added/updated appropriate regression tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.
- [x] I have confirmed that the bug fix does not affect the keyboard accessibility of the component.
- [x] I have confirmed that the fix does not introduce any new visual regressions.

2024-09-03 04:57 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +        true: [],
nit.

```suggestion
        true: ["resize-vertical"],
```

2024-09-03 04:57 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +  allowResize = false;
nit.

```suggestion
  resizable = false;
```

2024-09-03 04:57 UTC, yodas7 commented on .changeset/ten-items-peel.md
> +Textarea: The `allowResize` attribute has been added. (DDS-1327)
```suggestion
Textarea: The `allowResize` and `error` attribute has been added. (DDS-1327)
```

2024-09-03 04:57 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  _isTextarea: boolean = false;
nit.

```suggestion
  _hasTextarea: boolean = false;
```

2024-09-03 04:57 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +            : null}
nit.

```suggestion
            : nothing}
```

2024-09-03 06:18 UTC, yodas7 commented on .changeset/ten-items-peel.md
> +Textarea: The `resizable` and `error` attribute has been added. (DDS-1327)
```suggestion
Textarea: The `resizable` and `error` attributes has been added. (DDS-1327)
```

2024-09-03 06:18 UTC, yodas7 approved these changes
LGTM.

2024-09-03 06:20 UTC, yodas7 requested changes

2024-09-03 06:20 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +    onChangeCount: fn(eventPayloadTransformer),
Add tests for this event.

2024-09-03 07:57 UTC, poetrainy commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +    onChangeCount: fn(eventPayloadTransformer),
@yodas7 
I've added a test for the textarea counter on the Input Group side, but is that not enough?

2024-09-03 08:15 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +    onChangeCount: fn(eventPayloadTransformer),
Yes, the component events also need to be tested individually.
Integration testing is required separately, so please leave that as well.

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +          valueCount: this.value.length,
```suggestion
          count: this.value.length,
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/stories/common.ts
> +  onChangeCount: (event: Event & { detail: { valueCount: number } }) => void;
```suggestion
  onChangeCount: (event: Event & { detail: { count: number } }) => void;
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +  event: Event & { detail: { valueCount: number } }
```suggestion
  event: Event & { detail: { count: number } }
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +  };
```suggestion
  return event.detail;
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +function eventPayloadTransformerForOnChangeInput(
```suggestion
function eventPayloadTransformerDetail(
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +    onChangeCount: fn(eventPayloadTransformerForOnChangeInput),
```suggestion
    onChangeCount: fn(eventPayloadTransformerDetail),
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +      await expect(args.onChangeCount).toHaveLastReturnedWith({ value: 7 });
```suggestion
      await expect(args.onChangeCount).toHaveLastReturnedWith({ count: 7 });
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/textarea/stories/framework-react.tsx
> +      Event & { detail: { valueCount: number } }
```suggestion
      Event & { detail: { count: number } }
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    e: Event & { detail: { valueCount: number } }
```suggestion
    e: Event & { detail: { count: number } }
```

2024-09-04 03:21 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    this._textareaValueLength = e.detail.valueCount;
```suggestion
    this._textareaValueLength = e.detail.count;
```

2024-09-04 03:22 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +  // We need to retrieve `event.target.checked` inside the event listeners not to miss problems caused by the timing of acquisition.
```suggestion
```

2024-09-04 03:32 UTC, yodas7 approved these changes
LGTM

2024-09-11 05:31 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +      aria-required=${this.required}
I think we should use `required` attribute.

```suggestion
      ?required=${this.required}
```

2024-09-18 07:28 UTC, yodas7 requested changes

2024-09-18 07:28 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  @property({ type: Number, reflect: true })
```suggestion
  @property({ type: Number, reflect: true, attribute: "textarea-max-count" })
```

2024-09-18 07:28 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  _textareaValueLength: number = 0;
nit.

```suggestion
  @state()
  _hasTextarea = false;

  @state()
  _textareaValueLength = 0;
```

2024-09-18 07:28 UTC, yodas7 commented on src/components/input-group/stories/framework-wc.ts
> +        textareaMaxCount=${ifDefined(textareaMaxCount)}
```suggestion
        textarea-max-count=${ifDefined(textareaMaxCount)}
```

2024-09-18 07:28 UTC, yodas7 commented on src/components/textarea/stories/common.ts
> +  onChangeCount: (event: Event & { detail: { count: number } }) => void;
```suggestion
  onChangeCount: (event: CustomEvent<{ count: number }>) => void;
```

2024-09-18 07:28 UTC, yodas7 commented on src/components/textarea/stories/daikin-textarea.stories.ts
> +  event: Event & { detail: { count: number } }
```suggestion
  event: CustomEvent<{ count: number }>
```

2024-09-18 07:28 UTC, yodas7 commented on src/components/textarea/stories/framework-react.tsx
> +      Event & { detail: { count: number } }
```suggestion
      CustomEvent<{ count: number }>
```

2024-09-18 07:28 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    this._textareaValueLength = e.detail.count;
```suggestion
  private _handleChangeCount(event: CustomEvent<{ count: number }>): void {
    this._textareaValueLength = event.detail.count;
```

2024-09-18 08:56 UTC, poetrainy commented
I'm investigating this issue because changing the type definition causes unrelated files to fail the test.

2024-09-20 01:05 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +    "outline-transparent",
The meaning is slightly different between a transparent outline and a 0px outline, and I think a 0px outline is safer.

2024-09-20 02:20 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +    "outline-transparent",
```suggestion
```

2024-09-20 04:49 UTC, yodas7 approved these changes

2024-09-20 05:55 UTC, poetrainy commented on src/components/textarea/daikin-textarea.ts
> +    "outline-transparent",
If this line is not present, the outline will be represented in black.

2024-09-20 06:51 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +    "outline-transparent",
@poetrainy 
I checked, but that did not occur.
Also, on a different note, I feel that the display is strange when focus + hover.

2024-09-20 08:00 UTC, poetrainy commented on src/components/textarea/daikin-textarea.ts
> +    "outline-transparent",
What does it mean to be strange?

2024-09-26 00:35 UTC, yodas7 commented on src/components/textarea/daikin-textarea.ts
> +    "outline-transparent",
Did conversation and resolved.

2024-10-04 02:04 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +  _textareaValueLength = 0;
Let's combine the states into one.
```suggestion
  @state()
  private _textareaValueLength: number | null = null;
```

2024-10-04 02:04 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
>    _textareas!: DaikinTextarea[];
```suggestion
  private _textareas!: DaikinTextarea[];
```

2024-10-04 02:04 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
>    _controls!: ControlElement[];
```suggestion
  private _controls!: ControlElement[];
```

2024-10-04 02:04 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    }
```suggestion
    this._textareaValueLength = textarea?.value.length ?? null;
```

2024-10-04 02:04 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +          ${!!this.textareaMaxCount && !!this._hasTextarea
```suggestion
          ${this.textareaMaxCount != null && _textareaValueLength != null
```

2024-10-07 04:56 UTC, yodas7 approved these changes

2024-10-11 19:43 UTC, hiro-daikin approved these changes

2024-10-24 08:58 UTC, yodas7 approved these changes

2024-10-30 04:39 UTC, yodas7 commented on .changeset/ten-items-peel.md
> +**BREAKING CHANGE** Text Area: Renamed Textarea to Text Area. (DDS-1327)
```suggestion
**BREAKING CHANGE** Text Area: Renamed Textarea (`daikin-textarea`) to Text Area (`daikin-text-area`). (DDS-1327)
```

2024-10-30 04:39 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> + * The input group component serves as a wrapper for a `daikin-text-field` or `daikin-text-area` component, providing additional elements such as labels, helper texts, or a counter.
better to sort.

```suggestion
 * The input group component serves as a wrapper for a `daikin-text-area` or `daikin-text-field` component, providing additional elements such as labels, helper texts, or a counter.
```

2024-10-30 04:39 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
>   * - `daikin-input-group` > `daikin-text-field`
same.

```suggestion
 * - `daikin-input-group` > `daikin-text-area`
 * - `daikin-input-group` > `daikin-text-field`
```

2024-10-30 04:39 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> + * @slot - A slot for a input component. Place a `daikin-text-field` or `daikin-text-area` element here.
```suggestion
 * @slot - A slot for a input component. Place a `daikin-text-area` or `daikin-text-field` element here.
```

2024-10-30 04:39 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
>   * import "@daikin-oss/design-system-web-components/components/text-field/index.js";
```suggestion
 * import "@daikin-oss/design-system-web-components/components/text-area/index.js";
 * import "@daikin-oss/design-system-web-components/components/text-field/index.js";
```

2024-10-30 04:39 UTC, yodas7 commented on src/components/text-area/daikin-text-area.ts
> +  value = "";
`value` should not reflect. (same applies to text field.)

```suggestion
  @property({ type: String })
  value = "";
```

2024-10-30 04:39 UTC, yodas7 commented on src/components/text-area/daikin-text-area.ts
> +  placeholder = "";
```suggestion
  placeholder: string | null = null;
```

2024-10-30 08:02 UTC, yodas7 commented on src/components/text-area/daikin-text-area.ts
> +  value = "";
@poetrainy 
Could you update `daikin-text-field.ts` as well?

2024-10-30 08:02 UTC, yodas7 commented on src/components/text-area/daikin-text-area.ts
> +  placeholder = "";
@poetrainy 
Could you update `daikin-text-field.ts` as well?

2024-10-31 01:41 UTC, yodas7 commented on src/components/text-area/daikin-text-area.ts
> +  resizable = false;
Let's move the counting into a getter so that we can move to a more accurate logic than `value.length` in the future.

```suggestion
  resizable = false;

  get count(): number {
    return this.value.length;
  }
```

2024-10-31 01:43 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    this._textareaValueLength = textarea?.value.length ?? null;
```suggestion
    const textarea = this._textareas[0] as DaikinTextArea | undefined;
    this._textareaValueLength = textarea?.count ?? null;
```

2024-10-31 01:44 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +          @change-count=${this._handleChangeCount}
```suggestion
          @input=${this._handleInput}
```

2024-10-31 01:45 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +    this._textareaValueLength = e.detail.count;
```suggestion
  private _handleInput(event: Event): void {
    // Update counter if emitted by textarea.
    if ((event.target as HTMLElement).tagName === "DAIKIN-TEXTAREA") {
      this._textareaValueLength = (event.target as DaikinTextArea).count;
    }
```

2024-10-31 04:42 UTC, yodas7 approved these changes

2024-10-31 06:25 UTC, merged