DDS-1361 Add radio group component
dsv-rp/DDS pull request #65
Opened 2024-09-03 00:19 UTC by rinjInTokyo

This PR adds Radio Group (`daikin-radio-group`) component.

## Related Ticket(s) and Links

- JIRA Ticket: 
- Figma design: 

## API Design

- [JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3019341872/Button+Component+API)

## How Has This Been Tested?

### Visual Regression Tests

- \[horizontal; vertical;\] variants and \[Normal; Disabled\] states matrix.

### Interaction Tests

- fires `change` event when the radio be changed
- does not fire `change` event if the radio group is disabled
- click the radio will change radio group value

## Checklist

- [x] I have added a changeset file that describes the changes.  
       _Hint_: run `npx changeset`.
- [x] I have performed a self-review of my code.
- [x] I have added appropriate visual regression tests.
- [x] I have added appropriate interaction tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.  
       _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the component can be operated using only the keyboard.
- [x] I have confirmed that the focus state of the component is visually discernible.

If you don't feel that the PR is ready for review, please create the PR in draft status.

2024-09-11 05:34 UTC, yodas7 requested changes

2024-09-11 05:34 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      ${this.label ? html` <span class="">${this.label}</span>` : ""}
```suggestion
      ${this.label ? html`<span>${this.label}</span>` : nothing}
```

2024-09-13 06:19 UTC, rinjInTokyo commented on src/components/radio-group/daikin-radio-group.ts
> +  name = "";
Refactor name property. And user can use this property to set child radio button's name quickly.

2024-10-23 05:43 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +  private _updateRadios(value: string, name: string) {
value and name should always reference `this.value` and `this.name`.

```suggestion
  private _updateRadios() {
```

2024-10-23 05:43 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    this._updateRadios((event.target as HTMLInputElement).value, this.name);
```suggestion
    this.value = (event.target as HTMLInputElement).value;
```

`_updateRadios()` will be done by `updated()` if we set `this.value`.

2024-10-23 05:43 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    this._updateRadios(this.value, this.name);
```suggestion
    this._updateRadios();
```

2024-10-23 05:43 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      this._updateRadios(this.value, this.name);
```suggestion
      this._updateRadios();
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      nextRadioInput?.focus();
Implement focus delegation to `daikin-radio` component.


```suggestion
      nextRadio.focus();
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +        (focusedRadioIndex + moveOffset * i + radios.length * i) %
```suggestion
        (focusedRadioIndex + moveOffset * i + radios.length) %
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      daikinRadio.skipTab = !isSelected;
```suggestion
      // If none of the radio buttons are selected, the first radio button can be focused.
      daikinRadio.skipTab = selectedRadio ? !isSelected : daikinRadio !== firstEnabledRadio;
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      daikinRadio.internals.setFormValue(isSelected ? daikinRadio.value : null);
I think it's handled by `updated()` in the `daikin-radio` component.

```suggestion
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    return html`<fieldset @keydown=${this._handleKeyDown}>
```suggestion
    return html`<fieldset role="radiogroup" @keydown=${this._handleKeyDown}>
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  public internals = this.attachInternals();
Internals should not be public.

```suggestion
  private _internals = this.attachInternals();
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +    this.dispatchEvent(newEvent);
nit.

```suggestion
    this.dispatchEvent(new Event("change", {
      bubbles: true,
      composed: true,
      cancelable: true,
    }));
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +          tabindex=${this.skipTab ? "-1" : "0"}
Maybe we don't want to set `tabindex="0"` as it's default.

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      );
I don't understand what the correct behavior should be here.
Is it possible to receive a key event when the focus is not on the element in the first place?
For now, let's give priority to the checked radio and, if that's not the case, let's say it's the first enabled radio.

```suggestion
      const activeRadio = radios.find((radio) => radio.checked) ?? radios.find((radio) => !radio.disabled);
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      event.preventDefault();
```suggestion
      if (activeRadio) {
        activeRadio.checked = true;
        activeRadio.focus();
        event.preventDefault();
      }
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    for (const [, daikinRadio] of this._radios.entries()) {
```suggestion
    for (const daikinRadio of this._radios) {
```

2024-10-25 08:59 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    const selectedRadio = radios.find((radio) => radio.value === this.value);
```suggestion
    const selectedRadio = radios.find((radio) => radio.value === this.value);
    const firstEnabledRadio = radios.find((radio) => !radio.disabled);
```

2024-10-29 01:56 UTC, rinjInTokyo commented on src/components/radio-group/daikin-radio-group.ts
> +    for (const [, daikinRadio] of this._radios.entries()) {
Get the index and then use the index to check if it's the first element.

2024-10-29 05:18 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +  @property({ type: Boolean, reflect: true })
```suggestion
  @property({ type: Boolean, attribute: null })
```

2024-10-29 05:18 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +   * Whether the radio button can be focused.
```suggestion
   * Whether the radio button can be focused.
   * Automatically set by `daikin-radio-group` component.
```

2024-10-29 05:18 UTC, yodas7 commented on src/components/radio-group/stories/framework-react.tsx
> +      required={true}
nit.

```suggestion
      label="Label text"
      helper="Helper text"
      required
```

2024-10-29 05:18 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      }
I don't think we need this warning message.

```suggestion
```

2024-10-29 05:18 UTC, yodas7 commented on .changeset/cold-phones-lie.md
> +Add radio group component
```suggestion
Add radio group component. (DDS-1361)
```

2024-10-29 09:28 UTC, yodas7 requested changes
Please check failing tests

2024-10-31 04:53 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
We cannot use `<div>` in `<label>`.
https://developer.mozilla.org/ja/docs/Web/HTML/Element/label#technical_summary

Could you change it to `<span>`?
Also, please update `daikin-checkbox.ts` as well

2024-10-31 04:53 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +
nit.

```suggestion
```

2024-10-31 04:53 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> + * </daikin-radio-group>
nit.

```suggestion
 * <daikin-radio-group name="name">
 *   <daikin-radio value="value1" label="Option1"></daikin-radio>
 *   <daikin-radio value="value2" label="Option2"></daikin-radio>
 *   <daikin-radio value="value3" label="Option3"></daikin-radio>
 * </daikin-radio-group>
```

2024-10-31 04:53 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> + * </daikin-input-group>
```suggestion
 * <daikin-input-group label="Label text" helper="Helper text">
 *   <daikin-radio-group name="name">
 *     <daikin-radio value="value1" label="Option1"></daikin-radio>
 *     <daikin-radio value="value2" label="Option2"></daikin-radio>
 *     <daikin-radio value="value3" label="Option3"></daikin-radio>
 *   </daikin-radio-group>
 * </daikin-input-group>
```

2024-10-31 05:25 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +
I think we should call `event.preventDefault();` here.

2024-10-31 05:33 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    const radios = this._radios;
```suggestion
    const enabledRadios = this._radios.filter(({ disabled }) => !disabled);
```

2024-10-31 05:33 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    if (!radios.some((radio) => !radio.disabled)) {
```suggestion
    if (!enabledRadios.length) {
```

2024-10-31 05:33 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      ? radios.findIndex((radio) => radio.contains(activeElement))
```suggestion
      ? enabledRadios.findIndex((radio) => radio.contains(activeElement))
```

2024-10-31 05:33 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +        radios.find((radio) => !radio.disabled);
```suggestion
        enabledRadios.find((radio) => radio.checked) ??
        enabledRadios[0];
```

2024-10-31 05:33 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +    }
```suggestion
    // If there is a radio focused, move focus forward or backward
    const newIndex = (focusedRadioIndex + moveOffset + radios.length) % radios.length;
    if (newIndex !== focusedRadioIndex) {
      const newRadio = enabledRadios[newIndex];
      this.value = newRadio.value;
      newRadio.focus();
      this.dispatchEvent(new Event("change"));
    }
```

2024-10-31 05:33 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +        event.preventDefault();
```suggestion
        this.value = activeRadio.value;
        activeRadio.focus();
```

2024-10-31 05:36 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +      }
```suggestion
      this.value = activeRadio.value;
      activeRadio.focus();
```

2024-10-31 06:28 UTC, yodas7 approved these changes
Thanks!

2024-10-31 06:31 UTC, yodas7 commented
@rinjInTokyo 
Resolve conflicts please.

2024-11-01 00:33 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
>   * @slot - A slot for a input component. Place a `daikin-text-area` or `daikin-text-field` element here.
```suggestion
 * @slot - A slot for an input component. See **Hierarchies** for supported component.
```

2024-11-05 08:00 UTC, yodas7 commented on src/components/input-group/daikin-input-group.ts
> +      control.reflectInputGroup(this);
It would be preferable if there were no conditional branches here.
Can we add support for these to radio-group?

2024-11-05 21:51 UTC, hiro-daikin approved these changes

2024-11-06 05:20 UTC, yodas7 commented on src/components/radio/daikin-radio.ts
> +        cancelable: true,
Had a conversation. The native `change` event is not cancelable so we don't have to make this event cancelable.

2024-11-06 05:21 UTC, yodas7 commented on src/components/radio-group/daikin-radio-group.ts
> +  private _label: string | null = null;
Sorry we should use `@state` for this purpose.

2024-11-06 08:01 UTC, yodas7 approved these changes

2024-11-07 01:32 UTC, merged