DDS-1414 [Accordion] Retouching
dsv-rp/DDS pull request #69
Opened 2024-09-17 03:17 UTC by poetrainy

2024-09-17 06:31 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +      class="flex w-full h-max bg-white font-daikinSerif overflow-clip"
Do we need `h-max`? Should it be `h-full`?

2024-09-17 06:33 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +          ></daikin-icon>
I don't think we have to use `daikin-icon` in components if it does not have alt text or interacitons. Just using `i-daikin-*` looks simpler.

2024-09-17 06:35 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
>            "hover:cursor-pointer",
```suggestion
          "cursor-pointer",
```

2024-09-17 06:35 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +        true: ["text-daikinNeutral-200", "[&>*]:text-daikinNeutral-200"],
TailwindCSS has `*:text-daikinNeutral-200` notation.
BTW is it necessary? I thought it to be inherited.

```suggestion
        true: ["text-daikinNeutral-200"],
```

2024-09-18 02:56 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +    return html`<div class="w-full border-y-[1px] border-y-daikinNeutral-600">
nit.

```suggestion
    return html`<div class="w-full border-y border-y-daikinNeutral-600">
```

2024-09-18 05:22 UTC, yodas7 requested changes
When the `<details>` element is opened using the in-page search, the accordion behaves strangely.

2024-09-18 05:53 UTC, poetrainy commented
@yodas7 
Should we delete `disabled`?

2024-09-18 06:01 UTC, yodas7 commented
@poetrainy 
Yes, if it's okay to delete it, it would be better to delete it. However, I don't know who has the authority to make the decision.

2024-09-18 06:20 UTC, yodas7 commented
@poetrainy 
Please note that the problem mentioned above occurs regardless of whether the `disabled` is set or not.

2024-09-18 08:05 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    }
```suggestion
    this.open = event.newState === "open";
```

2024-09-18 08:08 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    }
Also, add a comment that describes why we need this.
e.g.
```
When using the in-page search, the `<details>` element may open without clicking on the `<summary>`. In order to handle such cases, it is necessary to respond to the "toggle" event.
```

2024-09-18 08:12 UTC, yodas7 commented
The display will be strange for a moment.
Instead of listening for `"toggle"`, maybe we should listen for `"beforetoggle"`, and call `preventDefault()` as well as updating `this.open`.

2024-09-18 08:55 UTC, poetrainy commented
@yodas7 
Since it did not work properly in the case of `beforetoggle`, I only added `event.preventDefault()`.

2024-09-19 00:44 UTC, yodas7 reviewed
Looks good, thanks.
I'll review it again once we have decided whether to delete the disabled.

2024-09-20 07:52 UTC, yodas7 requested changes
Please change `title` property of the `daikin-accordion-item` to something else (e.g. `heading`) as it conflicts with standard HTML attribute/property.

2024-09-20 07:52 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +      display: none;
Maybe we should use CSS variable for clarity:

```suggestion
      display: var(--divider-top-display, none);
```

2024-09-20 07:52 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +      display: none;
```suggestion
      display: var(--divider-bottom-display, none);
```

2024-09-20 07:52 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
>      }
```suggestion
    ::slotted(daikin-accordion-item:last-child) {
      --divider-bottom-display: block;
    }
```

2024-09-20 07:52 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
>        display: block;
```suggestion
    ::slotted(daikin-accordion-item) {
      --divider-top-display: block;
      --divider-bottom-display: none;
    }
```

2024-09-20 08:39 UTC, yodas7 approved these changes

2024-10-03 01:18 UTC, yodas7 requested changes

2024-10-03 01:18 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +        ${this.heading}
We should use named slot.

2024-10-03 01:18 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +    return html`<div class="w-full min-w-40">
We should not specify min width inside component.

2024-10-04 02:34 UTC, yodas7 requested changes

2024-10-04 02:34 UTC, yodas7 commented on .changeset/hot-pumpkins-visit.md
> +**BREAKING CHANGE** Accordion: The `title` attribute is renamed to `heading`.
This is outdated.

2024-10-04 02:34 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> + *   <span slot="Accordion summary">
```suggestion
 *   <span slot="summary">Accordion summary</span>
```

2024-10-04 02:34 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> + *     <span slot="Accordion summary 1">
```suggestion
 *     <span slot="summary">Accordion summary 1</span>
```

2024-10-04 02:34 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> + *     <span slot="Accordion summary 2">
```suggestion
 *     <span slot="summary">Accordion summary 2</span>
```

2024-10-04 02:34 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> + *     <span slot="Accordion summary 3">
```suggestion
 *     <span slot="summary">Accordion summary 3</span>
```

2024-10-09 07:33 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    this.shadowRoot?.querySelector("summary")?.focus(options);
We may want to use `@query`.

2024-10-09 07:33 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +  }
Not sure if we have to handle keyboard interactions.

2024-10-09 07:43 UTC, poetrainy commented on src/components/accordion/daikin-accordion.ts
> +  }
@yodas7 
Here is what I used as a reference: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

2024-10-09 07:50 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +  }
Had conversation. We don't have to handle (Shift+) Tab keys.

2024-10-11 06:16 UTC, yodas7 requested changes

2024-10-11 06:16 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +    return html`<div class="w-full" @keydown=${this._handleKeyDown}>
This handler will also be called when the focus is on the controls inside the accordion, so please move the event handler to the summary button of the accordion item.

2024-10-11 08:26 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +  }
- Use loop rather than recursion
- Prevent infinite loop
- Make the name and signature of the custom event more easy to understand

```suggestion
  private _handleMoveFocus(event: CustomEvent<{ direction: "up" | "down" }>): void {
    const moveOffset = event.detail.direction === "up" ? -1 : 1;
    const items = this._items;

    // Get focused item if any
    const activeElement = document.activeElement;
    const focusedItemIndex = activeElement
      ? items.findIndex((item) => item === activeElement)
      : -1;
      
    // If there is no accordion focused, do nothing.
    if (focusedItemIndex < 0) {
      return;
    }

    // Focus on the first accordion that is enabled.
    for (let index = focusedItemIndex + moveOffset, i = 0; i < items.length; index += moveOffset, i++) {
      index %= items.length;

      const item = items[index];
      if (item.disabled) {
        continue;
      }

      item.focus();
      break;
    }
  }
```

2024-10-11 08:26 UTC, yodas7 commented on src/components/accordion/daikin-accordion.ts
> +      <slot @summary-keydown=${this._handleKeyDown}></slot>
```suggestion
      <slot @accordion-move-focus=${this._handleMoveFocus}></slot>
```

2024-10-11 08:26 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +      })
```suggestion
      new CustomEvent("accordion-move-focus", {
        detail: {
          direction,
        },
        bubbles: true,
      })
```

2024-10-11 08:26 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    )[event.key];
```suggestion
    const direction = (
      {
        ArrowDown: "down",
        ArrowUp: "up",
      } as const
    )[event.key];
```

2024-10-11 08:26 UTC, yodas7 commented on src/components/accordion-item/daikin-accordion-item.ts
> +    if (!moveOffset) {
```suggestion
    if (!direction) {
```

2024-10-17 02:33 UTC, yodas7 approved these changes

2024-10-17 23:24 UTC, hiro-daikin approved these changes

2024-10-22 09:01 UTC, merged