DDS-1020 Add Tab Component
dsv-rp/DDS pull request #7
Opened 2024-06-25 02:56 UTC by yodas7

This PR adds Navigation Tab (`daikin-tab` and `daikin-tab-group`) component.

Draft status as interaction tests are missing.

## Related Issue(s) and Links

- JIRA Ticket (parent): [DDS-1020](https://daikinsvoil.atlassian.net/browse/DDS-1020)

## API Design

- [JIRA Wiki for Tab Component](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3018686539/Tab+Component+API)
- [JIRA Wiki for Tab Group Component](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3042738180/Tab+Group+Component+API)

## How Has This Been Tested?

- VRT (Visual Regression Test) for \[Default; Condensed\] size variants and \[Normal; Hover; Pressed; Disabled\] states matrix.

More tests coming...

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added appropriate VRTs.
- [ ] I have added appropriate interaction tests.
- [x] I have confirmed that my changes do not generate new warnings and errors.

2024-06-25 08:00 UTC, yodas7 commented
CI is failing due to text rendering.
Since we are using an M1 machine, a GitHub Actions M1 runner may solve the problem, but this always seems to be paid for.
I'll try setting `text-rendering`.

2024-06-27 09:22 UTC, KoharaKazuya requested changes

2024-06-27 09:22 UTC, KoharaKazuya commented on src/components/tab/daikin-tab-group.ts
> +        new CustomEvent("beforechange", {
@yodas7 
Is daikin-` prefix needed? Please track this discussion. https://github.com/dsv-rp/DDS/pull/4#discussion_r1653837344

2024-06-27 09:22 UTC, KoharaKazuya commented on src/components/tab/stories/daikin-tab-group-wc.stories.ts
@yodas7 
[IMO] It would be great if we have stories for 0, 1 and many tabs (to check scroll function).

2024-06-27 09:22 UTC, KoharaKazuya commented on __test__/__image_snapshots__/button-test-js-button-primary-hover-1-snap.png
@yodas7 
Is this an expected change?

2024-06-28 02:35 UTC, yodas7 commented on jest-puppeteer.config.js
> +// Ddd this code to improve chrome browser rendering performance when test
Fixed by merging develop branch.

2024-06-28 02:35 UTC, yodas7 commented on __test__/setupTests.js
> +  failureThreshold: 0.1, // 10%, very large value; this will be changed after we run VRTs in a container
Added comment

2024-06-28 02:37 UTC, yodas7 commented on __test__/__image_snapshots__/button-test-js-button-primary-hover-1-snap.png
Intended. Updated all snapshots by running `npm run test:update`.
FYI we'll do pixel-perfect VRT in #8 so that we don't have to concern about snapshots even more.

2024-06-28 03:36 UTC, yodas7 commented on src/components/tab/stories/daikin-tab-group-wc.stories.ts
Added except for 0 tabs.  
Tab group component requires at least one active tab exists in children (wrote comment on component class JSDoc).

2024-06-28 04:43 UTC, KoharaKazuya commented on src/components/tab/stories/daikin-tab-group-wc.stories.ts
Thanks

2024-06-28 04:46 UTC, KoharaKazuya commented on __test__/__image_snapshots__/button-test-js-button-primary-hover-1-snap.png
I got it. No problem.

2024-06-28 04:47 UTC, KoharaKazuya commented on __test__/setupTests.js
> +  failureThreshold: 0.1, // 10%, very large value; this will be changed after we run VRTs in a container
Thanks!

2024-07-03 01:25 UTC, yodas7 commented
@KoharaKazuya @hiro-daikin 
Could you review this PR?

2024-07-03 02:57 UTC, KoharaKazuya commented on src/components/tab-group/daikin-tab-group.ts
> + * NOTE: If there is no tab available in the child elements, i.e., zero tabs, or if all tabs are disabled, it is ILLEGAL.
@yodas7 
Does `ILLEGAL` mean undefined behavior? In my opinion, for safety, we should define some behavior. Any behavior is fine. What do you think?

2024-07-03 03:20 UTC, yodas7 commented on src/components/tab-group/daikin-tab-group.ts
> + * NOTE: If there is no tab available in the child elements, i.e., zero tabs, or if all tabs are disabled, it is ILLEGAL.
@KoharaKazuya 
Undefined behavior is correct.
I'd like to define "undefined behavior" to include unintended display, generation of unintended values, and throwing of exceptions, but not freezing.
In practice, it will probably remain unchanged as it was effective in the past, but the library does not guarantee any behavior and the behavior may change due to version upgrades.

2024-07-03 05:58 UTC, KoharaKazuya approved these changes

2024-07-03 06:10 UTC, yodas7 commented
@rinjInTokyo invented a drastic improvement that eliminates the need to attach listeners by bubbling events. I will not change it in this PR as it has already been reviewed, but will refactor it in the future.

2024-07-04 01:08 UTC, hiro-daikin requested changes

2024-07-04 01:08 UTC, hiro-daikin commented on src/components/tab/daikin-tab.ts
> +    ].join(" ");
Any reason why we're not using cva? 
We can also use it to automatically get types

2024-07-04 01:08 UTC, hiro-daikin commented on src/components/tab-group/daikin-tab-group.ts
> + * NOTE: If there is no tab available in the child elements, i.e., zero tabs, or if all tabs are disabled, it is ILLEGAL.
Should we throw an error for these edge cases?

2024-07-05 06:31 UTC, yodas7 commented on __test__/Tab.test.js
> +    expect(isDisabled).toBe(false);
We need to implement a tab panel that is not yet in this PR.
I'll try to implement a tab panel on this PR later.

2024-07-05 06:32 UTC, yodas7 commented on src/utils/decoratorListener.ts
> +export function on<K extends keyof HTMLElementEventMap>(
I'll add comments later.
I also feel that it would be better to create a base class rather than mixins, so I'll change that as well.

2024-07-05 06:34 UTC, yodas7 commented on src/components/tab-group/daikin-tab-group.ts
> + * NOTE: If there is no tab available in the child elements, i.e., zero tabs, or if all tabs are disabled, it is ILLEGAL.
I'm not sure how best to inform users (developers) when a component is used in a way that it is not intended to be used.
For example, frameworks such as React only show errors during development and are silent in production builds.
Should we incorporate such a mechanism?

2024-07-05 06:53 UTC, yodas7 commented
I'd like to wait for #8 to be merged as both this PR and #8 may change component fundamentals.

2024-07-10 09:12 UTC, yodas7 commented on src/components/tab/daikin-tab.ts
> +    ].join(" ");
Migrated to cva.

2024-07-10 09:14 UTC, yodas7 commented on src/utils/mixinLifecycle.ts
> +export function mixinLifecycle<T extends Constructor<LitElement>>(
These mixins and decorators proved unnecessary and were removed to reduce complexity.

2024-07-10 09:14 UTC, yodas7 commented on src/utils/decoratorListener.ts
> +export function on<K extends keyof HTMLElementEventMap>(
These mixins and decorators proved unnecessary and were removed to reduce complexity.

2024-07-10 09:15 UTC, yodas7 commented on __test__/Tab.test.js
> +    expect(isDisabled).toBe(true);
Updated.

2024-07-10 09:15 UTC, yodas7 commented on __test__/Tab.test.js
> +    expect(isDisabled).toBe(false);
Implemented.

2024-07-10 09:23 UTC, yodas7 commented on src/components/tab-group/daikin-tab-group.ts
> + * NOTE: If there is no tab available in the child elements, i.e., zero tabs, or if all tabs are disabled, it is ILLEGAL.
lit-html seems to use `development` field of `exports` in [package.json](https://github.com/lit/lit/blob/main/packages/lit-html/package.json#L15-L28).
ref: https://nodejs.org/api/packages.html#community-conditions-definitions

Ultimately, I think it would be best to provide both development and production code, as lit-html does, but I'm not sure at what point we should do that.
As for building, it is easy to achieve as it is just a `vite build` twice with different modes.

2024-07-10 20:31 UTC, hiro-daikin commented on src/components/tab-group/daikin-tab-group.ts
> + * NOTE: If there is no tab available in the child elements, i.e., zero tabs, or if all tabs are disabled, it is ILLEGAL.
@yodas7 Since one goal of a design system is to have uniform design/UI across projects, I think it's okay to throw the error in both development and production. 

If we aren't strict in the beginning, it would be extremely hard to change later. 
If there is a use case which isn't covered, the user can file an issue/ticket.

2024-07-11 05:56 UTC, yodas7 commented on src/components/tab-group/daikin-tab-group.ts
> + * NOTE: If there is no tab available in the child elements, i.e., zero tabs, or if all tabs are disabled, it is ILLEGAL.
@hiro-daikin 
Shortly after I wrote my comment, I changed it to include development builds.
Sorry for not notifying you.
I would appreciate it if you could check to see if this change looks good.

2024-07-12 09:13 UTC, yodas7 commented on package.json
> +      "development": {
The official information is only on the [Webpack website](https://webpack.js.org/guides/package-exports/#providing-devtools-or-production-optimizations).
[Vite also supports `development` condition](https://ja.vitejs.dev/config/shared-options#resolve-conditions).

- About nested conditions: https://nodejs.org/api/packages.html#nested-conditions
- Known community conditions : https://nodejs.org/api/packages.html#community-conditions-definitions

2024-07-12 09:18 UTC, yodas7 commented on package.json
> +      "development": {
A practical examples can be found here

- https://github.com/lit/lit/blob/main/packages/lit-html/package.json
- https://github.com/vuejs/core/blob/main/packages/runtime-dom/package.json

2024-07-12 09:33 UTC, KoharaKazuya commented on package.json
> +      "development": {
Thank you! I see.

2024-07-12 09:34 UTC, KoharaKazuya approved these changes

2024-07-15 17:47 UTC, hiro-daikin requested changes

2024-07-15 17:47 UTC, hiro-daikin commented on .storybook/react/main.ts
> +if (!env.STORYBOOK_MAIN_LOADED) {
Can you add comments for this block?

2024-07-15 17:47 UTC, hiro-daikin commented on build/vite/storybook-framework-loader.ts
> +`;
There seems to be some formatting issues here. 
Does prettier not catch template strings?

2024-07-15 17:47 UTC, hiro-daikin commented on package.json
> +    "build": "tsc -b && vite build && vite build --mode development",
I'm assuming this builds both for development and production?
Would it be better to separate this out to a `build:dev` script?

Main concern is it would take twice as long to build for production (such as in CICD pipeline)

2024-07-15 17:47 UTC, hiro-daikin commented on scripts/storybook-ci.ts
> +  console.error("Removing node_modules/.cache/storybook...");
Does this prevent you from proceeding?
If not, would `console.info` or `console.warn` be more appropriate?

2024-07-15 17:47 UTC, hiro-daikin commented on src/components/tab/stories/daikin-tab.stories.ts
> +    // should react if inner button clicked
```suggestion
    // should not react if inner button clicked
```

2024-07-15 17:47 UTC, hiro-daikin commented on src/components/tab/stories/daikin-tab.stories.ts
> +    // should also react if outer button clicked
```suggestion
    // should also not react if outer button clicked
```

2024-07-16 01:21 UTC, yodas7 commented on src/components/tab/stories/daikin-tab.stories.ts
> +    // should react if inner button clicked
THanks.

2024-07-16 01:24 UTC, yodas7 commented on scripts/storybook-ci.ts
> +  console.error("Removing node_modules/.cache/storybook...");
I wanted to output to stderr because Playwright throws all server side stdout logs away.
`console.error` is confusing, so I changed it to `stderr.write` and added a comment.

2024-07-16 01:27 UTC, yodas7 commented on package.json
> +    "build": "tsc -b && vite build && vite build --mode development",
Yes, they are.

In certain cases, such as testing, you may only need one of the builds, but both must be present for the final publication.
I am concerned that by splitting up the commands, it makes it easier for `dist` to be incomplete.

2024-07-16 01:29 UTC, yodas7 commented on build/vite/storybook-framework-loader.ts
> +`;
Prettier will only format template strings under certain conditions (i.e., when it is safe to change the code).
I have addressed this by creating the object on the plugin side and making the code template simpler.

2024-07-16 01:31 UTC, yodas7 commented on .storybook/react/main.ts
> +if (!env.STORYBOOK_MAIN_LOADED) {
Moved this type of processing to main-common and wrote a comment there.

2024-07-19 23:28 UTC, hiro-daikin commented on package.json
> +    "build": "tsc -b && vite build && vite build --mode development",
I see your concern. 

I've seen some patterns where they split up into:
build:dev
build:prod
build (combination of above 2)

If it makes sense, we can also follow this sort of pattern.

I'll leave the final implementation up to you, however.

2024-07-19 23:29 UTC, hiro-daikin approved these changes

2024-07-24 06:55 UTC, yodas7 commented on package.json
> +    "build": "tsc -b && vite build && vite build --mode development",
It only took 12 seconds to build, so I think I'll leave it as it is for now.
If the build itself starts taking longer in the future, I will consider separating it.

2024-07-24 08:04 UTC, merged