DDS-1335 [List] Add List Component
dsv-rp/DDS pull request #70
Opened 2024-09-17 06:02 UTC by poetrainy

This PR adds List (`daikin-list`, `daikin-list-item`) component.

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1335](https://daikinsvoil.atlassian.net/browse/DDS-1335)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/5MvuYbtMDzv3LiIm7nwJ3x/DDS%3A-Design-Kit?node-id=29847-661&node-type=canvas&t=5ZiAHPO1y9PMOJRt-0)

## API Design

- [JIRA Wiki - List](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3170041857/List+Component+API)
- [JIRA Wiki - List Item](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3166896129/List+Item+Component+API)

## How Has This Been Tested?

### Visual Regression Tests

- \[Button; Link\] types and \[Left; Nothing\] icons matrix for List Item Component.

### Interaction Tests

- Fires `click` event when the list item is clicked.

## Checklist

- [x] I have added a changeset file that describes the changes.  
       _Hint_: run `npx changeset`.
- [x] I have performed a self-review of my code.
- [x] I have added appropriate visual regression tests.
- [x] I have added appropriate interaction tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.  
       _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the component can be operated using only the keyboard.
- [x] I have confirmed that the focus state of the component is visually discernible.

2024-09-17 06:44 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +  leftIcon: IconType | null = null;
reflect?

2024-09-17 06:45 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +    const LIST_CLASS_NAME = cvaList({ disabled: this.disabled });
```suggestion
    const cn = cvaList({ disabled: this.disabled });
```

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +      linkDisabled: html`<div class=${LIST_CLASS_NAME}>${content}</div>`,
As `<a>` is an inline element, an alternative element should also be an inline element.

```suggestion
      linkDisabled: html`<span class=${LIST_CLASS_NAME}>${content}</span>`,
```

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +    const content = html`<div class="flex items-center gap-2">
You cannot use `<div>` inside `<button>` and `<span>`.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#technical_summary

```suggestion
    const content = html`<span class="flex items-center gap-2">
```

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +      isLink && this.disabled ? "linkDisabled" : isLink ? "link" : "button";
A bit confusing name.

```suggestion
    const wrapperType =
      isLink && this.disabled ? "linkDisabled" : isLink ? "link" : "button";
```

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/stories/daikin-list-item.stories.ts
> +  },
Add a test that checks if the list is rendered as a link.

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/stories/daikin-list-item.stories.ts
> +      await userEvent.type(innerInput, "Example");
click?

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/stories/daikin-list-item.stories.ts
> +    // should react if inner button clicked
```suggestion
    // should not react if inner button clicked
```

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/stories/daikin-list-item.stories.ts
> +      await userEvent.type(innerInput, "Example");
click?

2024-09-17 06:58 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +        true: ["text-daikinNeutral-200", "[&>*]:text-daikinNeutral-200"],
Do we need `[&>*]:text-daikinNeutral-200`?

```suggestion
        true: ["text-daikinNeutral-200"],
```

2024-09-17 06:59 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +      ></daikin-icon>`;
If the icon is fixed (not user-specified), you can use `i-daikin-*` directly. Either is fine.

2024-09-18 02:51 UTC, yodas7 commented on src/components/list-item/stories/daikin-list-item.stories.ts
> +};
You might want to add a `LinkDisabled` story and test that there are no links or buttons.

2024-09-18 05:42 UTC, yodas7 reviewed
Don't we need list and listitem roles?

2024-09-18 06:15 UTC, yodas7 approved these changes
LGTM

2024-09-18 06:15 UTC, yodas7 commented on src/components/list/stories/framework-wc.ts
> +        <daikin-list-item ?disabled=${true}>List item label 3</daikin-list-item>
nit.

```suggestion
        <daikin-list-item disabled>List item label 3</daikin-list-item>
```

2024-09-20 06:45 UTC, yodas7 commented
@poetrainy 
Could you share the page you referred to implement keyboard navigations?

2024-09-20 08:21 UTC, poetrainy commented
I made a mistake in the test section, so I fixed it again.

2024-09-20 09:43 UTC, yodas7 commented
It seems that something strange is happening with `focus-visible`.
I will investigate next week.

2024-09-26 06:21 UTC, yodas7 requested changes

2024-09-26 06:21 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +      ${this.label}
Please use slots for everything that is rendered on the DOM. In particular, please use the default slot for the main content.
If you need additional slots, please use named slots.

```suggestion
      <slot></slot>
```

2024-09-26 06:21 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +  rightArrowIcon: boolean = false;
Please check with the designer whether the icon is fixed or not. If it is variable, it should be something like rightIcon.

otherwise nit. 

```suggestion
  chevron: boolean = false;
```

2024-09-26 06:21 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +    </slot>`;
Not sure if we should wrap the icon with `<slot>`.
Maybe we should do `<slot name="..."></slot><span class="..."></span>`.

2024-09-26 07:36 UTC, poetrainy commented on src/components/list-item/daikin-list-item.ts
> +  rightArrowIcon: boolean = false;
The List is not yet a component that is ready for development, so we will check it as soon as we reach that stage.

2024-09-26 07:55 UTC, poetrainy commented on src/components/list-item/daikin-list-item.ts
> +    </slot>`;
Is it inappropriate to make the icon recognize the alternative content as a slot?

2024-09-26 08:02 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
> +    </slot>`;
It's more a question of whether there is a possibility of using icons and slots at the same time, though it doesn't seem to be the case according to Figma...

2024-09-27 04:55 UTC, poetrainy commented on src/components/list-item/daikin-list-item.ts
> +    </slot>`;
From Figma, it is not possible to tell whether either an icon or a slot will definitely exist, or whether it is possible that neither will exist. We will check with the designer, including whether the icon is fixed to the arrow.

2024-10-02 06:47 UTC, poetrainy commented
I have checked with the designer about the icon issue and resolved it. However, I am still waiting for the designer to respond regarding the interaction (hover, action, focus) with list items when there is an action within the list item.

2024-10-11 06:07 UTC, yodas7 commented on src/components/list-item/stories/framework-wc.ts
> +      List item label
This should be customizable via Storybook args.

2024-10-11 06:07 UTC, yodas7 commented on src/components/list-item/stories/common.ts
> +  hasSlot: {
`action` or `actionSlot`

```suggestion
  actionSlot: {
```

2024-10-11 06:07 UTC, yodas7 commented on src/components/list-item/stories/daikin-list-item.stories.ts
> +    disabled: false,
```suggestion
    disabled: false,
    actionSlot: false,
```

2024-10-16 22:55 UTC, hiro-daikin requested changes

2024-10-16 22:55 UTC, hiro-daikin commented on src/components/list/daikin-list.ts
> +    return html`<div role="list">
It's almost always better to use native elements: `ul`, `li`.
This handles keyboard navigation automatically. 
This will probably mean we need to to give users the option of choosing between the two.

Here is an example: https://cedar.rei.com/components/list

2024-10-17 03:06 UTC, poetrainy commented on src/components/list/daikin-list.ts
> +    return html`<div role="list">
@hiro-daikin cc: @yodas7 
We have considered this, but as the custom element is the top-level component directly under daikin-list (daikin-list-item), it is difficult to completely guarantee accessibility with the ul / li structure.
https://stackoverflow.com/questions/78129019/can-you-have-an-li-in-a-autonomous-custom-element-with-the-parent-ul-not
We can also replace any element with a custom element at the top level, but it is possible that some browsers do not support this behavior.
https://stackoverflow.com/questions/74561984/how-to-define-a-custom-li-element-with-respect-to-accessability-requirements

For this reason, I would like to use the role to represent the list as it is, rather than using ui / li.

2024-10-17 22:24 UTC, hiro-daikin commented on src/components/list/daikin-list.ts
> +    return html`<div role="list">
@poetrainy 
Thank you for the explanation. 
In that case, this should be okay as long it passes our automatic/manual testing

2024-10-17 22:24 UTC, hiro-daikin approved these changes

2024-10-18 01:57 UTC, yodas7 commented on src/components/list-item/daikin-list-item.ts
For the purpose of this time, it is more concise to use `group-hover`.

2024-10-22 08:51 UTC, merged