DDS-1299 [Tree] Add Tree Component
dsv-rp/DDS pull request #73
Opened 2024-09-19 01:32 UTC by poetrainy

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +        ${this.label}
I think we should use slot here.

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +  _children!: (DaikinTreeSection | DaikinTreeItem)[];
```suggestion
  private _children!: (DaikinTreeSection | DaikinTreeItem)[];
```

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +  hierarchy: number = 0;
```suggestion
  @property({ type: Number, reflect: true })
  level: number = 0;
```

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      </span>`,
Let's use <a> without href for disabled links. See list and button components.

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      aria-label=${this.textContent ?? ""}
I don't think we need this.

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +  hierarchy: number = 0;
```suggestion
  @property({ type: Number, reflect: true })
  level: number = 0;
```

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +    }
We will need to do the same thing with slotchange.

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      style=${`--padding-left:${12 + this.hierarchy * 36}px`}
Can't you achieve this without managing the level by simply setting padding-left to <slot>?

2024-10-18 02:31 UTC, yodas7 commented on src/components/tree/daikin-tree.ts
> +    }
Comments on what we will do are needed.

Also, in order to improve readability, it is better to have the descendants' events handled by the descendants themselves as much as possible. Remember the implementation with the accordion.

2024-10-18 06:06 UTC, poetrainy commented on src/components/tree-item/daikin-tree-item.ts
> +      style=${`--padding-left:${12 + this.hierarchy * 36}px`}
@yodas7 
I think you can set padding-left to <slot>, but I will need to manage the levels. This is because there is no (real) limit to the hierarchy, and you cannot determine which level you are on without looking at the parent element.

2024-10-18 06:09 UTC, poetrainy commented on src/components/tree-section/daikin-tree-section.ts
> +        ${this.label}
@yodas7 
This is also true of tree-item, but I'm not sure whether I should change the label the default for the slot, or whether I should just add a new slot=“label”.

2024-10-18 06:14 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +        ${this.label}
@poetrainy 
I think we should use `<slot name="label">` for `daikin-tree-section` and unnamed `<slot>` for `daikin-tree-item`.

2024-10-18 06:16 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      style=${`--padding-left:${12 + this.hierarchy * 36}px`}
@poetrainy 
Since it seems that the level information is only used for padding purposes, I thought that the `level` (`hierarchy`) property might not be necessary, but is it needed for other purposes?

2024-10-23 07:59 UTC, yodas7 commented
@poetrainy 
Please resolve conflicts.

2024-10-24 00:45 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      style=${`--padding-left:${12 + this.hierarchy * 36}px`}
Had conversation. We have to manage level as each item has full width and we cannot add padding to section children container.

2024-10-28 01:13 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +  }
nit.

```suggestion
  override focus(options?: FocusOptions): void {
    this._focusableElement.focus(options);
  }

  /**
   * Focuses on the inner button.
   * This is provided to ensure consistency of the interface.
   * @param options focus options
   */
  focusLastItem(options?: FocusOptions): void {
    this.focus(options);
  }
```

2024-10-28 01:13 UTC, yodas7 commented on src/components/tree/daikin-tree.ts
> +};
Create `common.ts` in the directory for these items.

2024-10-29 01:47 UTC, poetrainy commented
@yodas7 
I've made the necessary changes, including the one to Slack, but I'm not sure if it's been implemented exactly as you intended, so could you please check?

2024-10-29 05:09 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +      this.focus();
```suggestion
      this.focus();
```

2024-10-30 07:56 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      aria-selected=${this.selected}
Whether or not to add this depends on the meaning of `this.selected`.
Also, we might want to check `this.disabled` as well here.

2024-10-30 07:56 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +    return html`<div role="treeitem" aria-selected=${this._open}>
see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treeitem_role#examples

```suggestion
    return html`<div role="treeitem" aria-expanded=${this._open}>
```

2024-10-30 07:56 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +    return html`<div role="treeitem" aria-selected=${this._open}>
If we're providing select feature, we should also add `aria-selected` and `aria-disabled`.

2024-11-15 06:08 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +   * This is usually specified automatically and the user does not operate it.
```suggestion
   * Ignored if disabled.
   * Controlled by `daikin-tree` if its `selectable` is true.
```

2024-11-15 06:08 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +   * This is usually specified automatically and the user does not operate it.
```suggestion
   * Ignored if disabled.
   * Controlled by `daikin-tree` if its `selectable` is true.
```

2024-11-15 06:08 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +   * This is usually specified automatically and the user does not operate it.
nit. Also, we should move this below the `disabled` prop.

2024-11-15 06:08 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +   * This is usually specified automatically and the user does not operate it.
nit. Also, we should move this below the `disabled` prop.

2024-11-15 06:08 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      selected: this.selected,
nit?

```suggestion
      selected: this.selected && !this.disabled,
```

2024-11-15 06:08 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      role="treeitem"
```suggestion
      role="treeitem"
      aria-disabled=${this.disabled}
```

2024-11-15 06:12 UTC, yodas7 commented on src/components/tree/daikin-tree.ts
> +   * The value of the currently selected tree section or tree item.
```suggestion
   * The value of the currently selected tree section or tree item.
   * Only used if `selectable` is `true`.
```

2024-11-15 06:12 UTC, yodas7 commented on src/components/tree/daikin-tree.ts
> +   * Whether or not to enable tree selection.
```suggestion
   * Whether or not to enable tree selection.
   * When enabled, tree sections and items can be selected by click, and the `selected` property of the `daikin-tree` and its descendants will be automatically controlled.
   * Even if this is disabled, you can still set the `selected` property of sections and items yourself.
```

2024-11-15 07:07 UTC, poetrainy commented on src/components/tree-section/daikin-tree-section.ts
> +  selectedItem(selected?: string): void {
@yodas7 
When `disabled`, is it okay not to update this value?
Currently, there is no system that propagates disabled to child elements.

2024-11-15 07:51 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +  selectedItem(selected?: string): void {
@poetrainy 
If disabled, the section will not open, so the items underneath it will not be selectable.
Also, if we want to be more accurate, when the selected item or its ancestors become disabled, we need to update the `selected` of the tree to `null`.

2024-11-22 08:56 UTC, yodas7 reviewed
When a Tree is selectable and its descendant section is set to `disabled`, the following needs to be done:

1. Set the `selected` of the section's descendants to `false`
2. Update tree's `selected` as needed.
   i.e. If the section's descendants are the only selected items, set the tree's `selected` to `null`

I don't have a good idea of how to achieve the second part.

2024-11-25 06:25 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +    return null;
nit.

```suggestion
    return !this.disabled && this.selected ? this.value : null;
```

2024-11-25 06:25 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +   * When the tree item is selected, this.value is returned. When it is not selected or when this.disabled is true, null is returned.
nit.

```suggestion
   * Returns `this.value` if selected, or `null` if not selected.
   *
   * @returns `this.value` if selected. `null` if not selected.
```

2024-11-25 06:25 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +      emitTreeSelect(this);
This line should be placed outside the if statement.
Selection and opening/closing are independent concepts.

2024-11-25 06:25 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +  private _handleKeyDown(event: KeyboardEvent): void {
If the tree is selectable, it is necessary to call `preventDefault` and `emitTreeSelect(this)` because it is better not to toggle the section with Space or Enter.
If it is difficult to check `selectable` here, it is okay to always call `preventDefault` for the relevant key.

https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-1a/

2024-11-26 05:32 UTC, yodas7 requested changes

2024-11-26 05:32 UTC, yodas7 commented on src/utils/isSimpleKey.ts
sorry could you rename this file to `is-simple-key.ts` and `reDispatch.ts` to `re-dispatch.ts`?
I forgot we are supposed to use kebab-case for filenames.

2024-11-26 05:47 UTC, yodas7 commented
@poetrainy 
I'm not sure why we need [d20e394](https://github.com/dsv-rp/DDS/pull/73/commits/d20e3945d535f92baf93f814233c710b71957ab9).
Could you explain this?

2024-11-26 07:59 UTC, poetrainy commented
@yodas7 
This has been fixed because `selectable` was not being passed down to the descendant tree sections.

2024-11-27 01:53 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +   * Controlled by `daikin-tree` if its `selectable` is true.
```suggestion
   * Whether the tree item is selected.
   * Ignored if disabled.
   * Controlled by `daikin-tree` if its `selectable` is true.
   * If the tree's `selected` is false, you can manually set this property to control the display of the selected state.
```

2024-11-27 01:53 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +   * Controlled by `daikin-tree` if its `selectable` is true.
```suggestion
   * Whether the tree item is selected.
   * Ignored if disabled.
   * Controlled by `daikin-tree` if its `selectable` is true.
   * If the tree's `selected` is false, you can manually set this property to control the display of the selected state.
```

2024-11-27 01:54 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +   * Controlled by `daikin-tree`.
```suggestion
   * Controlled by `daikin-tree`.
   *
   * @private
```

2024-11-27 02:48 UTC, yodas7 commented on .changeset/proud-rules-give.md
> +Add Tree Component.
```suggestion
Tree: Initial Implementation.
```

2024-11-27 02:49 UTC, yodas7 commented on .changeset/proud-rules-give.md
> +"@daikin-oss/design-system-web-components": patch
We decided to treat new components as minor change, though they do not contain breaking changes.

```suggestion
"@daikin-oss/design-system-web-components": minor
```

2024-11-27 02:49 UTC, yodas7 approved these changes

2024-12-02 22:02 UTC, hiro-daikin requested changes

2024-12-05 09:12 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      this.type === "link"
@hiro-daikin 
This is because we have not yet found an appropriate method for expressing the entire item as a link.
If the Link component could “delegate” its style to another component (in this case, the Tree Item), we could design it that way, but at present we have not found a method for doing so.
However, the Link in Tree Item design is superior. It is worth researching in the future.

2024-12-09 01:03 UTC, hiro-daikin commented on src/components/tree-item/daikin-tree-item.ts
> +      this.type === "link"
@yodas7 

I also want to take a step back and ask if we really need this?
I looked at a few popular libraries, and they don't have support for a `link` type. 
Removing this until we get feedback is also a valid approach.

2024-12-09 01:35 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +        : html`<button
@hiro-daikin 
After investigating for a while, I found out why the button wasn't being used.
The reason was that the ARIA role allowed for the `button` element was unexpectedly small, and `treeitem` was also outside the scope.
ref: [button mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#technical_summary), [div mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#technical_summary).
We should also use a `div`.

@poetrainy 
Could you rewrite the code to use `<div>`?
Please beware of `tabindex`.

2024-12-09 01:42 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +        : html`<button
I had a slight misunderstanding. Even with the current code, there was no structural problem because there was a `<button>` under `<div role=“treeitem”>`.
However, since it is not clear what is nested, I think it is better to implement this together with the deletion of `type=link` in any case. (@poetrainy)

2024-12-09 01:44 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +      this.type === "link"
Decided to remove the link feature as it's unclear we need this for now.

2024-12-09 02:34 UTC, poetrainy commented on src/components/tree-item/daikin-tree-item.ts
> +        : html`<button
@hiro-daikin @yodas7 
The links and buttons have been removed and replaced with `<div>`.

2024-12-09 05:49 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +    "bg-[--color-base]",
Move this to `disabled: false`.
The current implementation reacts to hover even if disabled.


```suggestion
```

2024-12-09 05:49 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +    "cursor-pointer",
Same.

```suggestion
```

2024-12-09 05:49 UTC, yodas7 commented on src/components/tree-item/daikin-tree-item.ts
> +        true: ["text-system-state-disabled"],
`"hover:bg-[--color-base]", "active:bg-[--color-base]"` is useless.

```suggestion
        false: ["bg-[--color-base]", "cursor-pointer"],
        true: ["text-system-state-disabled"],
```

2024-12-09 05:49 UTC, yodas7 commented on src/components/tree-section/daikin-tree-section.ts
> +      </button>
Let's use `<div>` here like APG does.

2024-12-10 01:42 UTC, hiro-daikin approved these changes

2024-12-10 09:37 UTC, yodas7 approved these changes
Thank you!

2024-12-11 01:22 UTC, merged