DDS-1294 [Tooltip] Tooltip does not overflow parent element, Tooltip does not open even if trigger has focus
dsv-rp/DDS pull request #74
Opened 2024-09-30 09:05 UTC by poetrainy

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1501](https://daikinsvoil.atlassian.net/browse/DDS-1501)

## Problem

- Tooltip does not overflow parent element.
- Tooltip does not open even if trigger has focus.

## Root Cause

- Tooltip was at the same level as child elements, and the parent element could not overflow.
- There was no event setting for focus.

## Solution

- The location of the tooltip has been changed using the Popover API.
- An event has been set for focus.

## How Has This Been Tested?

- In the visual test, you can see that the parent element overflows.
- In the interaction test, we have added a test where a tooltip appears when the element is focused.

## Checklist

- [x] I have added a changeset file that describes the changes.
- [x] I have performed a self-review of my code.
- [x] I have added/updated appropriate regression tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.
- [x] I have confirmed that the bug fix does not affect the keyboard accessibility of the component.
- [x] I have confirmed that the fix does not introduce any new visual regressions.

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +        middleware: [offset({ mainAxis: spacing }), flip()],
Can you tell me why you removed `shift()`?

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  }
It is easier to understand the function that receives the value than the toggle.

```suggestion
  private _setOpenState(newState: boolean): void {
    if (this.open === newState) {
      return;
    }

    this._popover.togglePopover(newState);
    this.open = newState;
  }
```

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +      this._changeOpenState();
```suggestion
    if (this.trigger === "hover") {
      this._setOpenState(true);
```

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    }
```suggestion
    this._isFocused = true;
    this._setOpenState(true);
```

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
>      }
Not sure if we should hide tooltip even if the mouse cursor is on the trigger.

```suggestion
    this._changeOpenState(false);
    this._isFocused = false;
```

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +        @mouseleave=${this._handleMouseLeave}
Maybe we should move event listeners to `<slot>`

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +          this.dispatchEvent(new Event("toggle", event))}
Should we handle `preventDefault()`?

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +          this.dispatchEvent(new Event("toggle", event))}
Also, we should use `ToggleEvent` instead of `Event`.

2024-10-04 02:20 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +   * Specify the value of the popover attribute in the Popover API.
We should state which values should be used in which situations.

2024-10-04 02:21 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
>    }
I don't think this handler to be useful.

2024-10-04 02:55 UTC, poetrainy commented on src/components/tooltip/daikin-tooltip.ts
> +        middleware: [offset({ mainAxis: spacing }), flip()],
@yodas7 
As I mentioned in my previous consultation, `shift()` stopped working because I used the Popover API.

2024-10-09 05:39 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +        middleware: [offset({ mainAxis: spacing }), flip()],
@poetrainy 
I tried it out, but I found that we still needed to use `shift()` to prevent the text from going off the screen.

<img width="307" alt="スクリーンショット 2024-10-09 14 36 35" src="https://github.com/user-attachments/assets/52593293-8e2a-4c41-bbcc-b6b6ad31f1e4">
<img width="307" alt="スクリーンショット 2024-10-09 14 36 50" src="https://github.com/user-attachments/assets/9a5f9cdc-4e77-403e-906f-910e4daf9b9c">

I think one of the reasons is that the current Storybook demo does not allow us to try this out.

2024-10-09 05:39 UTC, yodas7 requested changes
Use `shift()`.
We may also want to expand the demo area to fill the entire viewport.

2024-10-09 07:35 UTC, yodas7 reviewed
Can you make it into a Storybook demo where users can try out the tooltip behavior (flip, shift)?

2024-10-15 05:25 UTC, poetrainy commented
@yodas7 
I have prepared a view area with a wider area.

2024-10-18 08:55 UTC, yodas7 reviewed
We should manage whether the focus is on the element or not, and whether the tooltip is open or not, separately.
Whether or not to display the tooltip is determined by a logical OR of these.

We also need to be prepared for the case where the user changes the `open` property on their own.

Even with the proposed fix, there is a problem where the tooltip is displayed after the user changes `open` to `false` after the element has been focused and hovered over, but this is an edge case and is ignored.

2024-10-18 08:55 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
>    }
Setting `open` can be done in `willUpdate` method.
Calling `.togglePopover` should be done in `updated` method.

2024-10-18 08:55 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    }
```suggestion
    if (this.trigger === "hover") {
      this._isMouseOpened = false;
    }
```

2024-10-18 08:55 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +    this._setOpenState(true);
```suggestion
```

2024-10-18 08:55 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
>      }
```suggestion
    this._isFocused = false;
```

2024-10-18 08:55 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
>    }
This should be done in `updated` method.

2024-10-23 04:58 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
>      }
Always reference the source (SSoT).

```suggestion
    if (reDispatch(this, event, new ToggleEvent("beforetoggle", event))) {
      this.open = event.newState === "open";
    }
```

2024-10-23 07:51 UTC, yodas7 commented on .changeset/rude-pigs-hide.md
> +**BREAKING CHANGE** Tooltip: The `trigger` and `tooltip` of the part attribute have been removed. (DDS-1501)
```suggestion
**BREAKING CHANGE** Tooltip: The `trigger` and `tooltip` CSS parts have been removed. (DDS-1501)
```

2024-10-23 07:52 UTC, yodas7 commented on .changeset/rude-pigs-hide.md
> +Tooltip: The `beforetoggle` and `toggle` custom events have been removed. (DDS-1501)
```suggestion
```

2024-10-23 07:53 UTC, yodas7 approved these changes

2024-10-25 01:20 UTC, hiro-daikin approved these changes

2024-10-29 01:58 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  _isFocused = false;
```suggestion
  private _isFocused = false;
```

2024-10-29 01:58 UTC, yodas7 commented on src/components/tooltip/daikin-tooltip.ts
> +  _isMouseOpened = false;
```suggestion
  private _isMouseOpened = false;
```

2024-10-29 07:33 UTC, merged