DDS-1301 [Toggle] Add `switch` role
dsv-rp/DDS pull request #78
Opened 2024-10-08 08:48 UTC by poetrainy

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1531](https://daikinsvoil.atlassian.net/browse/DDS-1531)

## Problem

The `switch` role has not been assigned.

## Solution

Assign the `switch` role.

## How Has This Been Tested?

- I tested that there is a component with a `switch` role.

## Checklist

- [x] I have added a changeset file that describes the changes.
      _Hint_: run `npx changeset`.
- [x] I have performed a self-review of my code.
- [x] I have added/updated appropriate regression tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.
      _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the bug fix does not affect the keyboard accessibility of the component.
- [x] I have confirmed that the fix does not introduce any new visual regressions.

[DDS-1531]: https://daikinsvoil.atlassian.net/browse/DDS-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-09 05:32 UTC, yodas7 requested changes

2024-10-09 05:32 UTC, yodas7 commented on src/components/toggle/daikin-toggle.ts
> +      aria-checked=${this.checked}
We don't need aria-checked for checkbox.

> If the switch element is an HTML input[type="checkbox"], it uses the HTML checked attribute instead of the aria-checked property.

2024-10-09 07:25 UTC, yodas7 commented on .changeset/tricky-stingrays-obey.md
> +"@daikin-oss/design-system-web-components": minor
```suggestion
"@daikin-oss/design-system-web-components": patch
```

2024-10-09 07:25 UTC, yodas7 commented on src/components/toggle/daikin-toggle.ts
> +    // eslint-disable-next-line lit-a11y/role-has-required-aria-attrs
```suggestion
    // eslint-disable-next-line lit-a11y/role-has-required-aria-attrs -- We don't need `aria-checked` for `<input type="checkbox">`.
```

2024-10-09 07:36 UTC, yodas7 approved these changes
LGTM

2024-10-16 23:02 UTC, hiro-daikin approved these changes

2024-10-22 08:40 UTC, merged