DDS-1122 DDS-1123 Migration to Vite + Playwright
dsv-rp/DDS pull request #8
Opened 2024-06-26 07:45 UTC by yodas7

2024-06-26 07:46 UTC, yodas7 commented
Unfortunately, it is expected to be too large to review...

2024-06-28 08:23 UTC, yodas7 commented
We should create PR that formats all code in current `develop` branch first.
Then I'll change the base branch of this PR to that PR.

2024-07-02 08:16 UTC, yodas7 commented
Draft status removed.

However, it's too much to ask for review in this state, so I'll ask for review after merging #12.

2024-07-03 01:57 UTC, hiro-daikin requested changes

2024-07-03 01:57 UTC, hiro-daikin commented on .prettierignore
> +package-lock.json
How about code output by build?

2024-07-03 01:57 UTC, hiro-daikin commented on README.md
>  ## Contributors
You added some commands, so it might be good to document them

2024-07-03 03:21 UTC, yodas7 commented on README.md
>  ## Contributors
Forgot to update the documents, thanks.

2024-07-03 03:22 UTC, yodas7 commented on .prettierignore
> +package-lock.json
[Prettier respects .gitignore](https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore) so we don't have to put them.

> Prettier will also follow rules specified in the ".gitignore" file if it exists in the same directory from which it is run.

2024-07-03 20:33 UTC, hiro-daikin commented on README.md
> +_We are looking for a more efficient way to import tokens._
I've also considered a monorepo setup, but I haven't looked into how that would work with `token studio` in Figma.

2024-07-03 20:40 UTC, hiro-daikin approved these changes

2024-07-03 21:36 UTC, hiro-daikin commented
This ticket was also assigned to me, but looks like you took care of most of it: https://daikinsvoil.atlassian.net/browse/DDS-1054

The only thing that's missing is a pre-commit hook. 

Would you be able to either add husky to this commit, or add another PR?

2024-07-04 05:15 UTC, yodas7 commented
@hiro-daikin 
Added husky and pre-**push** script.
If we run it on the `pre-commit` hook, it takes longer to commit and in my experience I sometimes lose changes due to malfunction, so I've decided to use the pre-push hook instead.

2024-07-04 05:19 UTC, yodas7 commented on README.md
> +_We are looking for a more efficient way to import tokens._
I had never thought about monorepo, but if it is possible it sounds interesting。

2024-07-04 05:51 UTC, yodas7 commented
@KoharaKazuya @ukkary 

Could you review this?

2024-07-04 05:54 UTC, yodas7 commented
@hiro-daikin 
When I added hiro-san when setting reviewers, I accidentally sent you a re-review request.
Please review if necessary, but if prior approval is sufficient you don't have to.

2024-07-04 06:20 UTC, yodas7 commented
VRT is taking a long time (5m).
We may be able to cut it in half by testing in each of the development mode and production builds, but only in the production build.

2024-07-04 07:24 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +// eslint-disable-next-line @typescript-eslint/no-duplicate-type-constituents
Didn't know we could write comments on `eslint-disable-next-line`.
I actually wanted to make sure that all unions were the same, so I'll create a better type template for this and eliminate `eslint-disable-next-line`.

2024-07-04 07:46 UTC, ukkary commented on tsconfig.lib.json
> +    "target": "ES2022",
Is there any reason that we didn't use same version with tsconfig.node.json?

2024-07-04 08:44 UTC, yodas7 commented on tsconfig.lib.json
> +    "target": "ES2022",
@ukkary 
Good point.

It is difficult because the requirements have not been finalized, but the lib side targets code that is shipped as a library, i.e., code that runs on the browser, so a wide range of environments (browsers) must be considered. The node side targets code that runs in the development environment, so relatively new language features can be used. To show the difference, I've dared to specify different ones.

However, the differences between ES2022 and ES2023 are not that great, so they can be unified.

2024-07-04 08:45 UTC, yodas7 commented on src/components/checkbox/daikin-checkbox.ts
> +// eslint-disable-next-line @typescript-eslint/no-duplicate-type-constituents
Changed to not use intersections.

2024-07-05 02:11 UTC, yodas7 commented
I'll cut out the VRT part and parallelize it.

2024-07-05 06:48 UTC, yodas7 commented on package.json
> +    "taze": "^0.14.0",
@KoharaKazuya 
Removed. I had left it in when I created the project and forgot about it.

2024-07-05 08:06 UTC, ukkary approved these changes

2024-07-05 08:08 UTC, KoharaKazuya approved these changes

2024-07-05 08:27 UTC, merged