DDS-1600 [Text Link] Add Text Link Component
dsv-rp/DDS pull request #93
Opened 2024-11-15 06:39 UTC by poetrainy

This PR adds Button (`daikin-text-link`) component.

## Related Ticket(s) and Links

- JIRA Ticket: [DDS-1600](https://daikinsvoil.atlassian.net/browse/DDS-1600)
- Figma design: [Figma](https://www.figma.com/design/VyaaU8Ta9yzyf0PsURWSSf/branch/0leaJJA7PmIhsRzSWmW7ZM/DDS%3A-Design-Kit?node-id=42103-1784&node-type=section&m=dev)

## API Design

- [JIRA Wiki](https://daikinsvoil.atlassian.net/wiki/spaces/GDS/pages/3336470529/Text+Link+Component+API)

## How Has This Been Tested?

### Visual Regression Tests

- \[HasVisited\] variants and \[Normal; Hover; Pressed; Focus; Disabled\] states matrix.

### Interaction Tests

- Normally, the role is link
- When `disabled`, the role must not be link

## Checklist

- [x] I have added a changeset file that describes the changes.  
       _Hint_: run `npx changeset`.
- [x] I have performed a self-review of my code.
- [x] I have added appropriate visual regression tests.
- [x] I have added appropriate interaction tests.
- [x] I have confirmed that there are no accessibility warnings that can be addressed.  
       _Hint_: check the Accessibility tab in the Storybook.
- [x] I have confirmed that the component can be operated using only the keyboard.
- [x] I have confirmed that the focus state of the component is visually discernible.

2024-11-21 02:01 UTC, yodas7 requested changes
Rename component to "Link".

2024-11-21 04:54 UTC, yodas7 commented on .changeset/seven-pants-kick.md
> +Add Text Link Component. (DDS-1600)
```suggestion
Link: Initial Implementation. (DDS-1600)
```

2024-11-21 05:04 UTC, yodas7 commented on src/components/link/daikin-link.ts
> +  hasVisited = false;
nit.

```suggestion
  @property({ type: Boolean, reflect: true, attribute: "show-visited" })
  showVisited = false;
```

2024-11-21 05:04 UTC, yodas7 commented on src/components/link/daikin-link.ts
> +    "focus-visible:before:h-[calc(100%+2px)]",
Maybe we can use inset? (not tested)

```suggestion
    "focus-visible:before:inset-[-1px]",
```

2024-11-21 05:04 UTC, yodas7 commented on src/components/link/daikin-link.ts
> + * It functions similarly to the HTML `<button>` tag, allowing users to initiate various operations such as submitting data, opening dialogs, or navigating to different sections of an application.
Modify description

2024-11-21 05:08 UTC, yodas7 commented on src/components/link/daikin-link.ts
> + * @slot - A slot for the button content.
Update description.

2024-11-21 05:08 UTC, yodas7 commented on src/components/link/daikin-link.ts
> + * <daikin-link href="#">
nit. I don't think `href="#"` be a good practice in these days.

```suggestion
 * <daikin-link href="https://www.example.com">
```

2024-11-21 05:08 UTC, yodas7 commented on src/components/link/daikin-link.ts
> +    :host([hasVisited]):host(:not([disabled])) a:visited {
nit.

```suggestion
    :host([show-visited]:not([disabled])) a:visited {
```

2024-11-21 05:49 UTC, poetrainy commented
@yodas7 
I'm wondering how much of the attributes that exist in the HTML standard anchor element I should cover.

2024-11-22 08:50 UTC, yodas7 commented
@poetrainy 
Let's assume that it is only necessary to prepare the same properties of other components that use `<a>` tags (e.g. `daikin-button`, `daikin-list-item`).
If necessary, we will expand it at that time together with those components.

2024-11-25 06:16 UTC, yodas7 reviewed
Could you add a VRT for visited links?

2024-11-26 01:17 UTC, poetrainy commented
@yodas7 
I tried a few things with playwright, but it was difficult to test visited.
https://playwright.dev/docs/api/class-browsercontext

2024-11-26 05:50 UTC, yodas7 commented on src/components/link/daikin-link.visual.test.ts
> +      showVisited: showVisited === showVisited,
```suggestion
      showVisited: false,
```

2024-11-26 05:50 UTC, yodas7 commented on src/components/link/daikin-link.visual.test.ts
> +  // NOTE: Has not implemented the VRT for `showVisited`
I don't think we need this `describeEach`.

```suggestion
// FIXME: VRT is not implemented for `:visited` styles, as it will require `launchPersistentContext` which cannot be done with containers.
```

2024-11-26 08:20 UTC, yodas7 approved these changes

2024-11-26 22:00 UTC, hiro-daikin approved these changes

2024-11-27 02:18 UTC, poetrainy commented
Once the background color has been finalized, I will merge this branch.

2024-11-27 02:47 UTC, merged